interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  dynamically_added_crash_region_00000000:
    base_addr: 0x0
    permissions: rw-
    size: 0xa000
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x8000000
    file: Soldering_Iron.bin
    ivt_offset: 0x0
    permissions: r-x
    size: 0x207a8
symbols:
  0x0: impure.c
  0x200: _Min_Heap_Size
  0x400: _Min_Stack_Size
  0x8000000: g_pfnVectors
  0x8000111: __do_global_dtors_aux
  0x8000135: frame_dummy
  0x800017d: memcpy
  0x8000269: Reset_Handler
  0x800026c: CopyDataInit
  0x8000274: LoopCopyDataInit
  0x8000282: FillZerobss
  0x8000288: LoopFillZerobss
  0x800029a: LoopForever
  0x80002b0: Default_Handler
  0x80002b1: USBWakeUp_IRQHandler
  0x80002b3: _ZL22settings_displayUIMenuv
  0x80002c1: _ZL20settings_enterUIMenuv
  0x80002d1: _ZL28settings_displayAdvancedMenuv
  0x80002dd: _ZL26settings_enterAdvancedMenuv
  0x80002ed: _Z8gui_MenuPK8menuitem
  0x80005dd: _Z17enterSettingsMenuv
  0x80005f1: _Z41__static_initialization_and_destruction_0ii
  0x80006d9: _GLOBAL__sub_I_rootSettingsMenu
  0x80006e9: _ZN4OLEDC2EP8FRToSI2C
  0x8000751: _ZN4OLED10initializeEv
  0x80007a9: _ZN4OLED8drawCharEcc
  0x80008a1: _ZN4OLED11setRotationEb
  0x8000931: _ZN4OLED5printEPKc
  0x8000981: _ZN4OLED7setFontEh
  0x80009e9: _ZN4OLED11printNumberEth
  0x8000b05: _ZN4OLED10drawSymbolEh
  0x8000b37: _ZN4OLED8drawAreaEsahhPKh
  0x8000c1b: _ZN4OLED8fillAreaEsahhh
  0x8000ce3: _ZN4OLED14drawFilledRectEhhhhb
  0x8000edd: _ZN4OLED14drawHeatSymbolEh
  0x8000f31: _Z12saveSettingsv
  0x8000fb1: _Z15restoreSettingsv
  0x8001009: _Z18lookupVoltageLevelh
  0x8001035: _Z13resetSettingsv
  0x80010f5: NVIC_SystemReset
  0x800111d: _ZN8FRToSI2C12CpltCallbackEv
  0x800116d: _ZN8FRToSI2C8Mem_ReadEtttPht
  0x800122f: _ZN8FRToSI2C9Mem_WriteEtttPht
  0x80012f1: _ZN8FRToSI2C8TransmitEtPht
  0x8001389: _Z12startGUITaskPKv
  0x80017d9: _Z12startPIDTaskPKv
  0x8001941: _Z12startMOVTaskPKv
  0x8001bd1: _Z23showBootLogoIfavailablev
  0x8001cc5: HAL_ADCEx_InjectedConvCpltCallback
  0x8001d0d: HAL_I2C_MasterRxCpltCallback
  0x8001d25: HAL_I2C_MasterTxCpltCallback
  0x8001d3d: HAL_I2C_MemTxCpltCallback
  0x8001d55: HAL_I2C_ErrorCallback
  0x8001d6d: HAL_I2C_AbortCpltCallback
  0x8001d85: HAL_I2C_MemRxCpltCallback
  0x8001d9d: vApplicationStackOverflowHook
  0x8001db1: _Z41__static_initialization_and_destruction_0ii
  0x8001e05: _GLOBAL__sub_I_i2cDev
  0x8001e15: _ZN4OLED13setCharCursorEss
  0x8001e55: _ZN4OLED12drawCheckboxEb
  0x8001e7d: _ZL31printShortDescriptionSingleLinem
  0x8001eb5: _ZL31printShortDescriptionDoubleLinem
  0x8001f09: _ZL21printShortDescriptionmt
  0x8001f51: _ZL16userConfirmationPKc
  0x8002045: _ZL23settings_setInputVRangev.lto_priv.56
  0x8002079: _ZL27settings_displayInputVRangev.lto_priv.57
  0x80020d1: _ZL21settings_setSleepTempv.lto_priv.34
  0x8002149: _ZL25settings_displaySleepTempv.lto_priv.35
  0x8002171: _ZL21settings_setSleepTimev.lto_priv.36
  0x80021b9: _ZL25settings_displaySleepTimev.lto_priv.37
  0x8002251: _ZL24settings_setShutdownTimev.lto_priv.38
  0x8002299: _ZL28settings_displayShutdownTimev.lto_priv.39
  0x80022f1: _ZL17settings_setTempFv.lto_priv.42
  0x800247d: _ZL21settings_displayTempFv.lto_priv.43
  0x80024ad: _ZL23settings_setSensitivityv.lto_priv.40
  0x8002511: _ZL27settings_displaySensitivityv.lto_priv.41
  0x800253d: _ZL36settings_setAdvancedSolderingScreensv.lto_priv.26
  0x8002565: _ZL40settings_displayAdvancedSolderingScreensv.lto_priv.27
  0x800258d: _ZL31settings_setAdvancedIDLEScreensv.lto_priv.24
  0x80025b5: _ZL35settings_displayAdvancedIDLEScreensv.lto_priv.25
  0x80025dd: _ZL23settings_setScrollSpeedv.lto_priv.48
  0x8002615: _ZL27settings_displayScrollSpeedv.lto_priv.49
  0x8002655: _ZL27settings_setDisplayRotationv.lto_priv.44
  0x80026dd: _ZL31settings_displayDisplayRotationv.lto_priv.45
  0x8002755: _ZL28settings_setBoostModeEnabledv.lto_priv.50
  0x800277d: _ZL32settings_displayBoostModeEnabledv.lto_priv.51
  0x80027a5: _ZL21settings_setBoostTempv.lto_priv.52
  0x8002825: _ZL25settings_displayBoostTempv.lto_priv.53
  0x800284d: _ZL30settings_setAutomaticStartModev.lto_priv.54
  0x8002891: _ZL34settings_displayAutomaticStartModev.lto_priv.55
  0x80028c5: _ZL31settings_setCoolingBlinkEnabledv.lto_priv.46
  0x80028ed: _ZL35settings_displayCoolingBlinkEnabledv.lto_priv.47
  0x8002915: _ZL25settings_setResetSettingsv.lto_priv.28
  0x800296d: _ZL29settings_displayResetSettingsv.lto_priv.29
  0x800297d: _ZL21settings_setCalibratev.lto_priv.30
  0x8002a45: _ZL25settings_displayCalibratev.lto_priv.31
  0x8002a55: _ZL24settings_setCalibrateVINv.lto_priv.32
  0x8002bc1: _ZL11displayMenuj.lto_priv.64
  0x8002c19: _ZL28settings_displayCalibrateVINv.lto_priv.33
  0x8002c27: _ZL29settings_displaySolderingMenuv.lto_priv.59
  0x8002c35: _ZL27settings_enterSolderingMenuv.lto_priv.58
  0x8002c45: _ZL25settings_displayPowerMenuv.lto_priv.61
  0x8002c51: _ZL23settings_enterPowerMenuv.lto_priv.60
  0x8002c61: HAL_InitTick
  0x8002d0d: _ZN8LIS2DH129initalizeEv
  0x8002d4d: _ZN8LIS2DH1215getAxisReadingsEPsS0_S0_
  0x8002daf: _ZN8LIS2DH1217I2C_RegisterWriteEhh
  0x8002ddd: _ZN8LIS2DH1216I2C_RegisterReadEh
  0x8002e0d: _ZN9MMA8652FC17I2C_RegisterWriteEhh
  0x8002e3b: _ZN9MMA8652FC16I2C_RegisterReadEh
  0x8002e6d: _ZN9MMA8652FC9initalizeEv
  0x8002ef1: _ZN9MMA8652FC14getOrientationEv
  0x8002f29: _ZN9MMA8652FC15getAxisReadingsEPsS0_S0_
  0x8002f8d: NVIC_SystemReset.lto_priv.68
  0x8002fb5: _ZN8FRToSI2CC1EP17I2C_HandleTypeDef
  0x8002fd7: _ZN8FRToSI2C9FRToSInitEv
  0x8003003: _ZN9MMA8652FCC2EP8FRToSI2C.lto_priv.73
  0x800301f: _ZN4OLED7refreshEv
  0x800303f: _ZN4OLED12displayOnOffEb
  0x8003069: _ZNK4OLED11getRotationEv
  0x800307f: _ZN4OLED9setCursorEss
  0x80030a3: _ZN4OLED11clearScreenEv
  0x80030bf: _ZN4OLED11drawBatteryEh
  0x80030e7: _ZSt3absl
  0x8003101: _ZN8LIS2DH12C2EP8FRToSI2C.lto_priv.72
  0x800311d: _ZN8LIS2DH1214getOrientationEv
  0x8003141: main
  0x80032c5: _Z12printVoltagev
  0x8003339: _Z8GUIDelayv
  0x8003345: _Z15gui_drawTipTempb
  0x80033d5: _Z14getButtonStatev
  0x80034e1: _ZL18waitForButtonPressv
  0x800352d: _Z27waitForButtonPressOrTimeoutm
  0x8003571: _ZL19checkVoltageForExitv
  0x800364d: _ZL19gui_drawBatteryIconv.lto_priv.69
  0x80036cd: _ZL23gui_solderingTempAdjustv.lto_priv.71
  0x800396d: _ZL3mintt
  0x8003995: _ZL25gui_SolderingSleepingModev
  0x8003be9: _ZL17display_countdowni
  0x8003c95: _ZL17gui_solderingModev.lto_priv.70
  0x8004041: _Z11showVersionv
  0x8004201: xQueueGiveFromISR
  0x8004315: xQueueGenericReceive
  0x800453d: prvCopyDataToQueue.lto_priv.92
  0x8004611: prvCopyDataFromQueue
  0x800465b: prvUnlockQueue.lto_priv.93
  0x80046f5: prvIsQueueEmpty
  0x8004721: prvIsQueueFull.lto_priv.94
  0x8004751: Setup_HAL
  0x8004791: getADC
  0x80047dd: SystemClock_Config
  0x8004871: MX_ADC1_Init
  0x800495d: MX_I2C1_Init
  0x80049ad: MX_IWDG_Init
  0x80049d5: MX_TIM3_Init
  0x8004aa5: MX_TIM2_Init
  0x8004b6d: MX_DMA_Init
  0x8004bc5: MX_GPIO_Init
  0x8004d1d: SystemInit
  0x8004d85: controlSanitizer
  0x8004d99: NVIC_SystemReset
  0x8004dc1: NMI_Handler
  0x8004dcb: HardFault_Handler
  0x8004dd5: MemManage_Handler
  0x8004ddf: BusFault_Handler
  0x8004de9: UsageFault_Handler
  0x8004df3: DebugMon_Handler
  0x8004dfd: SysTick_Handler
  0x8004e09: DMA1_Channel1_IRQHandler
  0x8004e19: ADC1_2_IRQHandler
  0x8004e29: TIM1_UP_IRQHandler
  0x8004e39: TIM3_IRQHandler
  0x8004e49: TIM2_IRQHandler
  0x8004e59: I2C1_EV_IRQHandler
  0x8004e69: I2C1_ER_IRQHandler
  0x8004e79: DMA1_Channel6_IRQHandler
  0x8004e89: DMA1_Channel7_IRQHandler
  0x8004e99: setCalibrationOffset
  0x8004eb5: getHandleTemperature
  0x8004ef9: tipMeasurementToC
  0x8004f4d: ctoTipMeasurement
  0x8004f95: tipMeasurementToF
  0x8004ffd: ftoTipMeasurement
  0x8005061: getTipInstantTemperature
  0x8005071: getTipRawTemp
  0x8005165: getInputVoltageX10
  0x8005225: getTipPWM
  0x800523d: setTipPWM
  0x8005271: HAL_TIM_PeriodElapsedCallback
  0x80052ed: HAL_TIM_PWM_PulseFinishedCallback
  0x8005321: HAL_MspInit
  0x80053c1: HAL_ADC_MspInit
  0x8005489: HAL_I2C_MspInit
  0x800558d: HAL_TIM_Base_MspInit
  0x80055ed: pvPortMalloc
  0x800577d: vPortFree
  0x800582d: xPortGetFreeHeapSize
  0x8005841: prvHeapInit
  0x8005901: prvInsertBlockIntoFreeList
  0x80059b1: pxPortInitialiseStack
  0x8005a09: prvTaskExitError
  0x8005a51: SVC_Handler
  0x8005a70: pxCurrentTCBConst2
  0x8005a75: prvPortStartFirstTask
  0x8005a95: xPortStartScheduler
  0x8005b51: vPortEnterCritical
  0x8005ba9: vPortExitCritical
  0x8005c01: PendSV_Handler
  0x8005c40: pxCurrentTCBConst
  0x8005c45: xPortSysTickHandler
  0x8005c85: vPortSetupTimerInterrupt
  0x8005cb9: vPortValidateInterruptPriority
  0x8005d31: vListInitialise
  0x8005d6d: vListInitialiseItem
  0x8005d83: vListInsertEnd
  0x8005dc7: vListInsert
  0x8005e35: uxListRemove
  0x8005e89: xQueueGenericReset
  0x8005f59: xQueueGenericCreate
  0x8005fcb: prvInitialiseNewQueue
  0x8006009: xQueueGenericSend
  0x8006201: prvInitialiseNewTask.lto_priv.114
  0x8006309: prvAddNewTaskToReadyList.lto_priv.113
  0x80063dd: vTaskStartScheduler
  0x8006469: vTaskSuspendAll
  0x8006481: xTaskResumeAll
  0x80065b9: xTaskGetTickCount
  0x80065d5: xTaskIncrementTick
  0x8006751: vTaskSwitchContext
  0x800684d: vTaskPlaceOnEventList
  0x8006891: xTaskRemoveFromEventList
  0x8006955: vTaskSetTimeOutState
  0x8006999: xTaskCheckForTimeOut
  0x8006a55: vTaskMissedYield
  0x8006a69: prvIdleTask
  0x8006a99: prvInitialiseTaskLists
  0x8006b19: prvCheckTasksWaitingTermination
  0x8006b23: prvTaskCheckFreeStackSpace
  0x8006b59: uxTaskGetStackHighWaterMark
  0x8006b91: prvResetNextTaskUnblockTime
  0x8006bd9: xTaskGetCurrentTaskHandle
  0x8006bf5: xTaskGetSchedulerState
  0x8006c31: vTaskPriorityInherit
  0x8006d1d: xTaskPriorityDisinherit
  0x8006e25: pvTaskIncrementMutexHeldCount
  0x8006e4d: ulTaskNotifyTake
  0x8006edd: vTaskNotifyGiveFromISR
  0x8006ff9: prvAddCurrentTaskToDelayedList
  0x80070c1: osKernelStart
  0x80070cf: osThreadCreate
  0x800711d: osDelay
  0x8007131: osSystickHandler
  0x8007145: xTaskCreate
  0x80071c7: makeFreeRtosPriority.lto_priv.117
  0x80071f5: HAL_Init
  0x8007221: HAL_IncTick
  0x8007239: HAL_GetTick
  0x800724d: HAL_Delay
  0x800725d: HAL_TIM_OC_DelayElapsedCallback
  0x800726d: HAL_TIM_IC_CaptureCallback
  0x800727d: HAL_TIM_TriggerCallback
  0x800728d: TIM_Base_SetConfig
  0x8007359: TIM_OC1_SetConfig.lto_priv.140
  0x800742d: TIM_OC2_SetConfig
  0x800750d: TIM_OC3_SetConfig.lto_priv.142
  0x80075e9: TIM_OC4_SetConfig.lto_priv.141
  0x8007691: TIM_TI1_ConfigInputStage.lto_priv.136
  0x80076f3: TIM_TI2_ConfigInputStage.lto_priv.137
  0x8007757: TIM_ITRx_SetConfig.lto_priv.135
  0x8007793: TIM_ETR_SetConfig.lto_priv.138
  0x80077d3: TIM_CCxChannelCmd
  0x8007815: HAL_TIM_IRQHandler
  0x8007a25: HAL_TIM_OC_ConfigChannel
  0x8007ae1: HAL_TIM_PWM_ConfigChannel
  0x8007c69: HAL_TIM_ConfigClockSource
  0x8007e1d: HAL_TIM_PWM_Init
  0x8007e73: HAL_TIM_PWM_MspInit
  0x8007e85: HAL_TIM_PWM_Start
  0x8007ed5: HAL_TIM_PWM_Stop
  0x8007f6d: HAL_TIM_PWM_Start_IT
  0x8008045: HAL_TIM_Base_Init
  0x800809b: HAL_TIM_Base_Start_IT
  0x80080cf: HAL_TIM_OC_Init
  0x8008125: HAL_TIM_OC_MspInit
  0x8008135: HAL_GPIO_ReadPin
  0x8008163: HAL_GPIO_WritePin
  0x8008191: HAL_GPIO_Init
  0x8008449: HAL_ADC_Start_DMA
  0x8008609: HAL_ADC_IRQHandler
  0x800878d: HAL_ADC_ConvCpltCallback
  0x800879d: HAL_ADC_ConvHalfCpltCallback
  0x80087ad: HAL_ADC_LevelOutOfWindowCallback
  0x80087bd: HAL_ADC_ErrorCallback
  0x80087cd: HAL_ADC_ConfigChannel
  0x80089bd: ADC_Enable
  0x8008a61: ADC_ConversionStop_Disable
  0x8008ad5: ADC_DMAConvCplt
  0x8008b4f: ADC_DMAHalfConvCplt
  0x8008b69: ADC_DMAError
  0x8008b9b: HAL_TIMEx_MasterConfigSynchronization
  0x8008c23: HAL_TIMEx_CommutationCallback
  0x8008c33: HAL_TIMEx_BreakCallback
  0x8008c45: HAL_RCC_OscConfig
  0x8009109: HAL_RCC_ClockConfig
  0x80092f1: HAL_RCC_GetSysClockFreq
  0x80093b1: HAL_RCC_GetHCLKFreq
  0x80093c5: HAL_RCC_GetPCLK1Freq
  0x80093ed: HAL_RCC_GetPCLK2Freq
  0x8009415: HAL_RCC_GetClockConfig
  0x8009475: RCC_Delay
  0x80094ad: HAL_ADC_Init
  0x800965d: HAL_FLASH_Unlock
  0x8009695: HAL_FLASH_Lock
  0x80096b5: FLASH_WaitForLastOperation
  0x8009741: FLASH_SetErrorCode.lto_priv.194
  0x80097dd: HAL_ADCEx_Calibration_Start
  0x8009915: HAL_ADCEx_InjectedStart
  0x8009a25: HAL_ADCEx_InjectedConfigChannel
  0x8009d4d: HAL_DMA_Init
  0x8009e19: HAL_DMA_Start_IT
  0x8009ed9: HAL_DMA_Abort_IT
  0x8009fd1: HAL_DMA_IRQHandler
  0x800a1f9: DMA_SetConfig
  0x800a251: HAL_IWDG_Init
  0x800a2c3: HAL_IWDG_Refresh
  0x800a2e1: HAL_RCCEx_PeriphCLKConfig
  0x800a44d: HAL_RCCEx_GetPeriphCLKFreq
  0x800a5cd: NVIC_SetPriorityGrouping
  0x800a611: NVIC_GetPriorityGrouping
  0x800a62d: NVIC_EnableIRQ
  0x800a65d: NVIC_SetPriority
  0x800a6ad: NVIC_EncodePriority
  0x800a70d: SysTick_Config
  0x800a751: HAL_NVIC_SetPriorityGrouping
  0x800a765: HAL_NVIC_SetPriority
  0x800a79b: HAL_NVIC_EnableIRQ
  0x800a7b5: HAL_SYSTICK_Config
  0x800a7cd: HAL_SYSTICK_CLKSourceConfig
  0x800a801: I2C_WaitOnTXEFlagUntilTimeout.lto_priv.214
  0x800a87b: I2C_WaitOnBTFFlagUntilTimeout.lto_priv.225
  0x800a8f5: I2C_WaitOnRXNEFlagUntilTimeout.lto_priv.224
  0x800a989: I2C_IsAcknowledgeFailed
  0x800a9d9: HAL_FLASHEx_Erase
  0x800aab5: FLASH_MassErase
  0x800aaed: FLASH_PageErase
  0x800ab29: I2C_Master_ADD10.lto_priv.220
  0x800ab49: I2C_Master_ADDR.lto_priv.219
  0x800ae29: I2C_Slave_AF.lto_priv.218
  0x800af0d: I2C_ITError.lto_priv.217
  0x800b119: I2C_MasterRequestWrite.lto_priv.228
  0x800b21d: I2C_RequestMemoryWrite.lto_priv.223
  0x800b341: I2C_RequestMemoryRead.lto_priv.222
  0x800b505: I2C_DMAXferCplt.lto_priv.215
  0x800b5ef: I2C_DMAError.lto_priv.216
  0x800b63b: I2C_DMAAbort
  0x800b6d5: I2C_WaitOnFlagUntilTimeout.lto_priv.221
  0x800b777: I2C_WaitOnMasterAddressFlagUntilTimeout
  0x800b855: HAL_I2C_EV_IRQHandler
  0x800b98d: HAL_I2C_ER_IRQHandler
  0x800baf1: HAL_I2C_SlaveTxCpltCallback
  0x800bb01: HAL_I2C_ListenCpltCallback
  0x800bb11: I2C_MasterTransmit_TXE
  0x800bd03: I2C_MasterTransmit_BTF
  0x800bded: I2C_MasterReceive_RXNE
  0x800bf2f: I2C_MasterReceive_BTF
  0x800c0b1: I2C_Master_SB
  0x800c185: HAL_I2C_Master_Transmit_DMA
  0x800c359: HAL_I2C_Mem_Write
  0x800c56d: HAL_I2C_Mem_Read
  0x800c9b9: HAL_I2C_Init
  0x800cb79: HAL_I2C_Master_Transmit
  0x800cd95: __libc_init_array
  0x800cde5: memset
  0x800ce81: strlen
  0x800cedd: register_fini
  0x800cef1: atexit
  0x800cefd: __libc_fini_array
  0x800cf31: __retarget_lock_acquire_recursive
  0x800cf35: __retarget_lock_release_recursive
  0x800cf39: __register_exitproc
  0x800cffc: __EH_FRAME_BEGIN__
  0x800cffd: _init
  0x800d009: _fini
  0x800d014: _etext
  0x800d078: AHBPrescTable
  0x800d088: APBPrescTable
  0x800d6f2: SettingRightChar
  0x800d6f3: SettingLeftChar
  0x800d6f4: SettingAutoChar
  0x800d6f5: SettingFastChar
  0x800d6f6: SettingSlowChar
  0x800d6f7: SettingsShortNameType
  0x800d6f8: _ZL13i2c_registers.lto_priv.62
  0x800d710: _ZL13i2c_registers.lto_priv.63
  0x800d72c: _ZL12idleScreenBG.lto_priv.15
  0x800d7d4: _ZL13idleScreenBGF.lto_priv.12
  0x800d87c: _ZL17SettingsMenuIcons.lto_priv.10
  0x800d8fc: _ZL7FONT_12.lto_priv.8
  0x800f6fc: _ZL14ExtraFontChars.lto_priv.5
  0x800f8ac: _ZL8FONT_6x8.lto_priv.2
  0x801002c: _ZL16REFRESH_COMMANDS
  0x801009c: _global_impure_ptr
  0x80100a0: __exidx_start
  0x80100a4: __frame_dummy_init_array_entry
  0x80100b0: __init_array_end
  0x80100b4: _sidata
  0x20000000: _sdata
  0x20000004: SystemCoreClock
  0x20000008: preFillneeded.7855.lto_priv.79
  0x2000000c: SettingsDescriptions
  0x20000050: SettingsCalibrationWarning
  0x20000054: SettingsResetWarning
  0x20000058: UVLOWarningString
  0x2000005c: UndervoltageString
  0x20000060: InputVoltageString
  0x20000064: BadTipString
  0x20000068: SleepingSimpleString
  0x2000006c: SleepingAdvancedString
  0x20000070: SleepingTipAdvancedString
  0x20000074: IdleTipString
  0x20000078: IdleSetString
  0x2000007c: TipDisconnectedString
  0x20000080: SolderingAdvancedPowerPrompt
  0x20000084: OffString
  0x20000088: SettingsShortNames
  0x20000110: SettingsMenuEntries
  0x20000120: SettingsMenuEntriesDescriptions
  0x20000130: _ZL7HEADERS.lto_priv.75
  0x20000158: rootSettingsMenu
  0x200001a0: _ZL13solderingMenu.lto_priv.66
  0x200001d0: _ZL6UIMenu
  0x2000020c: _ZL9PowerMenu.lto_priv.65
  0x20000248: _ZL12advancedMenu
  0x20000290: OLED_Setup_Array
  0x200002c8: impure_data
  0x200006f0: __atexit_recursive_mutex
  0x200006f4: _edata
  0x200006f8: __bss_start__
  0x200006fc: object.8672
  0x20000718: pFlash
  0x20000738: uwTick
  0x2000073c: pxCurrentTCB
  0x20000740: pxReadyTasksLists.lto_priv.102
  0x20000790: xDelayedTaskList1.lto_priv.106
  0x200007a4: xDelayedTaskList2.lto_priv.107
  0x200007b8: pxDelayedTaskList.lto_priv.99
  0x200007bc: pxOverflowDelayedTaskList.lto_priv.98
  0x200007c0: xPendingReadyList.lto_priv.103
  0x200007d4: xSuspendedTaskList.lto_priv.97
  0x200007e8: uxCurrentNumberOfTasks.lto_priv.110
  0x200007ec: xTickCount.lto_priv.95
  0x200007f0: uxTopReadyPriority.lto_priv.96
  0x200007f4: xSchedulerRunning.lto_priv.105
  0x200007f8: uxPendedTicks.lto_priv.109
  0x200007fc: xYieldPending.lto_priv.104
  0x20000800: xNumOfOverflows.lto_priv.108
  0x20000804: uxTaskNumber.lto_priv.112
  0x20000808: xNextTaskUnblockTime.lto_priv.100
  0x2000080c: xIdleTaskHandle.lto_priv.111
  0x20000810: uxSchedulerSuspended.lto_priv.101
  0x20000814: ucHeap.lto_priv.88
  0x20003014: xStart.lto_priv.86
  0x2000301c: pxEnd.lto_priv.87
  0x20003020: xFreeBytesRemaining.lto_priv.90
  0x20003024: xMinimumEverFreeBytesRemaining.lto_priv.89
  0x20003028: xBlockAllocatedBit.lto_priv.91
  0x2000302c: ucMaxSysCallPriority.lto_priv.83
  0x20003030: ulMaxPRIGROUPValue.lto_priv.84
  0x20003034: hadc1
  0x20003064: hdma_adc1
  0x200030a8: hi2c1
  0x200030fc: hdma_i2c1_rx
  0x20003140: hdma_i2c1_tx
  0x20003184: hiwdg
  0x20003190: htim2
  0x200031d0: htim3
  0x20003210: ADCReadings
  0x20003290: PWMSafetyTimer
  0x20003292: CalibrationTempOffset
  0x20003298: filterFP.7849.lto_priv.82
  0x200032a0: samples.7856.lto_priv.80
  0x200033a0: index.7857.lto_priv.81
  0x200033a4: htim1
  0x200033e4: i2cDev
  0x200033ec: lcd
  0x200034e0: accel
  0x200034e4: accel2
  0x200034e8: PCBVersion
  0x200034ea: currentlyActiveTemperatureTarget
  0x200034ec: lastMovementTime
  0x200034f0: lastButtonTime
  0x200034f4: GUITaskHandle
  0x200034f8: PIDTaskHandle
  0x200034fc: MOVTaskHandle
  0x20003500: _ZL19pidTaskNotification.lto_priv.67
  0x20003504: _ZZ14getButtonStatevE13previousState.lto_priv.76
  0x20003508: _ZZ14getButtonStatevE19previousStateChange.lto_priv.77
  0x2000350c: systemSettings
  0x20003528: __lock___atexit_recursive_mutex
  0x2000352c: __lock___arc4random_mutex
  0x20003530: __lock___env_recursive_mutex
  0x20003534: __lock___sinit_recursive_mutex
  0x20003538: __lock___malloc_recursive_mutex
  0x2000353c: __lock___at_quick_exit_mutex
  0x20003540: __lock___dd_hash_mutex
  0x20003544: __lock___tz_mutex
  0x20003548: __lock___sfp_recursive_mutex
  0x2000354c: __bss_end__
  0x20003550: end
  0x20005000: _estack
  0xf1e0f85f: BootRAM
