interrupt:
  mode: round-robin
  trigger:
    on-infinite-sleep: true
    interval: 1000

memory_maps:
  - name: mmio
    address: 0x40000000
    size: 0x20000000
    type: mmio
  - name: ram
    address: 0x20000000
    size: 0x100000
    type: ram
  - name: text
    address: 0x0
    size: 0x19c00
    file:
      path: Pretender.max32_rf_door_lock.bin
    type: rom

symbols:
  - Pretender.max32_rf_door_lock.elf
