board:
  init_nsvtor: 0x8000000

interrupt:
  mode: round-robin
  trigger:
    on-infinite-sleep: true
    interval: 1000

memory_maps:
  - name: mmio
    address: 0x40000000
    size: 0x20000000
    type: mmio
  - name: ram
    address: 0x1fffa000
    size: 0x106000
    type: ram
  - name: text
    address: 0x8000000
    size: 0x20c00
    file:
      path: gnrc_networking.bin
    type: rom

symbols:
  - gnrc_networking.elf
