interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x202000
    file: contiki6lowpanX.bin
    ivt_offset: 0x0
    permissions: r-x
    size: 0x8e000
symbols:
  0x0: smartrf-sensors.c
  0x202000: vectors
  0x20228d: reset_handler
  0x2022cd: platform_init_stage_two
  0x202319: platform_init_stage_three
  0x2023a5: process_thread_sensors_process
  0x202481: value
  0x2024a5: configure
  0x2024f9: soc_get_rev
  0x202511: soc_print_info
  0x202521: update_ticks
  0x20256d: clock_init
  0x2025b9: clock_time
  0x2025cd: clock_seconds
  0x2025e1: clock_delay_usec
  0x2025fd: clock_adjust
  0x20261d: rtimer_arch_next_trigger
  0x202629: rtimer_arch_now
  0x202655: rtimer_arch_schedule
  0x2026ad: rtimer_isr
  0x2026d9: permit_pm1
  0x2026fd: uart_isr
  0x202761: uart_init
  0x202909: uart_set_input
  0x202919: uart_write_byte
  0x202935: watchdog_init
  0x202941: watchdog_start
  0x20294d: watchdog_periodic
  0x20295d: nvic_init
  0x20296d: sys_ctrl_init
  0x2029e1: gpio_port_isr
  0x202a2d: ioc_init
  0x202a49: ioc_set_over
  0x202a5d: ioc_set_sel
  0x202a71: adc_init
  0x202a81: adc_get
  0x202af9: permit_pm1
  0x202b09: crypto_isr
  0x202b31: crypto_enable
  0x202b51: crypto_init
  0x202b8d: crypto_disable
  0x202bad: gpio_hal_arch_no_port_pin_cfg_set
  0x202c8d: 'on'
  0x202cb5: 'off'
  0x202cf5: set_channel
  0x202d2d: channel_clear
  0x202d69: receiving_packet
  0x202d81: pending_packet
  0x202d91: get_value
  0x202f0d: set_poll_mode
  0x202fa9: set_object
  0x202fd9: read
  0x2030b9: prepare
  0x203121: init
  0x203209: process_thread_cc2538_rf_process
  0x203299: get_object
  0x2033dd: transmit
  0x203481: set_value
  0x20360d: cc2538_rf_rx_tx_isr
  0x203631: cc2538_rf_err_isr
  0x203659: udma_init
  0x20368d: udma_set_channel_src
  0x20369d: udma_set_channel_dst
  0x2036b1: udma_set_channel_control_word
  0x2036c5: udma_channel_enable
  0x2036dd: udma_channel_mask_set
  0x2036f5: udma_channel_sw_request
  0x20370d: udma_channel_get_mode
  0x203729: udma_isr
  0x203739: udma_err_isr
  0x203745: select_32_mhz_xosc
  0x203775: lpm_exit
  0x2037a9: lpm_enter
  0x203861: lpm_register_peripheral
  0x203885: lpm_init
  0x2038a9: pka_isr
  0x2038d1: ieee_addr_cpy_to
  0x203931: main
  0x203b1d: stimer_expired
  0x203b3d: log_6addr
  0x203b5d: log_lladdr
  0x203b99: update_time
  0x203bdd: etimer_request_poll
  0x203be9: process_thread_etimer_process
  0x203c95: add_timer
  0x203cd5: etimer_pending
  0x203ce5: etimer_stop
  0x203d19: node_id_init
  0x203d31: process_thread_ctimer_process
  0x203db1: ctimer_init
  0x203dd9: ctimer_set_with_process
  0x203e1d: ctimer_set
  0x203e31: ctimer_reset
  0x203e69: ctimer_stop
  0x203e95: ctimer_expired
  0x203ec9: rtimer_run_next
  0x203ef1: call_process.part.0
  0x203f29: exit_process
  0x203fa9: do_poll
  0x203fdd: process_alloc_event
  0x203fed: process_init
  0x20401d: process_run
  0x2040a1: process_nevents
  0x2040b5: process_post
  0x2040f1: process_post_synch
  0x204105: process_start
  0x204135: process_poll
  0x20414d: stack_check_init
  0x204175: stack_check_get_usage
  0x2041b5: process_thread_stack_check_process
  0x204261: random_rand
  0x204281: random_init
  0x2042fd: duration_exceeded_callback
  0x204331: process_thread_button_hal_process
  0x2043a1: press_release_handler
  0x2043b9: debounce_handler
  0x20441d: button_hal_init
  0x204511: process_thread_serial_line_process
  0x2045b1: serial_line_input_byte
  0x2045f5: serial_line_init
  0x204619: leds_on
  0x204679: leds_off
  0x2046c1: leds_init
  0x204705: gpio_hal_register_handler
  0x204711: gpio_hal_event_handler
  0x204735: gpio_hal_init
  0x204741: queuebuf_init
  0x20475d: queuebuf_numfree
  0x204769: queuebuf_new_from_packetbuf
  0x2047ad: queuebuf_free
  0x2047d9: queuebuf_to_packetbuf
  0x204809: index_from_key
  0x204829: index_from_lladdr
  0x204869: nbr_get_bit.constprop.1
  0x204895: nbr_table_is_registered
  0x2048b5: nbr_table_register
  0x2048e5: nbr_table_next
  0x20492d: nbr_table_head
  0x204965: nbr_table_add_lladdr
  0x204a8d: nbr_table_remove
  0x204ab9: nbr_table_get_lladdr
  0x204add: packetbuf_set_datalen
  0x204ae9: packetbuf_datalen
  0x204af5: packetbuf_hdrlen
  0x204b0d: packetbuf_dataptr
  0x204b1d: packetbuf_copyto
  0x204b61: packetbuf_attr_clear
  0x204b95: packetbuf_clear
  0x204bb5: packetbuf_copyfrom
  0x204be1: packetbuf_attr_copyto
  0x204c05: packetbuf_attr_copyfrom
  0x204c29: packetbuf_set_attr
  0x204c39: packetbuf_attr
  0x204c45: packetbuf_set_addr
  0x204c5d: packetbuf_addr
  0x204c6d: netstack_process_ip_callback
  0x204cad: netstack_init
  0x204cd1: periodic
  0x204cfd: link_stats_packet_sent
  0x204d71: link_stats_input_callback
  0x204dc1: link_stats_init
  0x204de9: fill_space
  0x204e1d: format_str_v
  0x2054e5: printf
  0x205505: vsnprintf
  0x20552d: packet_input
  0x205539: 'on'
  0x205545: 'off'
  0x205551: max_payload
  0x205569: send_packet
  0x205585: uipbuf_add_ext_hdr
  0x2055b5: uipbuf_set_len
  0x2055c9: uipbuf_get_attr
  0x2055dd: uipbuf_clear_attr
  0x2055f1: uipbuf_clear
  0x205611: uipbuf_init
  0x205631: echo_reply_input
  0x20569d: echo_request_input
  0x205735: uip_icmp6_input
  0x20576d: uip_icmp6_register_input_handler
  0x205779: uip_icmp6_error_output
  0x2058bd: uip_icmp6_init
  0x2058d9: uip_ds6_prefix_add
  0x20593d: uip_ds6_is_addr_onlink
  0x20597d: uip_ds6_addr_lookup
  0x2059a9: uip_ds6_get_link_local
  0x2059e9: uip_ds6_maddr_add
  0x205a35: uip_ds6_addr_add
  0x205ac9: uip_ds6_maddr_lookup
  0x205af5: uip_ds6_addr_rm
  0x205b39: uip_ds6_select_src
  0x205bcd: uip_ds6_send_ra_sollicited
  0x205c01: uip_ds6_send_ra_periodic
  0x205c51: uip_ds6_periodic
  0x205cbd: uip_ds6_compute_reachable_time
  0x205ce9: uip_ds6_init
  0x205e0d: uiplib_ipaddr_snprint
  0x205efd: call_route_callback
  0x205f4d: uip_ds6_route_init
  0x205f99: uip_ds6_route_nexthop
  0x205fb5: uip_ds6_route_head
  0x205fc1: uip_ds6_route_lookup
  0x206029: uip_ds6_route_rm
  0x2060bd: rm_routelist
  0x2060ed: uip_ds6_defrt_rm
  0x206131: uip_ds6_defrt_lookup
  0x206165: uip_ds6_defrt_choose
  0x206195: uip_ds6_defrt_periodic
  0x2061c5: uip_ds6_nbr_rm
  0x2061e9: uip_ds6_neighbors_init
  0x206205: uip_ds6_nbr_add
  0x20626d: uip_ds6_nbr_get_ll
  0x206279: uip_ds6_nbr_head
  0x206285: uip_ds6_nbr_next
  0x206291: uip_ds6_nbr_ll_lookup
  0x20629d: uip_ds6_neighbor_periodic
  0x20639d: tcpip_output
  0x2063c9: tcpip_input
  0x2063ed: tcpip_ipv6_output
  0x206525: packet_input
  0x206545: process_thread_tcpip_process
  0x206601: tcpip_uipcall
  0x20662d: upper_layer_chksum
  0x206681: ext_hdr_options_process
  0x2066fd: uip_update_ttl
  0x206721: uip_init
  0x206759: uip_remove_ext_hdr
  0x2067c1: uip_process
  0x206c2d: extract_lladdr_from_llao_aligned
  0x206c4d: create_llao
  0x206c75: rs_input
  0x206de1: na_input
  0x206f71: ns_input
  0x2071b9: uip_nd6_ns_output
  0x207305: uip_nd6_ra_output
  0x2074ed: uip_nd6_init
  0x207511: clear_fragments
  0x20754d: sicslowpan_init
  0x207565: set_packet_attrs
  0x2075bd: compress_addr_64
  0x20764d: addr_context_lookup_by_prefix
  0x207671: send_packet
  0x207695: fragment_copy_payload_and_send
  0x207701: output
  0x207e7d: packet_sent
  0x207ed9: store_fragment
  0x207f31: uncompress_addr
  0x207fc1: add_fragment
  0x2080e1: input
  0x208831: process_thread_hello_world_process
  0x208879: __aeabi_uldivmod
  0x2088a9: __udivmoddi4
  0x208b95: __aeabi_idiv0
  0x208b99: memcmp
  0x208bfd: memcpy
  0x208ce9: memmove
  0x208db1: memset
  0x208e4d: default_handler
  0x208e4f: nmi_handler
  0x208e55: fade
  0x208ead: platform_init_stage_one
  0x208ec1: platform_idle
  0x208ec5: status
  0x208ec9: soc_init
  0x208eeb: clock_isr
  0x208eef: rtimer_arch_init
  0x208ef1: uart0_isr
  0x208ef7: uart1_isr
  0x208efd: gpio_port_a_isr
  0x208f03: gpio_port_b_isr
  0x208f09: gpio_port_c_isr
  0x208f0f: gpio_port_d_isr
  0x208f15: send
  0x208f27: int_master_read_and_disable
  0x208f2f: int_master_status_set
  0x208f35: dbg_putchar
  0x208f45: dbg_send_bytes
  0x208f65: configure
  0x208f69: status
  0x208f6d: value
  0x208fa1: configure
  0x208fa5: status
  0x208fa9: value
  0x208fd3: autostart_start
  0x208fe7: stimer_set
  0x208ff5: stimer_remaining
  0x209005: stimer_elapsed
  0x209013: energest_init
  0x209015: etimer_set
  0x209027: etimer_reset
  0x209039: etimer_expired
  0x209043: rtimer_init
  0x209047: call_process
  0x209053: timer_set
  0x209061: timer_expired
  0x20907d: timer_reset
  0x209091: ringbuf_init
  0x20909f: ringbuf_put
  0x2090c5: ringbuf_get
  0x2090e5: list_init
  0x2090eb: list_head
  0x2090ef: list_tail
  0x2090ff: list_remove
  0x209125: list_add
  0x20913f: list_push
  0x20914f: list_length
  0x20915d: list_item_next
  0x209163: memb_init
  0x209183: memb_alloc
  0x2091ab: memb_free
  0x2091d5: memb_inmemb
  0x2091f1: memb_numfree
  0x20920d: button_hal_get_state
  0x209237: item_from_index
  0x20924b: index_from_item
  0x209261: nbr_set_bit
  0x209299: nbr_table_get_from_lladdr
  0x2092bf: linkaddr_copy
  0x2092c5: linkaddr_cmp
  0x2092d5: link_stats_is_fresh
  0x2092f9: guess_etx_from_rssi
  0x209339: write_str
  0x209349: buffer_str
  0x209371: snprintf
  0x20938b: putchar
  0x209397: init
  0x20939b: uipbuf_set_len_field
  0x2093a3: uipbuf_get_len_field
  0x2093af: uipbuf_get_next_header
  0x2093fd: uipbuf_get_last_header
  0x209429: uip_ds6_list_loop
  0x209479: uip_ds6_maddr_rm
  0x209481: uip_ds6_set_addr_iid
  0x209497: get_match_length
  0x2094d5: uip_ds6_route_next
  0x2094dd: rm_routelist_callback
  0x2094e1: uip_ds6_nbr_lookup
  0x20950d: uip_ds6_nbr_update_ll
  0x20956b: uip_ds6_nbr_ipaddr_from_lladdr
  0x20956f: uip_ds6_link_callback
  0x209571: uip_ds6_nbr_refresh_reachable_state
  0x209591: chksum
  0x2095c9: uip_icmp6chksum
  0x2095cf: uip_udpchksum
  0x2095d5: uip_htons
  0x2095db: uip_htonl
  0x2095ed: root_set_prefix
  0x2095ef: get_sr_node_ipaddr
  0x2095f3: leave_network
  0x2095f5: ext_header_update
  0x2095f9: ext_header_hbh_update
  0x2095fd: ext_header_srh_update
  0x209601: ext_header_srh_get_next_hop
  0x209605: link_callback
  0x209607: drop_route
  0x209609: is_in_leaf_mode
  0x20960d: ext_header_remove
  0x209611: get_root_ipaddr
  0x209615: node_has_joined
  0x209619: node_is_reachable
  0x20961d: global_repair
  0x20961f: local_repair
  0x209621: neighbor_state_changed
  0x209623: root_start
  0x209627: node_is_root
  0x20962b: init
  0x20962c: als_sensor
  0x20963c: uart_regs
  0x209694: cc2538_rf_driver
  0x2096cc: output_power
  0x20973c: cc2538_temp_sensor
  0x20974c: vdd3_sensor
  0x20975c: nullmac_driver
  0x209778: sicslowpan_driver
  0x209788: nullrouting_driver
  0x2097dc: autostart_processes
  0x2097e4: linkaddr_null
  0x2097ec: leds_arch_leds
  0x209aa0: buffer.5551
  0x209ab0: buffer.5560
  0x209b34: unc_llconf
  0x209b38: llprefix
  0x209b3a: unc_mxconf
  0x209b49: ttl_values
  0x209b4d: unc_ctxconf
  0x209b7f: _etext
  0x209b80: _ldata
  0x27ffd4: flash_cca_lock_page
  0x20000000: _enrdata
  0x20000040: _data
  0x20000050: sensors
  0x20000060: key_up
  0x200000b0: key_left
  0x20000100: key_select
  0x20000150: key_right
  0x200001a0: key_down
  0x200001f0: button_hal_buttons
  0x20000208: cc2538_rf_process
  0x20000218: curr_log_level_main
  0x2000021c: etimer_process
  0x2000022c: ctimer_process
  0x2000023c: stack_check_process
  0x2000024c: button_hal_process
  0x2000025c: serial_line_process
  0x2000026c: bufmem
  0x20000278: buframmem
  0x20000284: neighbor_addr_mem
  0x20000290: link_stats_struct
  0x200002a0: ctxt
  0x200002a8: echo_request_handler
  0x200002b4: echo_reply_handler
  0x200002c0: defaultroutermemb
  0x200002cc: nbr_routes_struct
  0x200002dc: nbr_routes
  0x200002e0: routememb
  0x200002ec: neighborroutememb
  0x200002f8: ds6_neighbors_struct
  0x20000308: tcpip_process
  0x20000318: rs_input_handler
  0x20000324: ns_input_handler
  0x20000330: na_input_handler
  0x2000033c: hello_world_process
  0x2000034c: send_on_cca
  0x2000034d: rf_channel
  0x2000034e: _edata
  0x20000350: _bss
  0x20000358: rt_ticks_epoch
  0x20000360: i.5534
  0x20000364: events.5535
  0x20000368: next_trigger
  0x2000036c: input_handler
  0x20000374: ioc_sel
  0x20000378: ioc_over
  0x2000037c: notification_process
  0x20000380: prev_MDMTEST1
  0x20000384: prev_FRMCTRL0
  0x20000388: periph_permit_pm1_funcs
  0x2000039c: notification_process
  0x200003a0: timerlist
  0x200003a4: next_expiration
  0x200003a8: ctimer_list_list
  0x200003ac: next_rtimer
  0x200003b0: process_current
  0x200003b4: process_list
  0x200003b8: events
  0x20000538: et.5876
  0x20000548: button_event_handler
  0x20000554: pmask
  0x20000558: rxbuf
  0x20000560: ptr.5519
  0x20000564: handlers_list
  0x20000568: bufmem_memb_mem
  0x20000588: nbr_table_keys_list
  0x2000058c: neighbor_addr_mem_memb_mem
  0x2000064c: all_tables
  0x2000066c: num_tables
  0x20000670: packetbuf_aligned
  0x200006f0: ip_processor_list_list
  0x200006f4: _link_stats_mem
  0x200007b4: echo_reply_callback_list_list
  0x200007b8: input_handler_list_list
  0x200007bc: locmaddr
  0x200007c0: locprefix
  0x200007c4: locaddr
  0x200007c8: defaultroutermemb_memb_mem
  0x20000808: num_routes
  0x2000080c: defaultrouterlist_list
  0x20000810: _nbr_routes_mem
  0x20000890: routelist_list
  0x20000894: routememb_memb_mem
  0x20000b14: neighborroutememb_memb_mem
  0x20000b94: notificationlist_list
  0x20000b98: _ds6_neighbors_mem
  0x20000e18: periodic
  0x20000e28: prefix
  0x20000e2c: nbr
  0x20000e30: nd6_opt_llao
  0x20000e34: addr
  0x20000e38: callback
  0x20000e3c: context
  0x20000e40: last_rssi
  0x20000e44: hc06_ptr
  0x20000e48: packetbuf_ptr
  0x20000e4c: packetbuf_payload_len
  0x20000e50: last_tx_status
  0x20000e54: mac_max_payload
  0x20000e58: frag_info
  0x20000fc8: timer.5488
  0x20000fd8: node_id
  0x20000fda: buframmem_memb_mem
  0x2000153a: buflen
  0x2000153c: bufptr
  0x2000153e: uipbuf_attrs
  0x2000154a: uipbuf_default_attrs
  0x20001556: tmp_ipaddr
  0x20001566: default_prefix
  0x20001576: loc_fipaddr
  0x20001586: rand_time
  0x20001588: uip_ext_len
  0x2000158a: lastport
  0x2000158c: my_tag
  0x2000158e: num_sensors
  0x2000158f: crc_corr
  0x20001590: was_on
  0x20001591: rssi
  0x20001592: poll_mode
  0x20001593: rf_flags
  0x20001594: max_pm
  0x20001595: initialized
  0x20001596: fevent
  0x20001597: nevents
  0x20001598: poll_requested
  0x20001599: lastevent
  0x2000159a: rxbuf_data
  0x2000161a: overflow.5512
  0x2000161b: buf.5518
  0x2000169b: buframmem_memb_used
  0x200016a3: bufmem_memb_used
  0x200016ab: locked_map
  0x200016bb: neighbor_addr_mem_memb_used
  0x200016cb: used_map
  0x200016db: hdrlen
  0x200016dc: racount
  0x200016dd: routememb_memb_used
  0x200016ed: neighborroutememb_memb_used
  0x200016fd: defaultroutermemb_memb_used
  0x200016ff: uip_ext_bitmap
  0x20001700: uip_last_proto
  0x20001701: nd6_opt_offset
  0x20001702: curr_page
  0x20001703: uncomp_hdr_len
  0x20001704: addr_contexts
  0x2000170e: frag_buf
  0x20001c5a: packetbuf_hdr_len
  0x20001c5c: periodic_timer
  0x20001c7c: uip_ds6_timer_ra
  0x20001c84: uip_ds6_if
  0x20001d7c: uip_ds6_netif_addr_list_offset
  0x20001d7d: uip_ds6_addr_size
  0x20001d80: uip_ds6_prefix_list
  0x20001de0: uip_ds6_timer_periodic
  0x20001df0: uip_len
  0x20001df4: uip_sappdata
  0x20001df8: uip_lladdr
  0x20001e00: uip_aligned_buf
  0x20002300: uip_flags
  0x20002304: uip_udp_conn
  0x20002308: uip_appdata
  0x2000230c: uip_conn
  0x20002310: uip_slen
  0x20002314: uip_udp_conns
  0x20002414: packetbuf_addrs
  0x20002424: packetbuf_attrs
  0x2000243e: linkaddr_node_addr
  0x20002446: sensors_event
  0x20002447: sensors_flags
  0x2000244b: button_hal_release_event
  0x2000244c: button_hal_periodic_event
  0x2000244d: button_hal_press_event
  0x2000244e: serial_line_event_message
  0x2000244f: tcpip_event
  0x20002450: _stack
  0x20002c50: _heap
  0x20008000: _eheap
