interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x202000
    file: contiki-hello-4-4X.bin
    ivt_offset: 0x0
    permissions: r-x
    size: 0x8e000
symbols:
  0x0: smartrf-sensors.c
  0x202000: vectors
  0x20228d: reset_handler
  0x2022cd: platform_init_stage_two
  0x202319: platform_init_stage_three
  0x2023a5: process_thread_sensors_process
  0x202481: value
  0x2024a5: configure
  0x2024f9: soc_get_rev
  0x202511: soc_print_info
  0x202521: update_ticks
  0x20256d: clock_init
  0x2025b9: clock_time
  0x2025cd: clock_seconds
  0x2025e1: clock_delay_usec
  0x2025fd: clock_adjust
  0x20261d: rtimer_arch_next_trigger
  0x202629: rtimer_arch_now
  0x202655: rtimer_arch_schedule
  0x2026ad: rtimer_isr
  0x2026d9: permit_pm1
  0x2026fd: uart_isr
  0x202761: uart_init
  0x202909: uart_set_input
  0x202919: uart_write_byte
  0x202935: watchdog_init
  0x202941: watchdog_start
  0x20294d: watchdog_periodic
  0x20295d: nvic_init
  0x20296d: sys_ctrl_init
  0x2029e1: gpio_port_isr
  0x202a2d: ioc_init
  0x202a49: ioc_set_over
  0x202a5d: ioc_set_sel
  0x202a71: adc_init
  0x202a81: adc_get
  0x202af9: permit_pm1
  0x202b09: crypto_isr
  0x202b31: crypto_enable
  0x202b51: crypto_init
  0x202b8d: crypto_disable
  0x202bad: gpio_hal_arch_no_port_pin_cfg_set
  0x202c8d: "on"
  0x202cb5: "off"
  0x202cf5: set_channel
  0x202d2d: channel_clear
  0x202d69: receiving_packet
  0x202d81: pending_packet
  0x202d91: get_value
  0x202f0d: set_poll_mode
  0x202fa9: set_object
  0x202fd9: read
  0x2030b9: prepare
  0x203121: init
  0x203209: process_thread_cc2538_rf_process
  0x203299: get_object
  0x2033dd: transmit
  0x203481: set_value
  0x20360d: cc2538_rf_rx_tx_isr
  0x203631: cc2538_rf_err_isr
  0x203659: udma_init
  0x20368d: udma_set_channel_src
  0x20369d: udma_set_channel_dst
  0x2036b1: udma_set_channel_control_word
  0x2036c5: udma_channel_enable
  0x2036dd: udma_channel_mask_set
  0x2036f5: udma_channel_sw_request
  0x20370d: udma_channel_get_mode
  0x203729: udma_isr
  0x203739: udma_err_isr
  0x203745: select_32_mhz_xosc
  0x203775: lpm_exit
  0x2037a9: lpm_enter
  0x203861: lpm_register_peripheral
  0x203885: lpm_init
  0x2038a9: pka_isr
  0x2038d1: ieee_addr_cpy_to
  0x203931: main
  0x203b1d: stimer_expired
  0x203b3d: log_6addr
  0x203b5d: log_lladdr
  0x203b99: update_time
  0x203bdd: etimer_request_poll
  0x203be9: process_thread_etimer_process
  0x203c95: add_timer
  0x203cd5: etimer_pending
  0x203ce5: etimer_stop
  0x203d19: node_id_init
  0x203d31: process_thread_ctimer_process
  0x203db1: ctimer_init
  0x203dd9: ctimer_set_with_process
  0x203e1d: ctimer_set
  0x203e31: ctimer_reset
  0x203e69: ctimer_stop
  0x203e95: ctimer_expired
  0x203ec9: rtimer_run_next
  0x203ef1: call_process.part.0
  0x203f29: exit_process
  0x203fa9: do_poll
  0x203fdd: process_alloc_event
  0x203fed: process_exit
  0x203ff9: process_init
  0x204029: process_run
  0x2040ad: process_nevents
  0x2040c1: process_post
  0x2040fd: process_post_synch
  0x204111: process_start
  0x204141: process_poll
  0x204159: stack_check_init
  0x204181: stack_check_get_usage
  0x2041c1: process_thread_stack_check_process
  0x20426d: random_rand
  0x20428d: random_init
  0x204309: duration_exceeded_callback
  0x20433d: process_thread_button_hal_process
  0x2043ad: press_release_handler
  0x2043c5: debounce_handler
  0x204429: button_hal_init
  0x20451d: process_thread_serial_line_process
  0x2045bd: serial_line_input_byte
  0x204601: serial_line_init
  0x204625: leds_on
  0x204685: leds_off
  0x2046cd: leds_init
  0x204711: gpio_hal_register_handler
  0x20471d: gpio_hal_event_handler
  0x204741: gpio_hal_init
  0x20474d: queuebuf_init
  0x204769: queuebuf_numfree
  0x204775: queuebuf_new_from_packetbuf
  0x2047b9: queuebuf_free
  0x2047e5: queuebuf_to_packetbuf
  0x204815: index_from_key
  0x204835: index_from_lladdr
  0x204875: nbr_get_bit.constprop.0
  0x2048a1: nbr_table_is_registered
  0x2048c1: nbr_table_register
  0x2048f1: nbr_table_next
  0x204939: nbr_table_head
  0x204971: nbr_table_add_lladdr
  0x204add: nbr_table_remove
  0x204b09: nbr_table_lock
  0x204b19: nbr_table_unlock
  0x204b29: nbr_table_get_lladdr
  0x204b4d: packetbuf_set_datalen
  0x204b59: packetbuf_hdrptr
  0x204b61: packetbuf_datalen
  0x204b6d: packetbuf_hdrlen
  0x204b85: packetbuf_dataptr
  0x204b95: packetbuf_copyto
  0x204bd9: packetbuf_totlen
  0x204bed: packetbuf_hdralloc
  0x204c2d: packetbuf_attr_clear
  0x204c61: packetbuf_clear
  0x204c81: packetbuf_copyfrom
  0x204cad: packetbuf_attr_copyto
  0x204cd1: packetbuf_attr_copyfrom
  0x204cf5: packetbuf_set_attr
  0x204d05: packetbuf_attr
  0x204d11: packetbuf_set_addr
  0x204d29: packetbuf_addr
  0x204d39: netstack_process_ip_callback
  0x204d79: netstack_init
  0x204d9d: periodic
  0x204dc9: link_stats_from_lladdr
  0x204dd5: link_stats_packet_sent
  0x204e49: link_stats_input_callback
  0x204e99: link_stats_reset
  0x204ebd: link_stats_init
  0x204ee5: fill_space
  0x204f19: format_str_v
  0x2055e1: printf
  0x205601: vsnprintf
  0x205629: process_thread_ble_l2cap_tx_process
  0x20578d: get_channel_for_addr
  0x2057d5: "off"
  0x2057e5: "on"
  0x2057f9: send
  0x2058c5: init
  0x205a25: input_l2cap_conn_req
  0x205b61: input
  0x205d5d: uipbuf_add_ext_hdr
  0x205d8d: uipbuf_set_len
  0x205da1: uipbuf_get_attr
  0x205db5: uipbuf_clear_attr
  0x205dc9: uipbuf_clear
  0x205de9: uipbuf_init
  0x205e09: echo_reply_input
  0x205e75: echo_request_input
  0x205f0d: uip_icmp6_input
  0x205f45: uip_icmp6_register_input_handler
  0x205f51: uip_icmp6_error_output
  0x206095: uip_icmp6_send
  0x206111: uip_icmp6_init
  0x20612d: node_matches_address.part.0
  0x206155: uip_sr_get_node
  0x206189: uip_sr_is_addr_reachable
  0x2061cd: uip_sr_update_node
  0x206271: uip_sr_init
  0x206295: uip_sr_periodic
  0x2062fd: uip_sr_free_all
  0x20633d: uip_ds6_default_prefix
  0x206345: uip_ds6_prefix_add
  0x2063a9: uip_ds6_is_addr_onlink
  0x2063e9: uip_ds6_addr_lookup
  0x206415: uip_ds6_get_link_local
  0x206455: uip_ds6_maddr_add
  0x2064a1: uip_ds6_addr_add
  0x206535: uip_ds6_maddr_lookup
  0x206561: uip_ds6_addr_rm
  0x2065a5: uip_ds6_periodic
  0x2065f1: uip_ds6_select_src
  0x206685: uip_ds6_compute_reachable_time
  0x2066b1: uip_ds6_init
  0x2067c9: uiplib_ipaddr_snprint
  0x2068b9: uip_ds6_route_init
  0x2068d5: uip_ds6_defrt_rm
  0x20690d: uip_ds6_defrt_lookup
  0x206941: uip_ds6_defrt_add
  0x2069a1: uip_ds6_defrt_choose
  0x2069d1: uip_ds6_defrt_periodic
  0x206a01: uip_ds6_nbr_rm
  0x206a25: uip_ds6_neighbors_init
  0x206a41: uip_ds6_nbr_add
  0x206a81: uip_ds6_nbr_get_ll
  0x206a8d: uip_ds6_nbr_head
  0x206a99: uip_ds6_nbr_next
  0x206aa5: uip_ds6_nbr_ll_lookup
  0x206ab1: tcpip_output
  0x206add: tcpip_input
  0x206b01: tcpip_ipv6_output
  0x206be5: packet_input
  0x206c05: process_thread_tcpip_process
  0x206cc1: tcpip_uipcall
  0x206ced: upper_layer_chksum
  0x206d41: ext_hdr_options_process
  0x206dbd: uip_update_ttl
  0x206de1: uip_init
  0x206e19: uip_remove_ext_hdr
  0x206e81: uip_process
  0x2072dd: ns_input
  0x207545: uip_nd6_init
  0x207551: clear_fragments
  0x20758d: sicslowpan_init
  0x2075a5: set_packet_attrs
  0x2075fd: compress_addr_64
  0x20768d: addr_context_lookup_by_prefix
  0x2076b1: send_packet
  0x2076d5: fragment_copy_payload_and_send
  0x207741: output
  0x207ec1: packet_sent
  0x207f1d: store_fragment
  0x207f75: uncompress_addr
  0x208005: add_fragment
  0x208125: input
  0x2088c1: update_state
  0x208939: rpl_nbr_policy_find_removable
  0x208989: remove_neighbor
  0x2089c5: rpl_neighbor_get_from_lladdr
  0x2089d5: rpl_neighbor_rank_via_nbr
  0x2089ed: rpl_neighbor_get_lladdr
  0x2089fd: best_parent
  0x208a91: rpl_neighbor_is_parent
  0x208aa9: rpl_neighbor_set_preferred_parent
  0x208af1: rpl_neighbor_remove_all
  0x208b21: rpl_neighbor_get_from_ipaddr
  0x208b3d: rpl_neighbor_select_best
  0x208b91: rpl_neighbor_init
  0x208ba5: new_dio_interval
  0x208bfd: schedule_dao_retransmission
  0x208c2d: handle_unicast_dio_timer
  0x208c49: send_new_dao
  0x208c7d: resend_dao
  0x208cb5: handle_dao_ack_timer
  0x208cc9: handle_leaving_timer
  0x208cd9: handle_dio_timer
  0x208d49: rpl_timers_schedule_periodic_dis
  0x208d81: handle_dis_timer
  0x208db5: handle_periodic_timer
  0x208dfd: rpl_timers_dio_reset
  0x208e31: rpl_timers_schedule_unicast_dio
  0x208e59: rpl_timers_schedule_dao
  0x208e8d: rpl_timers_schedule_dao_ack
  0x208ed5: rpl_timers_notify_dao_ack
  0x208f21: get_probing_target
  0x208fe1: rpl_schedule_probing
  0x209009: rpl_schedule_probing_now
  0x209035: rpl_timers_unschedule_leaving
  0x209059: rpl_timers_schedule_leaving
  0x209089: rpl_timers_init
  0x2090a9: rpl_timers_stop_dag_timers
  0x2090ed: rpl_timers_unschedule_state_update
  0x209101: rpl_timers_schedule_state_update
  0x20911d: update_hbh_header
  0x209169: rpl_ext_header_srh_get_next_hop
  0x2091ed: rpl_ext_header_srh_update
  0x209291: rpl_ext_header_hbh_update
  0x209321: rpl_ext_header_remove
  0x2093d1: rpl_ext_header_update
  0x209629: rpl_has_joined
  0x209641: rpl_is_reachable
  0x209659: rpl_get_leaf_only
  0x209665: get_sr_node_ipaddr
  0x209691: set_ip_from_prefix
  0x2096bd: init
  0x2096fd: rpl_link_callback
  0x209729: rpl_get_global_address
  0x20978d: rpl_reset_prefix
  0x2097b5: rpl_set_prefix_from_addr
  0x209825: update_metric_container
  0x209831: within_hysteresis
  0x209869: rank_via_nbr
  0x209899: best_parent
  0x209909: dao_ack_input
  0x209941: dao_input
  0x209a41: dio_input
  0x209c55: dis_input
  0x209c81: rpl_icmp6_dis_output
  0x209cb9: rpl_icmp6_dio_output
  0x209e79: rpl_icmp6_dao_output
  0x209f3d: rpl_icmp6_dao_ack_output
  0x209f81: rpl_icmp6_init
  0x209fb1: init_dag
  0x20a029: process_dio_init_dag
  0x20a0cd: rpl_dag_get_root_ipaddr
  0x20a0fd: rpl_dag_leave
  0x20a151: rpl_dag_poison_and_leave
  0x20a161: rpl_dag_periodic
  0x20a1a9: rpl_is_addr_in_our_dag
  0x20a1d1: rpl_local_repair
  0x20a205: rpl_global_repair
  0x20a23d: rpl_dag_ready_to_advertise
  0x20a261: rpl_dag_update_state
  0x20a395: rpl_process_dio
  0x20a50d: rpl_process_dis
  0x20a539: rpl_process_dao
  0x20a585: rpl_process_dao_ack
  0x20a5d9: rpl_dag_init_root
  0x20a681: rpl_dag_init
  0x20a691: rpl_dag_root_set_prefix
  0x20a6f9: rpl_dag_root_start
  0x20a761: rpl_dag_root_is_root
  0x20a779: process_thread_hello_world_process
  0x20a7c1: __aeabi_uldivmod
  0x20a7f1: __udivmoddi4
  0x20aadd: __aeabi_idiv0
  0x20aae1: memcmp
  0x20ab45: memcpy
  0x20ac31: memmove
  0x20acf9: memset
  0x20ad95: strlen
  0x20adf1: default_handler
  0x20adf3: nmi_handler
  0x20adf9: fade
  0x20ae51: platform_init_stage_one
  0x20ae65: platform_idle
  0x20ae69: status
  0x20ae6d: soc_init
  0x20ae8f: clock_isr
  0x20ae93: rtimer_arch_init
  0x20ae95: uart0_isr
  0x20ae9b: uart1_isr
  0x20aea1: gpio_port_a_isr
  0x20aea7: gpio_port_b_isr
  0x20aead: gpio_port_c_isr
  0x20aeb3: gpio_port_d_isr
  0x20aeb9: send
  0x20aecb: int_master_read_and_disable
  0x20aed3: int_master_status_set
  0x20aed9: dbg_putchar
  0x20aee9: dbg_send_bytes
  0x20af09: configure
  0x20af0d: status
  0x20af11: value
  0x20af45: configure
  0x20af49: status
  0x20af4d: value
  0x20af77: autostart_start
  0x20af8b: stimer_set
  0x20af99: energest_init
  0x20af9b: etimer_set
  0x20afad: etimer_reset
  0x20afbf: etimer_expired
  0x20afc9: rtimer_init
  0x20afcd: call_process
  0x20afd9: timer_set
  0x20afe7: timer_expired
  0x20b003: timer_reset
  0x20b017: ringbuf_init
  0x20b025: ringbuf_put
  0x20b04b: ringbuf_get
  0x20b06b: list_init
  0x20b071: list_head
  0x20b075: list_tail
  0x20b085: list_remove
  0x20b0ab: list_add
  0x20b0c5: list_push
  0x20b0d5: list_item_next
  0x20b0db: memb_init
  0x20b0fb: memb_alloc
  0x20b123: memb_free
  0x20b14d: memb_inmemb
  0x20b169: memb_numfree
  0x20b185: button_hal_get_state
  0x20b1af: item_from_index
  0x20b1c3: index_from_item
  0x20b1d9: nbr_set_bit
  0x20b211: nbr_table_get_from_lladdr
  0x20b237: linkaddr_copy
  0x20b23d: linkaddr_cmp
  0x20b24d: link_stats_is_fresh
  0x20b271: guess_etx_from_rssi
  0x20b2b1: mac_call_sent_callback
  0x20b2c9: write_str
  0x20b2d9: buffer_str
  0x20b301: snprintf
  0x20b31b: putchar
  0x20b327: max_payload
  0x20b32d: input_l2cap_connection_udate_resp
  0x20b351: input_l2cap_credit
  0x20b39b: uipbuf_set_len_field
  0x20b3a3: uipbuf_get_len_field
  0x20b3af: uipbuf_get_next_header
  0x20b3fd: uipbuf_get_last_header
  0x20b429: uipbuf_search_header
  0x20b469: uip_sr_expire_parent
  0x20b491: uip_ds6_list_loop
  0x20b4e1: uip_ds6_maddr_rm
  0x20b4e9: uip_ds6_set_addr_iid
  0x20b4ff: uip_ds6_set_lladdr_from_iid
  0x20b515: get_match_length
  0x20b553: uip_ds6_route_nexthop
  0x20b557: uip_ds6_route_lookup
  0x20b55b: uip_ds6_route_rm
  0x20b55d: uip_ds6_nbr_lookup
  0x20b589: uip_ds6_nbr_update_ll
  0x20b5e7: uip_ds6_nbr_ipaddr_from_lladdr
  0x20b5eb: uip_ds6_nbr_lladdr_from_ipaddr
  0x20b5fd: uip_ds6_link_callback
  0x20b5ff: chksum
  0x20b637: uip_icmp6chksum
  0x20b63d: uip_udpchksum
  0x20b643: uip_htonl
  0x20b655: rpl_neighbor_get_ipaddr
  0x20b663: rpl_neighbor_get_link_stats
  0x20b671: rpl_neighbor_is_fresh
  0x20b67f: handle_state_update
  0x20b683: get_probing_delay
  0x20b69d: handle_probing_timer
  0x20b6c1: drop_route
  0x20b6c3: neighbor_state_changed
  0x20b6c5: rpl_lollipop_greater_than
  0x20b6f9: reset
  0x20b6fb: nbr_link_metric
  0x20b70d: nbr_has_usable_link
  0x20b71f: nbr_path_cost
  0x20b747: nbr_is_acceptable_parent
  0x20b765: get32
  0x20b77d: set32
  0x20b78f: get16
  0x20b79b: set16
  0x20b7a5: rpl_icmp6_update_nbr_table
  0x20b7d3: rpl_process_hbh
  0x20b7f0: als_sensor
  0x20b800: uart_regs
  0x20b858: cc2538_rf_driver
  0x20b890: output_power
  0x20b900: cc2538_temp_sensor
  0x20b910: vdd3_sensor
  0x20b920: ble_l2cap_driver
  0x20b93c: sicslowpan_driver
  0x20b94c: rpl_lite_driver
  0x20b9a0: autostart_processes
  0x20b9a8: linkaddr_null
  0x20b9b0: leds_arch_leds
  0x20bc68: buffer.5551
  0x20bc78: buffer.5560
  0x20bd23: unc_llconf
  0x20bd27: llprefix
  0x20bd29: unc_mxconf
  0x20bd38: ttl_values
  0x20bd3c: unc_ctxconf
  0x20be4e: _etext
  0x20be50: _ldata
  0x27ffd4: flash_cca_lock_page
  0x20000000: _enrdata
  0x20000040: _data
  0x20000050: sensors
  0x20000060: key_up
  0x200000b0: key_left
  0x20000100: key_select
  0x20000150: key_right
  0x200001a0: key_down
  0x200001f0: button_hal_buttons
  0x20000208: cc2538_rf_process
  0x20000218: curr_log_level_main
  0x2000021c: etimer_process
  0x2000022c: ctimer_process
  0x2000023c: stack_check_process
  0x2000024c: button_hal_process
  0x2000025c: serial_line_process
  0x2000026c: bufmem
  0x20000278: buframmem
  0x20000284: neighbor_addr_mem
  0x20000290: link_stats_struct
  0x200002a0: ctxt
  0x200002a8: ble_l2cap_tx_process
  0x200002b8: echo_request_handler
  0x200002c4: echo_reply_handler
  0x200002d0: nodememb
  0x200002dc: defaultroutermemb
  0x200002e8: ds6_neighbors_struct
  0x200002f8: tcpip_process
  0x20000308: ns_input_handler
  0x20000314: rpl_neighbors
  0x20000318: rpl_neighbors_struct
  0x20000328: rpl_mrhof
  0x2000034c: dao_ack_handler
  0x20000358: dis_handler
  0x20000364: dao_handler
  0x20000370: dio_handler
  0x2000037c: hello_world_process
  0x2000038c: send_on_cca
  0x2000038d: rf_channel
  0x2000038e: _edata
  0x20000390: _bss
  0x20000398: rt_ticks_epoch
  0x200003a0: i.5534
  0x200003a4: events.5535
  0x200003a8: next_trigger
  0x200003ac: input_handler
  0x200003b4: ioc_sel
  0x200003b8: ioc_over
  0x200003bc: notification_process
  0x200003c0: prev_MDMTEST1
  0x200003c4: prev_FRMCTRL0
  0x200003c8: periph_permit_pm1_funcs
  0x200003dc: notification_process
  0x200003e0: timerlist
  0x200003e4: next_expiration
  0x200003e8: ctimer_list_list
  0x200003ec: next_rtimer
  0x200003f0: process_current
  0x200003f4: process_list
  0x200003f8: events
  0x20000578: et.5876
  0x20000588: button_event_handler
  0x20000594: pmask
  0x20000598: rxbuf
  0x200005a0: ptr.5519
  0x200005a4: handlers_list
  0x200005a8: bufmem_memb_mem
  0x200005c8: nbr_table_keys_list
  0x200005cc: neighbor_addr_mem_memb_mem
  0x2000068c: all_tables
  0x200006ac: num_tables
  0x200006b0: packetbuf_aligned
  0x20000730: ip_processor_list_list
  0x20000734: _link_stats_mem
  0x200007f4: echo_reply_callback_list_list
  0x200007f8: input_handler_list_list
  0x200007fc: num_nodes
  0x20000800: nodememb_memb_mem
  0x20000980: nodelist_list
  0x20000984: locmaddr
  0x20000988: locprefix
  0x2000098c: locaddr
  0x20000990: defaultroutermemb_memb_mem
  0x200009d0: defaultrouterlist_list
  0x200009d4: periodic
  0x200009e4: nbr
  0x200009e8: nd6_opt_llao
  0x200009ec: addr
  0x200009f0: callback
  0x200009f4: context
  0x200009f8: last_rssi
  0x200009fc: hc06_ptr
  0x20000a00: packetbuf_ptr
  0x20000a04: packetbuf_payload_len
  0x20000a08: last_tx_status
  0x20000a0c: mac_max_payload
  0x20000a10: frag_info
  0x20000b80: worst_rank_nbr_lladdr
  0x20000b84: num_parents
  0x20000b88: _rpl_neighbors_mem
  0x20000c08: periodic_timer
  0x20000c28: dis_timer
  0x20000c48: timer.5488
  0x20000c58: node_id
  0x20000c5a: buframmem_memb_mem
  0x200011ba: buflen
  0x200011bc: bufptr
  0x200011be: l2cap_channels
  0x20001bde: uipbuf_attrs
  0x20001bea: uipbuf_default_attrs
  0x20001bf6: tmp_ipaddr
  0x20001c06: default_prefix
  0x20001c16: loc_fipaddr
  0x20001c26: _ds6_neighbors_mem
  0x20001d46: uip_ext_len
  0x20001d48: lastport
  0x20001d4a: my_tag
  0x20001d4c: worst_rank
  0x20001d4e: root_ipaddr.7069
  0x20001d5e: num_sensors
  0x20001d5f: crc_corr
  0x20001d60: was_on
  0x20001d61: rssi
  0x20001d62: poll_mode
  0x20001d63: rf_flags
  0x20001d64: max_pm
  0x20001d65: initialized
  0x20001d66: fevent
  0x20001d67: nevents
  0x20001d68: poll_requested
  0x20001d69: lastevent
  0x20001d6a: rxbuf_data
  0x20001dea: overflow.5512
  0x20001deb: buf.5518
  0x20001e6b: buframmem_memb_used
  0x20001e73: bufmem_memb_used
  0x20001e7b: locked_map
  0x20001e8b: neighbor_addr_mem_memb_used
  0x20001e9b: used_map
  0x20001eab: hdrlen
  0x20001eac: l2cap_channel_count
  0x20001ead: l2cap_tx_event
  0x20001eae: ble_addr
  0x20001eb4: nodememb_memb_used
  0x20001ec4: defaultroutermemb_memb_used
  0x20001ec6: uip_ext_bitmap
  0x20001ec7: uip_last_proto
  0x20001ec8: nd6_opt_offset
  0x20001ec9: curr_page
  0x20001eca: uncomp_hdr_len
  0x20001ecb: addr_contexts
  0x20001ed5: frag_buf
  0x20002421: packetbuf_hdr_len
  0x20002422: rpl_leaf_only
  0x20002423: initialized.7080
  0x20002424: periodic_timer
  0x20002444: uip_ds6_timer_ra
  0x2000244c: uip_ds6_if
  0x20002544: uip_ds6_netif_addr_list_offset
  0x20002545: uip_ds6_addr_size
  0x20002548: uip_ds6_prefix_list
  0x200025a8: uip_ds6_timer_periodic
  0x200025b8: uip_len
  0x200025bc: uip_sappdata
  0x200025c0: uip_lladdr
  0x200025c8: uip_aligned_buf
  0x20002ac8: uip_flags
  0x20002acc: uip_udp_conn
  0x20002ad0: uip_appdata
  0x20002ad4: uip_conn
  0x20002ad8: uip_slen
  0x20002adc: uip_udp_conns
  0x20002bdc: curr_instance
  0x20002d3c: packetbuf_addrs
  0x20002d4c: packetbuf_attrs
  0x20002d66: linkaddr_node_addr
  0x20002d6e: rpl_multicast_addr
  0x20002d7e: sensors_event
  0x20002d7f: sensors_flags
  0x20002d83: button_hal_release_event
  0x20002d84: button_hal_periodic_event
  0x20002d85: button_hal_press_event
  0x20002d86: serial_line_event_message
  0x20002d87: tcpip_event
  0x20002d88: _stack
  0x20003588: _heap
  0x20008000: _eheap
