interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x8000000
    file: PLC.bin
    ivt_offset: 0x0
    permissions: r-x
    size: 0x16114
symbols:
  0x0: reent.c
  0x400: _Min_Stack_Size
  0x2000: _Min_Heap_Size
  0x8000000: g_pfnVectors
  0x80001ad: __do_global_dtors_aux
  0x80001d1: frame_dummy
  0x8000219: strlen
  0x8000231: memchr
  0x80002d1: __aeabi_uldivmod
  0x8000301: __udivmoddi4
  0x80005dd: __aeabi_idiv0
  0x80005e1: _ZN6Modbus5beginEl
  0x800064d: _ZN6Modbus4initEhhh
  0x8000663: _ZN6ModbusC1Ehhh
  0x8000671: _Z41__static_initialization_and_destruction_0ii
  0x8000695: _ZN6Modbus11getRxBufferEv
  0x8000709: _ZN6Modbus7calcCRCEh
  0x800074d: _ZN6Modbus12sendTxBufferEv
  0x80007d1: _ZN6Modbus15validateRequestEv
  0x80008ad: _ZN6Modbus14buildExceptionEh
  0x80008c3: _ZN6Modbus11process_FC1EPth
  0x8000979: _ZN6Modbus11process_FC3EPth
  0x80009e1: _ZN6Modbus11process_FC5EPth
  0x8000a2f: _ZN6Modbus11process_FC6EPth
  0x8000a5b: _ZN6Modbus12process_FC15EPth
  0x8000ae5: _ZN6Modbus12process_FC16EPth
  0x8000b35: _ZN6Modbus4pollEPth
  0x8000c2d: setup
  0x8000c41: loop
  0x8000c59: _GLOBAL__sub_I__ZN6ModbusC2Ev
  0x8000c69: SystemClock_Config
  0x8000d19: Reset_Handler
  0x8000d20: CopyDataInit
  0x8000d28: LoopCopyDataInit
  0x8000d36: FillZerobss
  0x8000d3c: LoopFillZerobss
  0x8000d68: Default_Handler
  0x8000d69: CAN2_SCE_IRQHandler
  0x8000d6b: init
  0x8000d73: HAL_MspInit
  0x8000d75: HAL_InitTick
  0x8000dc1: HAL_Init
  0x8000df5: HAL_IncTick
  0x8000e0d: HAL_GetTick
  0x8000e19: HAL_NVIC_SetPriorityGrouping
  0x8000e3d: HAL_NVIC_SetPriority
  0x8000ea1: HAL_NVIC_EnableIRQ
  0x8000ebd: HAL_SYSTICK_Config
  0x8000ee9: HAL_NVIC_ClearPendingIRQ
  0x8000f09: HAL_SYSTICK_CLKSourceConfig
  0x8000f29: HAL_SYSTICK_Callback
  0x8000f2b: HAL_SYSTICK_IRQHandler
  0x8000f33: HAL_DAC_DeInit
  0x8000f4f: HAL_DAC_Stop
  0x8000f69: HAL_DMA_Abort_IT
  0x8000f91: HAL_GPIO_Init
  0x8001175: HAL_GPIO_WritePin
  0x8001181: HAL_GPIO_EXTI_IRQHandler
  0x800119d: I2C_Master_SB
  0x8001227: I2C_Master_ADD10
  0x8001233: I2C_Master_ADDR
  0x80013fd: I2C_SlaveTransmit_BTF
  0x800141d: I2C_SlaveReceive_BTF
  0x800143d: HAL_I2C_Slave_Sequential_Transmit_IT
  0x80014c9: HAL_I2C_Slave_Sequential_Receive_IT
  0x8001555: HAL_I2C_EnableListen_IT
  0x8001593: HAL_I2C_MasterTxCpltCallback
  0x8001595: HAL_I2C_MasterRxCpltCallback
  0x8001597: HAL_I2C_SlaveTxCpltCallback
  0x8001599: I2C_SlaveTransmit_TXE
  0x80015e9: HAL_I2C_SlaveRxCpltCallback
  0x80015eb: I2C_SlaveReceive_RXNE
  0x8001637: I2C_Slave_ADDR
  0x8001661: I2C_Slave_AF
  0x80016f5: HAL_I2C_MemTxCpltCallback
  0x80016f7: I2C_MasterTransmit_TXE
  0x8001841: I2C_MasterTransmit_BTF
  0x80018df: HAL_I2C_MemRxCpltCallback
  0x80018e1: I2C_MasterReceive_RXNE
  0x800197d: I2C_MasterReceive_BTF
  0x8001a89: HAL_I2C_AbortCpltCallback
  0x8001a8d: I2C_ITError
  0x8001bd9: I2C_Slave_STOPF
  0x8001cdd: HAL_I2C_EV_IRQHandler
  0x8001e45: HAL_I2C_ER_IRQHandler
  0x8001f19: I2C_DMAAbort
  0x8001f79: HAL_PWREx_EnableOverDrive
  0x8001ff9: HAL_RCC_OscConfig
  0x8002391: HAL_RCC_GetSysClockFreq
  0x8002465: HAL_RCC_ClockConfig
  0x80025bd: HAL_RCC_GetHCLKFreq
  0x80025c9: HAL_RCC_GetPCLK1Freq
  0x80025e9: HAL_RCC_GetPCLK2Freq
  0x8002609: HAL_RTC_AlarmIRQHandler
  0x8002669: HAL_RTCEx_AlarmBEventCallback
  0x800266b: HAL_TIM_PWM_DeInit
  0x80026a5: HAL_TIM_IC_CaptureCallback
  0x80026a7: HAL_TIM_PWM_PulseFinishedCallback
  0x80026a9: HAL_TIM_TriggerCallback
  0x80026ab: HAL_TIM_IRQHandler
  0x8002825: TIM_CCxChannelCmd
  0x8002841: HAL_TIM_PWM_Stop
  0x80028b1: TIM_CCxNChannelCmd
  0x80028cd: HAL_TIMEx_PWMN_Stop
  0x8002919: HAL_TIMEx_CommutationCallback
  0x800291b: HAL_TIMEx_BreakCallback
  0x800291d: UART_EndRxTransfer
  0x8002939: UART_Transmit_IT
  0x80029a5: UART_SetConfig
  0x8002ce9: UART_WaitOnFlagUntilTimeout
  0x8002d4d: HAL_UART_MspInit
  0x8002d4f: HAL_UART_Init
  0x8002dad: HAL_UART_Transmit
  0x8002e8f: HAL_UART_Transmit_IT
  0x8002ed7: HAL_UART_Receive_IT
  0x8002f29: UART_EndTransmit_IT
  0x8002f43: UART_Receive_IT
  0x8002fd9: HAL_UART_IRQHandler
  0x80030f9: UART_DMAAbortOnError
  0x8003109: HAL_UART_GetState
  0x8003115: is_pin_configured
  0x800312b: set_pin_configured
  0x8003149: reset_pin_configured
  0x8003169: get_GPIO_Port
  0x80031d9: set_GPIO_Port_Clock
  0x800335d: get_dac_channel
  0x8003379: get_pwm_channel
  0x80033a5: HAL_DAC_MspDeInit
  0x80033b5: dac_stop
  0x80033e9: HAL_TIM_PWM_MspDeInit
  0x80033f1: pwm_stop
  0x8003449: GetCurrentMilli
  0x8003451: noOsSystickHandler
  0x8003453: SysTick_Handler
  0x8003463: digital_io_init
  0x8003493: digital_io_write
  0x80034ab: hw_config_init
  0x80034b7: pinmap_find_peripheral
  0x80034d1: pinmap_peripheral
  0x80034e3: pinmap_find_pin
  0x80034fb: pinmap_pin
  0x800350b: pinmap_find_function
  0x8003527: pinmap_function
  0x800353b: pin_in_pinmap
  0x800355f: pinmap_merge_peripheral
  0x8003571: HAL_RTC_AlarmAEventCallback
  0x8003589: RTC_Alarm_IRQHandler
  0x8003599: SystemInit
  0x80035d9: timer_disable_clock
  0x800372d: get_timer_obj
  0x8003731: HAL_TIM_OC_DelayElapsedCallback
  0x800374b: HAL_TIM_PeriodElapsedCallback
  0x8003759: TIM1_UP_TIM10_IRQHandler
  0x8003775: TIM2_IRQHandler
  0x8003789: TIM3_IRQHandler
  0x800379d: TIM4_IRQHandler
  0x80037b1: TIM5_IRQHandler
  0x80037c5: TIM6_DAC_IRQHandler
  0x80037d9: TIM7_IRQHandler
  0x80037ed: TIM8_UP_TIM13_IRQHandler
  0x8003809: TIM1_BRK_TIM9_IRQHandler
  0x800381d: TIM1_TRG_COM_TIM11_IRQHandler
  0x8003831: TIM8_BRK_TIM12_IRQHandler
  0x8003845: TIM8_TRG_COM_TIM14_IRQHandler
  0x8003859: get_i2c_obj
  0x800385d: HAL_I2C_AddrCallback
  0x80038ad: HAL_I2C_ListenCpltCallback
  0x80038dd: HAL_I2C_ErrorCallback
  0x80038f5: I2C1_EV_IRQHandler
  0x8003905: I2C1_ER_IRQHandler
  0x8003915: I2C2_EV_IRQHandler
  0x8003925: I2C2_ER_IRQHandler
  0x8003935: I2C3_EV_IRQHandler
  0x8003945: I2C3_ER_IRQHandler
  0x8003955: uart_init
  0x8003ca5: uart_debug_init
  0x8003cf5: uart_debug_write
  0x8003dad: serial_rx_active
  0x8003dd1: serial_tx_active
  0x8003df5: uart_getc
  0x8003e31: uart_attach_rx_callback
  0x8003e89: uart_attach_tx_callback
  0x8003edd: uart_index
  0x8003f01: HAL_UART_RxCpltCallback
  0x8003f25: HAL_UART_TxCpltCallback
  0x8003f71: HAL_UART_ErrorCallback
  0x8003fb1: USART1_IRQHandler
  0x8003fc9: USART2_IRQHandler
  0x8003fe1: USART3_IRQHandler
  0x8003ff9: UART4_IRQHandler
  0x8004011: UART5_IRQHandler
  0x8004029: USART6_IRQHandler
  0x8004041: UART7_IRQHandler
  0x8004059: UART8_IRQHandler
  0x8004071: _sbrk
  0x80040ad: _close
  0x80040b3: _fstat
  0x80040bd: _isatty
  0x80040c1: _lseek
  0x80040c5: _read
  0x80040c9: _write
  0x80040d5: _exit
  0x80040d9: _kill
  0x80040e9: _getpid
  0x80040ed: pinMode
  0x8004199: digitalWrite
  0x80041e1: millis
  0x80041e9: _ZN14HardwareSerial16_tx_complete_irqEP8serial_s
  0x800421d: _ZN14HardwareSerial9availableEv
  0x8004231: _ZN14HardwareSerial4peekEv
  0x800424d: _ZN14HardwareSerial4readEv
  0x8004275: _ZN14HardwareSerial5flushEv
  0x8004289: _ZN14HardwareSerial16_rx_complete_irqEP8serial_s
  0x80042c5: _ZN14HardwareSerial5writeEh
  0x8004315: _Z14serialEventRunv
  0x8004341: _ZN14HardwareSerial4initEv
  0x8004365: _ZN14HardwareSerial5beginEmh
  0x8004421: _ZN14HardwareSerial5setRxEm
  0x800443d: _ZN14HardwareSerial5setTxEm
  0x8004459: _ZN14HardwareSerialC1EPv
  0x80044b5: _Z41__static_initialization_and_destruction_0ii
  0x80044d9: _GLOBAL__sub_I_Serial3
  0x80044e7: _ZNK9IPAddress7printToER5Print
  0x8004521: _ZN9IPAddressC1Ehhhh
  0x800453d: _Z41__static_initialization_and_destruction_0ii
  0x8004569: _GLOBAL__sub_I__ZN9IPAddressC2Ev
  0x8004577: _ZN5Print5writeEPKhj
  0x800459b: _ZN5Print5printEc
  0x80045a5: _ZN5Print11printNumberEmh
  0x80045ff: _ZN5Print5printEmi
  0x8004615: _ZN5Print5printEhi
  0x800461d: _Z8makeWordhh
  0x8004623: _Z11initVariantv
  0x8004625: _Z7premainv
  0x8004635: main
  0x8004655: _ZL10get_pin_idt
  0x8004669: __tcf_0
  0x8004691: _Z41__static_initialization_and_destruction_0ii
  0x800473d: EXTI0_IRQHandler
  0x8004747: EXTI1_IRQHandler
  0x8004751: EXTI2_IRQHandler
  0x800475b: EXTI3_IRQHandler
  0x8004765: EXTI4_IRQHandler
  0x800476f: EXTI9_5_IRQHandler
  0x8004785: EXTI15_10_IRQHandler
  0x800479d: _ZNKSt8functionIFvvEEclEv
  0x80047ad: HAL_GPIO_EXTI_Callback
  0x80047cd: _GLOBAL__sub_I__Z22stm32_interrupt_enableP12GPIO_TypeDeftSt8functionIFvvEEm
  0x80047db: __aeabi_atexit
  0x80047e5: __assert_func
  0x8004821: __cxa_atexit
  0x800483d: fiprintf
  0x8004861: __libc_init_array
  0x80048a9: memset
  0x80048b9: _free_r
  0x8004955: _malloc_r
  0x8004a11: __sfputc_r
  0x8004a3d: __sfputs_r
  0x8004a61: _vfiprintf_r
  0x8004c8d: _printf_common
  0x8004d79: _printf_i
  0x8004fb9: iprintf
  0x8004fe9: _sbrk_r
  0x8005009: __swbuf_r
  0x80050ad: __swsetup_r
  0x8005189: abort
  0x8005199: __sflush_r
  0x80052a9: _fflush_r
  0x80052fd: _cleanup_r
  0x8005309: std.isra.0
  0x8005351: __sfmoreglue
  0x800537d: __sinit
  0x80053dd: __sfp
  0x8005455: _fwalk_reent
  0x8005491: __swhatbuf_r
  0x80054d9: __smakebuf_r
  0x8005559: __malloc_lock
  0x800555b: __malloc_unlock
  0x800555d: _raise_r
  0x80055ad: raise
  0x80055bd: _kill_r
  0x80055e1: _getpid_r
  0x80055e5: __sread
  0x8005607: __swrite
  0x800563f: __sseek
  0x8005663: __sclose
  0x800566d: _write_r
  0x8005691: _close_r
  0x80056b1: _fstat_r
  0x80056d5: _isatty_r
  0x80056f5: _lseek_r
  0x8005719: _read_r
  0x800573d: _ZSt25__throw_bad_function_callv
  0x8005745: _GLOBAL__sub_I__ZNSt12ctype_bynameIcEC2ERKSsj
  0x8005809: _GLOBAL__sub_I__ZNSt12ctype_bynameIwEC2ERKSsj
  0x80058cd: _GLOBAL__sub_I__ZNSt12ctype_bynameIwEC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEj
  0x8005951: _GLOBAL__sub_I__ZNSt12ctype_bynameIcEC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEj
  0x80059d4: __EH_FRAME_BEGIN__
  0x80059d5: _init
  0x80059e1: _fini
  0x80059ec: _etext
  0x80059f4: PinMap_DAC
  0x8005a18: PinMap_PWM
  0x8005bec: PinMap_UART_RX
  0x8005c7c: PinMap_UART_TX
  0x8005d18: digitalPin
  0x8005dd8: AHBPrescTable
  0x8005de8: APBPrescTable
  0x8005ea8: _ZTV14HardwareSerial
  0x8005ec8: _ZZN14HardwareSerial5beginEmhE19__PRETTY_FUNCTION__
  0x8005efc: _ZTV9IPAddress
  0x8005f44: _global_impure_ptr
  0x8005f7c: __sf_fake_stderr
  0x8005f9c: __sf_fake_stdin
  0x8005fbc: __sf_fake_stdout
  0x8005fdc: __exidx_start
  0x8005fe4: __exidx_end
  0x8005fe8: __frame_dummy_init_array_entry
  0x800600c: __init_array_end
  0x8006010: _sidata
  0x8006114: _siccmram
  0x10000000: _sccmram
  0x20000000: __dso_handle
  0x20000004: au16data
  0x20000024: uwTickFreq
  0x20000028: uwTickPrio
  0x2000002c: SystemCoreClock
  0x20000030: serial_debug
  0x200000a0: _impure_ptr
  0x200000a4: impure_data
  0x20000104: _edata
  0x20000108: object.8672
  0x20000120: slave
  0x20000184: RTCUserCallback
  0x20000188: RtcHandle
  0x200001a8: callbackUserData
  0x200001ac: timer_handles
  0x20000204: i2c_handles
  0x20000210: rx_callback
  0x20000238: rx_callback_obj
  0x20000260: tx_callback
  0x20000288: tx_callback_obj
  0x200002b0: uart_handlers
  0x200002d8: heap_end.4572
  0x200002dc: g_anOutputPinConfigured
  0x20000308: g_digPinConfigured
  0x20000334: Serial3
  0x2000047c: _ZL11INADDR_NONE
  0x20000484: _ZL13gpio_irq_conf
  0x200005c4: __malloc_free_list
  0x200005c8: __malloc_sbrk_start
  0x200005cc: _ZGVNSt7collateIcE2idE
  0x200005d0: _ZGVNSt8messagesIcE2idE
  0x200005d4: _ZGVNSt8time_getIcSt19istreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x200005d8: _ZGVNSt8time_putIcSt19ostreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x200005dc: _ZGVNSt11__timepunctIcE2idE
  0x200005e0: _ZGVNSt7num_putIcSt19ostreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x200005e4: _ZGVNSt7num_getIcSt19istreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x200005e8: _ZGVNSt8numpunctIcE2idE
  0x200005ec: _ZGVNSt9money_putIcSt19ostreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x200005f0: _ZGVNSt9money_getIcSt19istreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x200005f4: _ZGVNSt10moneypunctIcLb1EE2idE
  0x200005f8: _ZGVNSt10moneypunctIcLb0EE2idE
  0x200005fc: _ZGVNSt7collateIwE2idE
  0x20000600: _ZGVNSt8messagesIwE2idE
  0x20000604: _ZGVNSt8time_getIwSt19istreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x20000608: _ZGVNSt8time_putIwSt19ostreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x2000060c: _ZGVNSt11__timepunctIwE2idE
  0x20000610: _ZGVNSt7num_putIwSt19ostreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x20000614: _ZGVNSt7num_getIwSt19istreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x20000618: _ZGVNSt8numpunctIwE2idE
  0x2000061c: _ZGVNSt9money_putIwSt19ostreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x20000620: _ZGVNSt9money_getIwSt19istreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x20000624: _ZGVNSt10moneypunctIwLb1EE2idE
  0x20000628: _ZGVNSt10moneypunctIwLb0EE2idE
  0x2000062c: _ZGVNSt7__cxx117collateIwE2idE
  0x20000630: _ZGVNSt7__cxx118messagesIwE2idE
  0x20000634: _ZGVNSt7__cxx118time_getIwSt19istreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x20000638: _ZGVNSt7__cxx118numpunctIwE2idE
  0x2000063c: _ZGVNSt7__cxx119money_putIwSt19ostreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x20000640: _ZGVNSt7__cxx119money_getIwSt19istreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x20000644: _ZGVNSt7__cxx1110moneypunctIwLb1EE2idE
  0x20000648: _ZGVNSt7__cxx1110moneypunctIwLb0EE2idE
  0x2000064c: _ZGVNSt7__cxx117collateIcE2idE
  0x20000650: _ZGVNSt7__cxx118messagesIcE2idE
  0x20000654: _ZGVNSt7__cxx118time_getIcSt19istreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x20000658: _ZGVNSt7__cxx118numpunctIcE2idE
  0x2000065c: _ZGVNSt7__cxx119money_putIcSt19ostreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x20000660: _ZGVNSt7__cxx119money_getIcSt19istreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x20000664: _ZGVNSt7__cxx1110moneypunctIcLb1EE2idE
  0x20000668: _ZGVNSt7__cxx1110moneypunctIcLb0EE2idE
  0x2000066c: uwTick
  0x20000670: errno
  0x20000674: __bss_end__
  0x20000678: _end
  0x20030000: _estack
