interrupt:
  mode: round-robin
  trigger:
    on-infinite-sleep: true
    interval: 1000

memory_maps:
  - name: ".stack"
    address: 0x1ffec000
    size: 0xa000
    type: ram
  - name: mmio
    address: 0x40000000
    size: 0x20000000
    type: mmio
  - name: ram
    address: 0x20000000
    size: 0x100000
    type: ram
  - name: text
    address: 0x0
    size: 0x19400
    file:
      path: ConsoleX.bin
    type: rom
