interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x202000
    file: ip64-router.bin
    ivt_offset: 0x0
    permissions: r-x
    size: 0x8e000
symbols:
  0x0: ip64-eth.c
  0x202000: vectors
  0x20228d: reset_handler
  0x2022cd: platform_init_stage_two
  0x202319: platform_init_stage_three
  0x2023a5: leds_on
  0x202405: leds_off
  0x20244d: leds_init
  0x202491: enc28j60_arch_spi_select
  0x2024a1: enc28j60_arch_spi_deselect
  0x2024ad: enc28j60_arch_spi_init
  0x20253d: enc28j60_arch_spi_write
  0x202549: enc28j60_arch_spi_read
  0x202555: soc_get_rev
  0x20256d: soc_print_info
  0x20257d: update_ticks
  0x2025c9: clock_init
  0x202615: clock_time
  0x202629: clock_seconds
  0x20263d: clock_delay_usec
  0x202659: clock_adjust
  0x202679: rtimer_arch_next_trigger
  0x202685: rtimer_arch_now
  0x2026b1: rtimer_arch_schedule
  0x202709: rtimer_isr
  0x20273d: permit_pm1
  0x202761: uart_isr
  0x2027c5: uart_init
  0x20296d: uart_set_input
  0x20297d: uart_write_byte
  0x202999: watchdog_init
  0x2029a5: watchdog_start
  0x2029b1: watchdog_periodic
  0x2029c1: nvic_init
  0x2029d1: sys_ctrl_init
  0x202a45: gpio_port_isr
  0x202a91: ioc_init
  0x202aad: ioc_set_over
  0x202ac1: ioc_set_sel
  0x202ad5: adc_get
  0x202b4d: permit_pm1
  0x202b5d: crypto_isr
  0x202b8d: crypto_enable
  0x202bad: crypto_init
  0x202be9: crypto_disable
  0x202c09: gpio_hal_arch_no_port_pin_cfg_set
  0x202ce9: 'on'
  0x202d11: 'off'
  0x202d51: set_channel
  0x202d89: channel_clear
  0x202dc5: read
  0x202ded: receiving_packet
  0x202e05: pending_packet
  0x202e15: get_value
  0x202f79: set_object
  0x202fa9: get_object
  0x2030ed: transmit
  0x203191: prepare
  0x2031f9: set_poll_mode
  0x20329d: init
  0x203385: process_thread_cc2538_rf_process
  0x203415: set_value
  0x2035a5: cc2538_rf_rx_tx_isr
  0x2035c9: cc2538_rf_err_isr
  0x2035f1: udma_init
  0x203625: udma_set_channel_src
  0x203635: udma_set_channel_dst
  0x203649: udma_set_channel_control_word
  0x20365d: udma_channel_enable
  0x203675: udma_channel_mask_set
  0x20368d: udma_channel_sw_request
  0x2036a5: udma_isr
  0x2036b5: udma_err_isr
  0x2036c1: select_32_mhz_xosc
  0x2036f1: lpm_exit
  0x203725: lpm_enter
  0x2037dd: lpm_register_peripheral
  0x203801: lpm_init
  0x203825: pka_isr
  0x203855: dbg_putchar
  0x203895: ieee_addr_cpy_to
  0x2038f5: main
  0x203ae1: stimer_expired
  0x203b01: log_6addr
  0x203b21: log_lladdr
  0x203b5d: update_time
  0x203ba1: etimer_request_poll
  0x203bad: process_thread_etimer_process
  0x203c59: add_timer
  0x203c99: etimer_pending
  0x203ca9: etimer_stop
  0x203cdd: node_id_init
  0x203cf5: process_thread_ctimer_process
  0x203d75: ctimer_init
  0x203d9d: ctimer_set_with_process
  0x203de1: ctimer_set
  0x203df5: ctimer_reset
  0x203e2d: ctimer_stop
  0x203e59: ctimer_expired
  0x203e8d: call_process.part.0
  0x203ec5: exit_process
  0x203f45: do_poll
  0x203f79: process_alloc_event
  0x203f89: process_init
  0x203fb9: process_run
  0x20403d: process_nevents
  0x204051: process_post
  0x20408d: process_post_synch
  0x2040a1: process_start
  0x2040d1: process_poll
  0x2040e9: rtimer_run_next
  0x204111: stack_check_init
  0x204139: stack_check_get_usage
  0x204179: process_thread_stack_check_process
  0x204225: process_thread_sensors_process
  0x204301: random_rand
  0x204321: random_init
  0x20439d: duration_exceeded_callback
  0x2043d1: process_thread_button_hal_process
  0x204445: press_release_handler
  0x20445d: debounce_handler
  0x2044c1: button_hal_init
  0x2045b5: process_thread_serial_line_process
  0x204655: serial_line_input_byte
  0x204699: serial_line_init
  0x2046bd: gpio_hal_register_handler
  0x2046c9: gpio_hal_event_handler
  0x2046ed: gpio_hal_init
  0x2046f9: queuebuf_init
  0x204715: queuebuf_numfree
  0x204721: queuebuf_new_from_packetbuf
  0x204765: queuebuf_free
  0x204791: queuebuf_to_packetbuf
  0x2047c1: index_from_key
  0x2047e1: index_from_lladdr
  0x204821: used_count
  0x204849: nbr_get_bit.constprop.3
  0x204875: remove_key
  0x2048fd: nbr_table_is_registered
  0x20491d: nbr_table_register
  0x20494d: nbr_table_next
  0x204995: nbr_table_head
  0x2049cd: entry_is_allowed.isra.2
  0x204a3d: nbr_table_add_lladdr
  0x204aed: nbr_table_remove
  0x204b19: nbr_table_get_lladdr
  0x204b3d: packetbuf_set_datalen
  0x204b49: packetbuf_datalen
  0x204b55: packetbuf_hdrlen
  0x204b6d: packetbuf_dataptr
  0x204b7d: packetbuf_copyto
  0x204bc1: packetbuf_attr_clear
  0x204bf5: packetbuf_clear
  0x204c15: packetbuf_copyfrom
  0x204c41: packetbuf_attr_copyto
  0x204c65: packetbuf_attr_copyfrom
  0x204c89: packetbuf_set_attr
  0x204c99: packetbuf_attr
  0x204ca5: packetbuf_set_addr
  0x204cbd: packetbuf_addr
  0x204ccd: netstack_process_ip_callback
  0x204d0d: netstack_init
  0x204d31: periodic
  0x204d5d: link_stats_packet_sent
  0x204de1: link_stats_input_callback
  0x204e45: link_stats_init
  0x204e6d: process_thread_enc28j60_ip64_driver_process
  0x204eb5: init
  0x204f3d: is_mac_mii_reg
  0x204f71: setregbank
  0x204f95: enc28j60_init
  0x2050b9: enc28j60_read
  0x205181: fill_space
  0x2051b5: format_str_v
  0x205889: printf
  0x2058a9: vsnprintf
  0x2058d1: packet_input
  0x2058dd: 'on'
  0x2058e9: 'off'
  0x2058f5: max_payload
  0x20590d: send_packet
  0x205929: uipbuf_add_ext_hdr
  0x205959: uipbuf_set_len
  0x20596d: uipbuf_get_attr
  0x205981: uipbuf_set_attr
  0x205995: uipbuf_clear_attr
  0x2059a9: uipbuf_clear
  0x2059c9: uipbuf_init
  0x2059e9: echo_reply_input
  0x205a55: echo_request_input
  0x205aed: uip_icmp6_input
  0x205b25: uip_icmp6_register_input_handler
  0x205b31: uip_icmp6_error_output
  0x205c75: uip_icmp6_init
  0x205c91: uip_ds6_prefix_add
  0x205cf5: uip_ds6_is_addr_onlink
  0x205d35: uip_ds6_addr_lookup
  0x205d61: uip_ds6_get_link_local
  0x205da1: uip_ds6_maddr_add
  0x205ded: uip_ds6_addr_add
  0x205e81: uip_ds6_maddr_lookup
  0x205ead: uip_ds6_addr_rm
  0x205ef1: uip_ds6_select_src
  0x205f85: uip_ds6_send_ra_sollicited
  0x205fb9: uip_ds6_send_ra_periodic
  0x206009: uip_ds6_periodic
  0x206075: uip_ds6_compute_reachable_time
  0x2060a1: uip_ds6_init
  0x2061c9: ip64_addr_4to6
  0x2061f9: ip64_addr_is_ip64
  0x206219: call_route_callback
  0x206269: uip_ds6_route_init
  0x2062b5: uip_ds6_route_nexthop
  0x2062d1: uip_ds6_route_head
  0x2062dd: uip_ds6_route_lookup
  0x206345: uip_ds6_route_rm
  0x2063d9: rm_routelist
  0x206409: uip_ds6_defrt_rm
  0x20644d: uip_ds6_defrt_lookup
  0x206481: uip_ds6_defrt_choose
  0x2064b1: uip_ds6_defrt_periodic
  0x2064e1: uip_ds6_nbr_rm
  0x206505: uip_ds6_neighbors_init
  0x206521: uip_ds6_nbr_add
  0x206589: uip_ds6_nbr_get_ll
  0x206595: uip_ds6_nbr_head
  0x2065a1: uip_ds6_nbr_next
  0x2065ad: uip_ds6_nbr_ll_lookup
  0x2065b9: uip_ds6_neighbor_periodic
  0x2066b9: start_periodic_tcp_timer
  0x2066d5: tcpip_output
  0x206701: udp_new
  0x206719: tcpip_input
  0x20673d: tcpip_ipv6_output
  0x2068b9: packet_input.part.4
  0x2068f9: process_thread_tcpip_process
  0x206a89: tcpip_poll_udp
  0x206a99: tcpip_uipcall
  0x206b01: ext_hdr_options_process
  0x206b7d: uip_update_ttl
  0x206ba1: uip_add32
  0x206bf5: uip_add_rcv_nxt
  0x206c25: uip_init
  0x206c89: uip_remove_ext_hdr
  0x206cf1: uip_udp_new
  0x206d7d: uip_unlisten
  0x206da1: uip_process
  0x207bad: uip_send
  0x207c0d: uip_nameserver_update
  0x207c31: uip_nameserver_get
  0x207c41: extract_lladdr_from_llao_aligned
  0x207c61: create_llao
  0x207c89: rs_input
  0x207df5: na_input
  0x207f85: ns_input
  0x2081dd: uip_nd6_ns_output
  0x208329: uip_nd6_ra_output
  0x208511: uip_nd6_init
  0x208535: clear_fragments
  0x208571: sicslowpan_init
  0x208589: set_packet_attrs
  0x2085e1: compress_addr_64
  0x208671: addr_context_lookup_by_prefix
  0x208695: send_packet
  0x2086b9: fragment_copy_payload_and_send
  0x208725: output
  0x208ea5: packet_sent
  0x208f01: store_fragment
  0x208f5d: uncompress_addr
  0x208fed: add_fragment
  0x20910d: input
  0x2099a1: uiplib_ipaddr_snprint
  0x209a91: arp_update
  0x209b65: ip64_arp_arp_input
  0x209c1d: ip64_arp_check_cache
  0x209cb9: ip64_arp_create_ethhdr
  0x209d95: ip64_arp_create_arp_request
  0x209e4d: process_thread_ip64_ipv4_dhcp_process
  0x209e95: ip64_ipv4_dhcp_init
  0x209eb1: ip64_dhcpc_configured
  0x209f3d: output
  0x209fad: ip64_eth_interface_input
  0x20a009: interface_init
  0x20a015: interface_output
  0x20a025: ip64_set_hostaddr
  0x20a03d: ip64_set_netmask
  0x20a049: ip64_set_draddr
  0x20a055: ip64_get_hostaddr
  0x20a05d: ip64_get_netmask
  0x20a065: ip64_get_draddr
  0x20a06d: ip64_set_ipv6_address
  0x20a079: ip64_init
  0x20a0d5: ip64_6to4
  0x20a319: ip64_4to6
  0x20a56d: check_age
  0x20a5a5: ip64_addrmap_lookup
  0x20a611: ip64_addrmap_lookup_port
  0x20a645: ip64_addrmap_create
  0x20a769: create_msg
  0x20a811: send_request
  0x20a881: msg_for_me
  0x20a8e9: parse_msg
  0x20a9b5: handle_dhcp.isra.0
  0x20ac49: ip64_dhcpc_init
  0x20aca9: ip64_dhcpc_appcall
  0x20acc1: ip64_dhcpc_request
  0x20ace1: process_thread_router_node_process
  0x20ad0d: __aeabi_uldivmod
  0x20ad3d: __udivmoddi4
  0x20b029: __aeabi_idiv0
  0x20b02d: memcmp
  0x20b091: memcpy
  0x20b17d: memmove
  0x20b245: memset
  0x20b2e1: default_handler
  0x20b2e3: nmi_handler
  0x20b2e9: fade
  0x20b341: platform_init_stage_one
  0x20b355: platform_idle
  0x20b359: board_init
  0x20b35b: soc_init
  0x20b37d: clock_isr
  0x20b381: rtimer_arch_init
  0x20b383: uart0_isr
  0x20b389: uart1_isr
  0x20b38f: gpio_port_a_isr
  0x20b395: gpio_port_b_isr
  0x20b39b: gpio_port_c_isr
  0x20b3a1: gpio_port_d_isr
  0x20b3a7: send
  0x20b3b9: int_master_read_and_disable
  0x20b3c1: int_master_status_set
  0x20b3c7: dbg_send_bytes
  0x20b3e7: configure
  0x20b3eb: status
  0x20b3ef: value
  0x20b423: configure
  0x20b427: status
  0x20b42b: value
  0x20b455: stimer_set
  0x20b463: stimer_remaining
  0x20b473: stimer_elapsed
  0x20b481: autostart_start
  0x20b495: energest_init
  0x20b497: etimer_set
  0x20b4a9: etimer_reset
  0x20b4bb: etimer_restart
  0x20b4cd: etimer_expired
  0x20b4d7: call_process
  0x20b4e3: rtimer_init
  0x20b4e7: timer_set
  0x20b4f5: timer_restart
  0x20b501: timer_expired
  0x20b51d: timer_reset
  0x20b531: timer_remaining
  0x20b541: list_init
  0x20b547: list_head
  0x20b54b: list_tail
  0x20b55b: list_remove
  0x20b581: list_add
  0x20b59b: list_push
  0x20b5ab: list_length
  0x20b5b9: list_item_next
  0x20b5bf: memb_init
  0x20b5df: memb_alloc
  0x20b607: memb_free
  0x20b631: memb_inmemb
  0x20b64d: memb_numfree
  0x20b669: ringbuf_init
  0x20b677: ringbuf_put
  0x20b69d: ringbuf_get
  0x20b6bd: button_hal_get_state
  0x20b6e7: item_from_index
  0x20b6fb: index_from_item
  0x20b711: nbr_set_bit
  0x20b749: nbr_table_gc_get_worst
  0x20b767: nbr_table_get_from_lladdr
  0x20b78d: linkaddr_copy
  0x20b793: linkaddr_cmp
  0x20b7a3: link_stats_is_fresh
  0x20b7c7: guess_etx_from_rssi
  0x20b80d: output
  0x20b819: writereg
  0x20b83d: readdata
  0x20b869: readdatabyte
  0x20b87f: readreg
  0x20b8a9: setregbitfield
  0x20b8e9: enc28j60_send
  0x20b8ed: write_str
  0x20b8fd: buffer_str
  0x20b925: snprintf
  0x20b93f: putchar
  0x20b94b: init
  0x20b94f: uipbuf_set_len_field
  0x20b957: uipbuf_get_len_field
  0x20b963: uipbuf_get_next_header
  0x20b9b7: uipbuf_get_last_header
  0x20b9e3: uip_ds6_list_loop
  0x20ba33: uip_ds6_maddr_rm
  0x20ba3b: uip_ds6_set_addr_iid
  0x20ba51: get_match_length
  0x20ba8f: ip64_addr_copy4
  0x20ba95: ip64_addr_copy6
  0x20ba9b: ip64_addr_6to4
  0x20babb: uip_ds6_route_next
  0x20bac3: rm_routelist_callback
  0x20bac7: uip_ds6_nbr_lookup
  0x20baf3: uip_ds6_nbr_update_ll
  0x20bb51: uip_ds6_nbr_ipaddr_from_lladdr
  0x20bb55: uip_ds6_link_callback
  0x20bb57: uip_ds6_nbr_refresh_reachable_state
  0x20bb77: uip_icmp6chksum
  0x20bb7d: uip_htons
  0x20bb83: uip_htonl
  0x20bb95: ip64_dns64_6to4
  0x20bbe1: ip64_dns64_4to6
  0x20bdd7: ip64_dhcpc_unconfigured
  0x20bdd9: init
  0x20bddb: chksum
  0x20be13: ipv6_transport_checksum
  0x20be4d: ipv4_transport_checksum
  0x20be85: ip64_special_ports_translate_incoming
  0x20be89: ip64_special_ports_translate_outgoing
  0x20be8d: ip64_special_ports_incoming_is_special
  0x20be91: ip64_special_ports_outgoing_is_special
  0x20be95: ip64_addrmap_set_lifetime
  0x20be9f: ip64_addrmap_set_recycleble
  0x20beaf: root_set_prefix
  0x20beb1: get_sr_node_ipaddr
  0x20beb5: leave_network
  0x20beb7: ext_header_update
  0x20bebb: ext_header_hbh_update
  0x20bebf: ext_header_srh_update
  0x20bec3: ext_header_srh_get_next_hop
  0x20bec7: link_callback
  0x20bec9: drop_route
  0x20becb: is_in_leaf_mode
  0x20becf: ext_header_remove
  0x20bed3: get_root_ipaddr
  0x20bed7: node_has_joined
  0x20bedb: node_is_reachable
  0x20bedf: global_repair
  0x20bee1: local_repair
  0x20bee3: neighbor_state_changed
  0x20bee5: root_start
  0x20bee9: node_is_root
  0x20beed: init
  0x20bef0: uart_regs
  0x20bf48: cc2538_rf_driver
  0x20bf80: output_power
  0x20bff0: cc2538_temp_sensor
  0x20c000: vdd3_sensor
  0x20c010: enc28j60_ip64_driver
  0x20c018: nullmac_driver
  0x20c034: sicslowpan_driver
  0x20c044: ip64_eth_interface
  0x20c04c: ip64_uip_fallback_interface
  0x20c054: nullrouting_driver
  0x20c0a8: autostart_processes
  0x20c0b0: linkaddr_null
  0x20c0f0: leds_arch_leds
  0x20c384: buffer.5659
  0x20c394: buffer.5668
  0x20c3f0: llprefix
  0x20c3f2: unc_llconf
  0x20c3f6: unc_mxconf
  0x20c405: ttl_values
  0x20c409: unc_ctxconf
  0x20c435: broadcast_ethaddr
  0x20c45c: magic_cookie
  0x20c478: _ldata
  0x27ffd4: flash_cca_lock_page
  0x20000000: _enrdata
  0x20004000: channel_config
  0x20004040: _data
  0x20004090: button_hal_buttons
  0x20004098: sensors
  0x200040a4: cc2538_rf_process
  0x200040b4: curr_log_level_main
  0x200040b8: etimer_process
  0x200040c8: ctimer_process
  0x200040d8: stack_check_process
  0x200040e8: sensors_process
  0x200040f8: button_hal_process
  0x20004108: serial_line_process
  0x20004118: bufmem
  0x20004124: buframmem
  0x20004130: neighbor_addr_mem
  0x2000413c: link_stats_struct
  0x2000414c: enc28j60_ip64_driver_process
  0x2000415c: ctxt
  0x20004164: echo_request_handler
  0x20004170: echo_reply_handler
  0x2000417c: defaultroutermemb
  0x20004188: nbr_routes_struct
  0x20004198: nbr_routes
  0x2000419c: routememb
  0x200041a8: neighborroutememb
  0x200041b4: ds6_neighbors_struct
  0x200041c4: tcpip_process
  0x200041d4: rs_input_handler
  0x200041e0: ns_input_handler
  0x200041ec: na_input_handler
  0x200041f8: ip64_ipv4_dhcp_process
  0x20004208: ip64_packet_buffer
  0x2000420c: entrymemb
  0x20004218: router_node_process
  0x20004228: ip64_prefix
  0x20004238: ip64_packet_buffer_maxlen
  0x2000423a: mapped_port
  0x2000423c: send_on_cca
  0x2000423d: rf_channel
  0x2000423e: ip64_prefix_len
  0x2000423f: _edata
  0x20004240: _bss
  0x20004248: rt_ticks_epoch
  0x20004250: next_trigger
  0x20004254: input_handler
  0x2000425c: ioc_sel
  0x20004260: ioc_over
  0x20004264: notification_process
  0x20004268: prev_MDMTEST1
  0x2000426c: prev_FRMCTRL0
  0x20004270: periph_permit_pm1_funcs
  0x20004284: notification_process
  0x20004288: timerlist
  0x2000428c: next_expiration
  0x20004290: ctimer_list_list
  0x20004294: process_current
  0x20004298: process_list
  0x2000429c: events
  0x2000441c: next_rtimer
  0x20004420: et.5998
  0x20004430: i.5642
  0x20004434: events.5643
  0x20004438: pmask
  0x2000443c: button_event_handlers
  0x20004448: rxbuf
  0x20004450: ptr.5627
  0x20004454: handlers_list
  0x20004458: bufmem_memb_mem
  0x20004478: nbr_table_keys_list
  0x2000447c: neighbor_addr_mem_memb_mem
  0x2000453c: all_tables
  0x2000455c: num_tables
  0x20004560: packetbuf_aligned
  0x200045e0: ip_processor_list_list
  0x200045e4: _link_stats_mem
  0x200046a4: e.6009
  0x200046b4: received_packets
  0x200046b8: echo_reply_callback_list_list
  0x200046bc: input_handler_list_list
  0x200046c0: locmaddr
  0x200046c4: locprefix
  0x200046c8: locaddr
  0x200046cc: defaultroutermemb_memb_mem
  0x2000470c: num_routes
  0x20004710: defaultrouterlist_list
  0x20004714: _nbr_routes_mem
  0x20004794: routelist_list
  0x20004798: routememb_memb_mem
  0x20004a18: neighborroutememb_memb_mem
  0x20004a98: notificationlist_list
  0x20004a9c: _ds6_neighbors_mem
  0x20004d1c: s
  0x20004dc0: periodic
  0x20004dd0: serverlifetime
  0x20004dd4: prefix
  0x20004dd8: nbr
  0x20004ddc: nd6_opt_llao
  0x20004de0: addr
  0x20004de4: callback
  0x20004de8: context
  0x20004dec: last_rssi
  0x20004df0: packetbuf_ptr
  0x20004df4: iphc_ptr
  0x20004df8: last_tx_status
  0x20004dfc: packetbuf_payload_len
  0x20004e00: mac_max_payload
  0x20004e04: frag_info
  0x20004f74: entrymemb_memb_mem
  0x20005574: entrylist_list
  0x20005578: s
  0x200055e4: xid
  0x200055e8: node_id
  0x200055ea: buframmem_memb_mem
  0x20005b4a: buflen
  0x20005b4c: bufptr
  0x20005b4e: uipbuf_attrs
  0x20005b5e: uipbuf_default_attrs
  0x20005b6e: tmp_ipaddr
  0x20005b7e: default_prefix
  0x20005b8e: loc_fipaddr
  0x20005b9e: rand_time
  0x20005ba0: uip_ext_len
  0x20005ba2: lastport
  0x20005ba4: serveraddr
  0x20005bb4: nd6_opt_offset
  0x20005bb6: my_tag
  0x20005bb8: arp_table
  0x20005c18: ip64_draddr
  0x20005c1c: ipid
  0x20005c1e: ip64_hostaddr
  0x20005c22: ip64_netmask
  0x20005c26: ipv6_local_address
  0x20005c36: ipv4_broadcast_addr
  0x20005c3a: was_on
  0x20005c3b: poll_mode
  0x20005c3c: rf_flags
  0x20005c3d: max_pm
  0x20005c3e: debug_frame.5606
  0x20005c3f: initialized
  0x20005c40: fevent
  0x20005c41: nevents
  0x20005c42: poll_requested
  0x20005c43: lastevent
  0x20005c44: num_sensors
  0x20005c45: rxbuf_data
  0x20005cc5: overflow.5620
  0x20005cc6: buf.5626
  0x20005d46: buframmem_memb_used
  0x20005d4e: bufmem_memb_used
  0x20005d56: locked_map
  0x20005d66: neighbor_addr_mem_memb_used
  0x20005d76: used_map
  0x20005d86: hdrlen
  0x20005d87: enc_mac_addr
  0x20005d8d: initialized
  0x20005d8e: bank
  0x20005d8f: racount
  0x20005d90: routememb_memb_used
  0x20005da0: neighborroutememb_memb_used
  0x20005db0: defaultroutermemb_memb_used
  0x20005db2: uip_ext_bitmap
  0x20005db3: iss
  0x20005db7: uip_last_proto
  0x20005db8: curr_page
  0x20005db9: uncomp_hdr_len
  0x20005dba: addr_contexts
  0x20005dc4: frag_buf
  0x20006310: packetbuf_hdr_len
  0x20006311: arptime
  0x20006312: tmpage
  0x20006313: ip64_hostaddr_configured
  0x20006314: entrymemb_memb_used
  0x20006334: periodic_timer
  0x20006354: uip_ds6_timer_ra
  0x2000635c: uip_ds6_if
  0x20006478: uip_ds6_netif_addr_list_offset
  0x20006479: uip_ds6_addr_size
  0x2000647c: uip_ds6_prefix_list
  0x200064dc: uip_ds6_timer_periodic
  0x200064ec: uip_len
  0x200064f0: uip_sappdata
  0x200064f4: uip_acc32
  0x200064f8: uip_lladdr
  0x20006500: uip_aligned_buf
  0x20006a00: uip_flags
  0x20006a04: uip_udp_conn
  0x20006a08: uip_appdata
  0x20006a0c: uip_conn
  0x20006a10: uip_conns
  0x20006b90: uip_listenports
  0x20006bb8: uip_slen
  0x20006bbc: uip_udp_conns
  0x20006cbc: ip64_packet_buffer_aligned
  0x200071bc: packetbuf_addrs
  0x200071cc: packetbuf_attrs
  0x200071e6: linkaddr_node_addr
  0x200071ee: uip_all_zeroes_addr
  0x200071fe: uip_hostaddr
  0x2000720e: sensors_flags
  0x20007211: sensors_event
  0x20007212: button_hal_release_event
  0x20007213: button_hal_periodic_event
  0x20007214: button_hal_press_event
  0x20007215: serial_line_event_message
  0x20007216: tcpip_event
  0x20007217: ip64_eth_addr
  0x2000721d: _stack
  0x20007220: stack
  0x20007a20: _heap
  0x20008000: _eheap
