board:
  init_nsvtor: 0x202000

interrupt:
  mode: round-robin
  trigger:
    on-infinite-sleep: true
    interval: 1000

memory_maps:
  - name: mmio
    address: 0x40000000
    size: 0x20000000
    type: mmio
  - name: ram
    address: 0x20000000
    size: 0x100000
    type: ram
  - name: text
    address: 0x202000
    size: 0x8e000
    file:
      path: ip64-router.bin
    type: rom

symbols:
  - ip64-router.elf
