interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x202000
    file: contiki-hello-4-8X.bin
    ivt_offset: 0x0
    permissions: r-x
    size: 0x8e000
symbols:
  0x0: smartrf-sensors.c
  0x202000: vectors
  0x20228d: reset_handler
  0x2022cd: platform_init_stage_two
  0x202319: platform_init_stage_three
  0x2023a5: process_thread_sensors_process
  0x202481: value
  0x2024a5: configure
  0x2024f9: soc_get_rev
  0x202511: soc_print_info
  0x202521: update_ticks
  0x20256d: clock_init
  0x2025b9: clock_time
  0x2025cd: clock_seconds
  0x2025e1: clock_delay_usec
  0x2025fd: clock_adjust
  0x20261d: rtimer_arch_next_trigger
  0x202629: rtimer_arch_now
  0x202655: rtimer_arch_schedule
  0x2026ad: rtimer_isr
  0x2026e1: permit_pm1
  0x202705: uart_isr
  0x202769: uart_init
  0x202911: uart_set_input
  0x202921: uart_write_byte
  0x20293d: watchdog_init
  0x202949: watchdog_start
  0x202955: watchdog_periodic
  0x202965: nvic_init
  0x202975: sys_ctrl_init
  0x2029e9: gpio_port_isr
  0x202a35: ioc_init
  0x202a51: ioc_set_over
  0x202a65: ioc_set_sel
  0x202a79: adc_init
  0x202a89: adc_get
  0x202b01: permit_pm1
  0x202b11: crypto_isr
  0x202b41: crypto_enable
  0x202b61: crypto_init
  0x202b9d: crypto_disable
  0x202bbd: gpio_hal_arch_no_port_pin_cfg_set
  0x202c9d: "on"
  0x202cc5: "off"
  0x202d05: set_channel
  0x202d3d: channel_clear
  0x202d79: receiving_packet
  0x202d91: pending_packet
  0x202da1: get_value
  0x202f1d: set_object
  0x202f4d: read
  0x20302d: prepare
  0x203095: get_object
  0x2031d9: transmit
  0x20327d: set_poll_mode
  0x203321: init
  0x203409: process_thread_cc2538_rf_process
  0x203499: set_value
  0x203629: cc2538_rf_rx_tx_isr
  0x20364d: cc2538_rf_err_isr
  0x203675: udma_init
  0x2036a9: udma_set_channel_src
  0x2036b9: udma_set_channel_dst
  0x2036cd: udma_set_channel_control_word
  0x2036e1: udma_channel_enable
  0x2036f9: udma_channel_mask_set
  0x203711: udma_channel_sw_request
  0x203729: udma_channel_get_mode
  0x203745: udma_isr
  0x203755: udma_err_isr
  0x203761: select_32_mhz_xosc
  0x203791: lpm_exit
  0x2037c5: lpm_enter
  0x20387d: lpm_register_peripheral
  0x2038a1: lpm_init
  0x2038c5: pka_isr
  0x2038f5: ieee_addr_cpy_to
  0x203955: main
  0x203b41: stimer_expired
  0x203b61: log_6addr
  0x203b81: log_lladdr
  0x203bbd: update_time
  0x203c01: etimer_request_poll
  0x203c0d: process_thread_etimer_process
  0x203cb9: add_timer
  0x203cf9: etimer_pending
  0x203d09: etimer_stop
  0x203d3d: node_id_init
  0x203d55: process_thread_ctimer_process
  0x203dd5: ctimer_init
  0x203dfd: ctimer_set_with_process
  0x203e41: ctimer_set
  0x203e55: ctimer_reset
  0x203e8d: ctimer_stop
  0x203eb9: ctimer_expired
  0x203eed: rtimer_run_next
  0x203f15: call_process.part.0
  0x203f4d: exit_process
  0x203fcd: do_poll
  0x204001: process_alloc_event
  0x204011: process_exit
  0x20401d: process_init
  0x20404d: process_run
  0x2040d1: process_nevents
  0x2040e5: process_post
  0x204121: process_post_synch
  0x204135: process_start
  0x204165: process_poll
  0x20417d: stack_check_init
  0x2041a5: stack_check_get_usage
  0x2041e5: process_thread_stack_check_process
  0x204291: random_rand
  0x2042b1: random_init
  0x20432d: duration_exceeded_callback
  0x204361: process_thread_button_hal_process
  0x2043d5: press_release_handler
  0x2043ed: debounce_handler
  0x204451: button_hal_init
  0x204545: process_thread_serial_line_process
  0x2045e5: serial_line_input_byte
  0x204629: serial_line_init
  0x20464d: leds_on
  0x2046ad: leds_off
  0x2046f5: leds_init
  0x204739: gpio_hal_register_handler
  0x204745: gpio_hal_event_handler
  0x204769: gpio_hal_init
  0x204775: queuebuf_init
  0x204791: queuebuf_numfree
  0x20479d: queuebuf_new_from_packetbuf
  0x2047e1: queuebuf_free
  0x20480d: queuebuf_to_packetbuf
  0x20483d: index_from_key
  0x20485d: index_from_lladdr
  0x20489d: nbr_get_bit.constprop.3
  0x2048c9: remove_key
  0x204951: nbr_table_is_registered
  0x204971: nbr_table_register
  0x2049a1: nbr_table_next
  0x2049e9: nbr_table_head
  0x204a21: entry_is_allowed.isra.2
  0x204a91: nbr_table_add_lladdr
  0x204b41: nbr_table_remove
  0x204b6d: nbr_table_lock
  0x204b7d: nbr_table_unlock
  0x204b8d: nbr_table_get_lladdr
  0x204bb1: packetbuf_set_datalen
  0x204bbd: packetbuf_hdrptr
  0x204bc5: packetbuf_datalen
  0x204bd1: packetbuf_hdrlen
  0x204be9: packetbuf_dataptr
  0x204bf9: packetbuf_copyto
  0x204c3d: packetbuf_totlen
  0x204c51: packetbuf_hdralloc
  0x204c91: packetbuf_attr_clear
  0x204cc5: packetbuf_clear
  0x204ce5: packetbuf_copyfrom
  0x204d11: packetbuf_attr_copyto
  0x204d35: packetbuf_attr_copyfrom
  0x204d59: packetbuf_set_attr
  0x204d69: packetbuf_attr
  0x204d75: packetbuf_set_addr
  0x204d8d: packetbuf_addr
  0x204d9d: netstack_process_ip_callback
  0x204ddd: netstack_init
  0x204e01: periodic
  0x204e2d: link_stats_from_lladdr
  0x204e39: link_stats_packet_sent
  0x204ebd: link_stats_input_callback
  0x204f21: link_stats_reset
  0x204f45: link_stats_init
  0x204f6d: fill_space
  0x204fa1: format_str_v
  0x205675: printf
  0x205695: vsnprintf
  0x2056bd: process_thread_ble_l2cap_tx_process
  0x20581d: get_channel_for_addr
  0x205865: "off"
  0x205875: "on"
  0x205889: send
  0x205955: init
  0x205ab5: input_l2cap_conn_req
  0x205bf1: input
  0x205df9: uipbuf_add_ext_hdr
  0x205e29: uipbuf_set_len
  0x205e3d: uipbuf_get_attr
  0x205e51: uipbuf_set_attr
  0x205e65: uipbuf_clear_attr
  0x205e79: uipbuf_clear
  0x205e99: uipbuf_init
  0x205eb9: echo_reply_input
  0x205f25: echo_request_input
  0x205fbd: uip_icmp6_input
  0x205ff5: uip_icmp6_register_input_handler
  0x206001: uip_icmp6_error_output
  0x206145: uip_icmp6_send
  0x2061c9: uip_icmp6_init
  0x2061e5: node_matches_address.part.0
  0x20620d: uip_sr_get_node
  0x206241: uip_sr_is_addr_reachable
  0x206285: uip_sr_update_node
  0x206329: uip_sr_init
  0x20634d: uip_sr_periodic
  0x2063b5: uip_sr_free_all
  0x2063f5: uip_ds6_default_prefix
  0x2063fd: uip_ds6_prefix_add
  0x206461: uip_ds6_is_addr_onlink
  0x2064a1: uip_ds6_addr_lookup
  0x2064cd: uip_ds6_get_link_local
  0x20650d: uip_ds6_maddr_add
  0x206559: uip_ds6_addr_add
  0x2065ed: uip_ds6_maddr_lookup
  0x206619: uip_ds6_addr_rm
  0x20665d: uip_ds6_periodic
  0x2066a9: uip_ds6_select_src
  0x20673d: uip_ds6_compute_reachable_time
  0x206769: uip_ds6_init
  0x206885: uiplib_ipaddr_snprint
  0x206975: uip_ds6_route_init
  0x206991: uip_ds6_defrt_rm
  0x2069c9: uip_ds6_defrt_lookup
  0x2069fd: uip_ds6_defrt_add
  0x206a5d: uip_ds6_defrt_choose
  0x206a8d: uip_ds6_defrt_periodic
  0x206abd: uip_ds6_nbr_rm
  0x206ae1: uip_ds6_neighbors_init
  0x206afd: uip_ds6_nbr_add
  0x206b3d: uip_ds6_nbr_get_ll
  0x206b49: uip_ds6_nbr_head
  0x206b55: uip_ds6_nbr_next
  0x206b61: uip_ds6_nbr_ll_lookup
  0x206b6d: tcpip_output
  0x206b99: tcpip_input
  0x206bbd: tcpip_ipv6_output
  0x206ca1: packet_input
  0x206cc1: process_thread_tcpip_process
  0x206d7d: tcpip_uipcall
  0x206da9: upper_layer_chksum
  0x206dfd: ext_hdr_options_process
  0x206e79: uip_update_ttl
  0x206e9d: uip_init
  0x206ed5: uip_remove_ext_hdr
  0x206f3d: uip_process
  0x207399: ns_input
  0x207611: uip_nd6_init
  0x20761d: clear_fragments
  0x207659: sicslowpan_init
  0x207671: set_packet_attrs
  0x2076c9: compress_addr_64
  0x207759: addr_context_lookup_by_prefix
  0x20777d: send_packet
  0x2077a1: fragment_copy_payload_and_send
  0x20780d: output
  0x207f8d: packet_sent
  0x207fe9: store_fragment
  0x208045: uncompress_addr
  0x2080d5: add_fragment
  0x2081f5: input
  0x208a89: get_rank
  0x208aa9: remove_neighbor
  0x208ae5: rpl_neighbor_get_from_lladdr
  0x208af5: rpl_neighbor_rank_via_nbr
  0x208b0d: rpl_neighbor_get_lladdr
  0x208b1d: best_parent
  0x208bb1: rpl_neighbor_set_preferred_parent
  0x208bf9: rpl_neighbor_remove_all
  0x208c29: rpl_neighbor_get_from_ipaddr
  0x208c45: rpl_neighbor_select_best
  0x208c99: rpl_neighbor_init
  0x208cad: new_dio_interval
  0x208d05: schedule_dao_retransmission
  0x208d35: handle_unicast_dio_timer
  0x208d51: send_new_dao
  0x208d85: resend_dao
  0x208dbd: handle_dao_ack_timer
  0x208dd1: handle_leaving_timer
  0x208de1: handle_dio_timer
  0x208e51: rpl_timers_schedule_periodic_dis
  0x208e89: handle_dis_timer
  0x208ebd: handle_periodic_timer
  0x208f05: rpl_timers_dio_reset
  0x208f39: rpl_timers_schedule_unicast_dio
  0x208f61: rpl_timers_schedule_dao
  0x208f95: rpl_timers_schedule_dao_ack
  0x208fdd: rpl_timers_notify_dao_ack
  0x209029: get_probing_target
  0x2090e9: rpl_schedule_probing
  0x209111: rpl_schedule_probing_now
  0x20913d: rpl_timers_unschedule_leaving
  0x209161: rpl_timers_schedule_leaving
  0x209191: rpl_timers_init
  0x2091b1: rpl_timers_stop_dag_timers
  0x2091f5: rpl_timers_unschedule_state_update
  0x209209: rpl_timers_schedule_state_update
  0x209225: update_hbh_header
  0x209271: rpl_ext_header_srh_get_next_hop
  0x2092f5: rpl_ext_header_srh_update
  0x2093ad: rpl_ext_header_hbh_update
  0x20943d: rpl_ext_header_remove
  0x2094ed: rpl_ext_header_update
  0x209745: rpl_has_joined
  0x20975d: rpl_is_reachable
  0x209775: rpl_get_leaf_only
  0x209781: get_sr_node_ipaddr
  0x2097ad: set_ip_from_prefix
  0x2097d9: init
  0x209819: rpl_link_callback
  0x209845: rpl_get_global_address
  0x2098a9: rpl_reset_prefix
  0x2098d1: rpl_set_prefix_from_addr
  0x209941: update_metric_container
  0x20994d: within_hysteresis
  0x209985: rank_via_nbr
  0x2099b5: best_parent
  0x209a25: dao_ack_input
  0x209a5d: dao_input
  0x209b5d: dio_input
  0x209d71: dis_input
  0x209d9d: rpl_icmp6_dis_output
  0x209dd5: rpl_icmp6_dio_output
  0x209f95: rpl_icmp6_dao_output
  0x20a059: rpl_icmp6_dao_ack_output
  0x20a09d: rpl_icmp6_init
  0x20a0cd: init_dag
  0x20a145: process_dio_init_dag
  0x20a1e9: rpl_dag_get_root_ipaddr
  0x20a219: rpl_dag_leave
  0x20a26d: rpl_dag_poison_and_leave
  0x20a27d: rpl_dag_periodic
  0x20a2c5: rpl_is_addr_in_our_dag
  0x20a2ed: rpl_local_repair
  0x20a321: rpl_global_repair
  0x20a359: rpl_dag_ready_to_advertise
  0x20a37d: rpl_dag_update_state
  0x20a4ad: rpl_process_dio
  0x20a625: rpl_process_dis
  0x20a651: rpl_process_dao
  0x20a69d: rpl_process_dao_ack
  0x20a6f1: rpl_dag_init_root
  0x20a799: rpl_dag_init
  0x20a7a9: rpl_dag_root_set_prefix
  0x20a811: rpl_dag_root_start
  0x20a879: rpl_dag_root_is_root
  0x20a891: process_thread_hello_world_process
  0x20a8d9: __aeabi_uldivmod
  0x20a909: __udivmoddi4
  0x20abf5: __aeabi_idiv0
  0x20abf9: memcmp
  0x20ac5d: memcpy
  0x20ad49: memmove
  0x20ae11: memset
  0x20aead: strlen
  0x20af09: default_handler
  0x20af0b: nmi_handler
  0x20af11: fade
  0x20af69: platform_init_stage_one
  0x20af7d: platform_idle
  0x20af81: status
  0x20af85: soc_init
  0x20afa7: clock_isr
  0x20afab: rtimer_arch_init
  0x20afad: uart0_isr
  0x20afb3: uart1_isr
  0x20afb9: gpio_port_a_isr
  0x20afbf: gpio_port_b_isr
  0x20afc5: gpio_port_c_isr
  0x20afcb: gpio_port_d_isr
  0x20afd1: send
  0x20afe3: int_master_read_and_disable
  0x20afeb: int_master_status_set
  0x20aff1: dbg_putchar
  0x20b001: dbg_send_bytes
  0x20b021: configure
  0x20b025: status
  0x20b029: value
  0x20b05d: configure
  0x20b061: status
  0x20b065: value
  0x20b08f: autostart_start
  0x20b0a3: stimer_set
  0x20b0b1: energest_init
  0x20b0b3: etimer_set
  0x20b0c5: etimer_reset
  0x20b0d7: etimer_expired
  0x20b0e1: rtimer_init
  0x20b0e5: call_process
  0x20b0f1: timer_set
  0x20b0ff: timer_expired
  0x20b11b: timer_reset
  0x20b12f: ringbuf_init
  0x20b13d: ringbuf_put
  0x20b163: ringbuf_get
  0x20b183: list_init
  0x20b189: list_head
  0x20b18d: list_tail
  0x20b19d: list_remove
  0x20b1c3: list_add
  0x20b1dd: list_push
  0x20b1ed: list_item_next
  0x20b1f3: memb_init
  0x20b213: memb_alloc
  0x20b23b: memb_free
  0x20b265: memb_inmemb
  0x20b281: memb_numfree
  0x20b29d: button_hal_get_state
  0x20b2c7: item_from_index
  0x20b2db: index_from_item
  0x20b2f1: nbr_set_bit
  0x20b329: nbr_table_get_from_lladdr
  0x20b34f: linkaddr_copy
  0x20b355: linkaddr_cmp
  0x20b365: link_stats_is_fresh
  0x20b389: guess_etx_from_rssi
  0x20b3cf: mac_call_sent_callback
  0x20b3e7: write_str
  0x20b3f7: buffer_str
  0x20b41f: snprintf
  0x20b439: putchar
  0x20b445: max_payload
  0x20b44b: input_l2cap_connection_udate_resp
  0x20b46f: input_l2cap_credit
  0x20b4b7: uipbuf_set_len_field
  0x20b4bf: uipbuf_get_len_field
  0x20b4cb: uipbuf_get_next_header
  0x20b51f: uipbuf_get_last_header
  0x20b54b: uipbuf_search_header
  0x20b58b: uip_sr_expire_parent
  0x20b5b9: uip_ds6_list_loop
  0x20b609: uip_ds6_maddr_rm
  0x20b611: uip_ds6_set_addr_iid
  0x20b627: uip_ds6_set_lladdr_from_iid
  0x20b63d: get_match_length
  0x20b67b: uip_ds6_route_nexthop
  0x20b67f: uip_ds6_route_lookup
  0x20b683: uip_ds6_route_rm
  0x20b685: uip_ds6_nbr_lookup
  0x20b6b1: uip_ds6_nbr_update_ll
  0x20b70f: uip_ds6_nbr_ipaddr_from_lladdr
  0x20b713: uip_ds6_nbr_lladdr_from_ipaddr
  0x20b725: uip_ds6_link_callback
  0x20b727: chksum
  0x20b75f: uip_icmp6chksum
  0x20b765: uip_udpchksum
  0x20b76b: uip_htonl
  0x20b77d: rpl_nbr_gc_get_worst
  0x20b79b: rpl_neighbor_get_ipaddr
  0x20b7a9: rpl_neighbor_get_link_stats
  0x20b7b7: rpl_neighbor_is_fresh
  0x20b7c5: handle_state_update
  0x20b7c9: get_probing_delay
  0x20b7e3: handle_probing_timer
  0x20b807: drop_route
  0x20b809: neighbor_state_changed
  0x20b80b: rpl_lollipop_greater_than
  0x20b83f: reset
  0x20b841: nbr_link_metric
  0x20b853: nbr_has_usable_link
  0x20b865: nbr_path_cost
  0x20b88d: nbr_is_acceptable_parent
  0x20b8ab: get32
  0x20b8c3: set32
  0x20b8d5: get16
  0x20b8e1: set16
  0x20b8eb: rpl_icmp6_update_nbr_table
  0x20b919: rpl_process_hbh
  0x20b934: als_sensor
  0x20b944: uart_regs
  0x20b99c: cc2538_rf_driver
  0x20b9d4: output_power
  0x20ba44: cc2538_temp_sensor
  0x20ba54: vdd3_sensor
  0x20ba64: ble_l2cap_driver
  0x20ba80: sicslowpan_driver
  0x20ba90: rpl_lite_driver
  0x20bae4: autostart_processes
  0x20baec: linkaddr_null
  0x20baf4: leds_arch_leds
  0x20bdac: buffer.5647
  0x20bdbc: buffer.5656
  0x20be67: llprefix
  0x20be69: unc_llconf
  0x20be6d: unc_mxconf
  0x20be7c: ttl_values
  0x20be80: unc_ctxconf
  0x20bf92: _etext
  0x20bf94: _ldata
  0x27ffd4: flash_cca_lock_page
  0x20000000: _enrdata
  0x20000040: _data
  0x20000050: sensors
  0x20000060: key_up
  0x200000b0: key_left
  0x20000100: key_select
  0x20000150: key_right
  0x200001a0: key_down
  0x200001f0: button_hal_buttons
  0x20000208: cc2538_rf_process
  0x20000218: curr_log_level_main
  0x2000021c: etimer_process
  0x2000022c: ctimer_process
  0x2000023c: stack_check_process
  0x2000024c: button_hal_process
  0x2000025c: serial_line_process
  0x2000026c: bufmem
  0x20000278: buframmem
  0x20000284: neighbor_addr_mem
  0x20000290: link_stats_struct
  0x200002a0: ctxt
  0x200002a8: ble_l2cap_tx_process
  0x200002b8: echo_request_handler
  0x200002c4: echo_reply_handler
  0x200002d0: nodememb
  0x200002dc: defaultroutermemb
  0x200002e8: ds6_neighbors_struct
  0x200002f8: tcpip_process
  0x20000308: ns_input_handler
  0x20000314: rpl_neighbors
  0x20000318: rpl_neighbors_struct
  0x20000328: rpl_mrhof
  0x2000034c: dao_ack_handler
  0x20000358: dis_handler
  0x20000364: dao_handler
  0x20000370: dio_handler
  0x2000037c: hello_world_process
  0x2000038c: send_on_cca
  0x2000038d: rf_channel
  0x2000038e: _edata
  0x20000390: _bss
  0x20000398: rt_ticks_epoch
  0x200003a0: events.5631
  0x200003a4: i.5630
  0x200003a8: next_trigger
  0x200003ac: input_handler
  0x200003b4: ioc_sel
  0x200003b8: ioc_over
  0x200003bc: notification_process
  0x200003c0: prev_MDMTEST1
  0x200003c4: prev_FRMCTRL0
  0x200003c8: periph_permit_pm1_funcs
  0x200003dc: notification_process
  0x200003e0: timerlist
  0x200003e4: next_expiration
  0x200003e8: ctimer_list_list
  0x200003ec: next_rtimer
  0x200003f0: process_current
  0x200003f4: process_list
  0x200003f8: events
  0x20000578: et.5974
  0x20000588: pmask
  0x2000058c: button_event_handlers
  0x20000598: rxbuf
  0x200005a0: ptr.5615
  0x200005a4: handlers_list
  0x200005a8: bufmem_memb_mem
  0x200005c8: nbr_table_keys_list
  0x200005cc: neighbor_addr_mem_memb_mem
  0x2000068c: all_tables
  0x200006ac: num_tables
  0x200006b0: packetbuf_aligned
  0x20000730: ip_processor_list_list
  0x20000734: _link_stats_mem
  0x200007f4: echo_reply_callback_list_list
  0x200007f8: input_handler_list_list
  0x200007fc: num_nodes
  0x20000800: nodememb_memb_mem
  0x20000980: nodelist_list
  0x20000984: locmaddr
  0x20000988: locprefix
  0x2000098c: locaddr
  0x20000990: defaultroutermemb_memb_mem
  0x200009d0: defaultrouterlist_list
  0x200009d4: periodic
  0x200009e4: nbr
  0x200009e8: nd6_opt_llao
  0x200009ec: addr
  0x200009f0: callback
  0x200009f4: context
  0x200009f8: last_rssi
  0x200009fc: packetbuf_ptr
  0x20000a00: iphc_ptr
  0x20000a04: last_tx_status
  0x20000a08: packetbuf_payload_len
  0x20000a0c: mac_max_payload
  0x20000a10: frag_info
  0x20000b80: _rpl_neighbors_mem
  0x20000c00: periodic_timer
  0x20000c20: dis_timer
  0x20000c40: timer.5584
  0x20000c50: node_id
  0x20000c52: buframmem_memb_mem
  0x200011b2: buflen
  0x200011b4: bufptr
  0x200011b6: l2cap_channels
  0x20001bd6: uipbuf_attrs
  0x20001be6: uipbuf_default_attrs
  0x20001bf6: tmp_ipaddr
  0x20001c06: default_prefix
  0x20001c16: loc_fipaddr
  0x20001c26: _ds6_neighbors_mem
  0x20001d46: uip_ext_len
  0x20001d48: lastport
  0x20001d4a: nd6_opt_offset
  0x20001d4c: my_tag
  0x20001d4e: root_ipaddr.7245
  0x20001d5e: num_sensors
  0x20001d5f: crc_corr
  0x20001d60: was_on
  0x20001d61: rssi
  0x20001d62: poll_mode
  0x20001d63: rf_flags
  0x20001d64: max_pm
  0x20001d65: initialized
  0x20001d66: fevent
  0x20001d67: nevents
  0x20001d68: poll_requested
  0x20001d69: lastevent
  0x20001d6a: rxbuf_data
  0x20001dea: overflow.5608
  0x20001deb: buf.5614
  0x20001e6b: buframmem_memb_used
  0x20001e73: bufmem_memb_used
  0x20001e7b: locked_map
  0x20001e8b: neighbor_addr_mem_memb_used
  0x20001e9b: used_map
  0x20001eab: hdrlen
  0x20001eac: l2cap_channel_count
  0x20001ead: l2cap_tx_event
  0x20001eae: ble_addr
  0x20001eb4: nodememb_memb_used
  0x20001ec4: defaultroutermemb_memb_used
  0x20001ec6: uip_ext_bitmap
  0x20001ec7: uip_last_proto
  0x20001ec8: curr_page
  0x20001ec9: uncomp_hdr_len
  0x20001eca: addr_contexts
  0x20001ed4: frag_buf
  0x20002420: packetbuf_hdr_len
  0x20002421: rpl_leaf_only
  0x20002422: initialized.7256
  0x20002424: periodic_timer
  0x20002444: uip_ds6_timer_ra
  0x2000244c: uip_ds6_if
  0x20002568: uip_ds6_netif_addr_list_offset
  0x20002569: uip_ds6_addr_size
  0x2000256c: uip_ds6_prefix_list
  0x200025cc: uip_ds6_timer_periodic
  0x200025dc: uip_len
  0x200025e0: uip_sappdata
  0x200025e4: uip_lladdr
  0x200025ec: uip_aligned_buf
  0x20002aec: uip_flags
  0x20002af0: uip_udp_conn
  0x20002af4: uip_appdata
  0x20002af8: uip_conn
  0x20002afc: uip_slen
  0x20002b00: uip_udp_conns
  0x20002c00: curr_instance
  0x20002d60: packetbuf_addrs
  0x20002d70: packetbuf_attrs
  0x20002d8a: linkaddr_node_addr
  0x20002d92: rpl_multicast_addr
  0x20002da2: sensors_event
  0x20002da3: sensors_flags
  0x20002da7: button_hal_release_event
  0x20002da8: button_hal_periodic_event
  0x20002da9: button_hal_press_event
  0x20002daa: serial_line_event_message
  0x20002dab: tcpip_event
  0x20002dac: _stack
  0x20002db0: stack
  0x200035b0: _heap
  0x20008000: _eheap
