interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x202000
    file: snmp-serverX.bin
    ivt_offset: 0x0
    permissions: r-x
    size: 0x8e000
symbols:
  0x0: smartrf-sensors.c
  0x202000: vectors
  0x20228d: reset_handler
  0x2022cd: platform_init_stage_two
  0x202319: platform_init_stage_three
  0x2023a5: process_thread_sensors_process
  0x202481: value
  0x2024a5: configure
  0x2024f9: soc_get_rev
  0x202511: soc_print_info
  0x202521: update_ticks
  0x20256d: clock_init
  0x2025b9: clock_time
  0x2025cd: clock_seconds
  0x2025e1: clock_delay_usec
  0x2025fd: clock_adjust
  0x20261d: rtimer_arch_next_trigger
  0x202629: rtimer_arch_now
  0x202655: rtimer_arch_schedule
  0x2026ad: rtimer_isr
  0x2026d9: permit_pm1
  0x2026fd: uart_isr
  0x202761: uart_init
  0x202909: uart_set_input
  0x202919: uart_write_byte
  0x202935: watchdog_init
  0x202941: watchdog_start
  0x20294d: watchdog_periodic
  0x20295d: nvic_init
  0x20296d: sys_ctrl_init
  0x2029e1: gpio_port_isr
  0x202a2d: ioc_init
  0x202a49: ioc_set_over
  0x202a5d: ioc_set_sel
  0x202a71: adc_init
  0x202a81: adc_get
  0x202af9: permit_pm1
  0x202b09: crypto_isr
  0x202b31: crypto_enable
  0x202b51: crypto_init
  0x202b8d: crypto_disable
  0x202bad: gpio_hal_arch_no_port_pin_cfg_set
  0x202c8d: 'on'
  0x202cb5: 'off'
  0x202cf5: set_channel
  0x202d2d: channel_clear
  0x202d69: receiving_packet
  0x202d81: pending_packet
  0x202d91: get_value
  0x202f11: set_poll_mode
  0x202fad: set_object
  0x202fdd: read
  0x2030b9: prepare
  0x203125: init
  0x203205: process_thread_cc2538_rf_process
  0x203299: get_object
  0x2033dd: transmit
  0x203485: set_value
  0x203611: cc2538_rf_rx_tx_isr
  0x203635: cc2538_rf_err_isr
  0x20365d: udma_init
  0x203691: udma_set_channel_src
  0x2036a1: udma_set_channel_dst
  0x2036b5: udma_set_channel_control_word
  0x2036c9: udma_channel_enable
  0x2036e1: udma_channel_mask_set
  0x2036f9: udma_channel_sw_request
  0x203711: udma_channel_get_mode
  0x20372d: udma_isr
  0x20373d: udma_err_isr
  0x203749: select_32_mhz_xosc
  0x203779: lpm_exit
  0x2037ad: lpm_enter
  0x203865: lpm_register_peripheral
  0x203889: lpm_init
  0x2038ad: pka_isr
  0x2038d5: ieee_addr_cpy_to
  0x203935: sysDescr_handler
  0x203941: sysContact_handler
  0x20394d: sysName_handler
  0x203959: sysLocation_handler
  0x203965: sysObjectID_handler
  0x203971: uipbuf_add_ext_hdr
  0x2039a1: uipbuf_set_len
  0x2039b5: uipbuf_clear_attr
  0x2039c9: uipbuf_clear
  0x2039e9: uipbuf_init
  0x203a09: echo_reply_input
  0x203a75: echo_request_input
  0x203b0d: uip_icmp6_input
  0x203b45: uip_icmp6_register_input_handler
  0x203b51: uip_icmp6_error_output
  0x203c95: uip_icmp6_init
  0x203cb1: uip_ds6_prefix_add
  0x203d15: uip_ds6_is_addr_onlink
  0x203d55: uip_ds6_addr_lookup
  0x203d81: uip_ds6_get_link_local
  0x203dc1: uip_ds6_maddr_add
  0x203e0d: uip_ds6_addr_add
  0x203ea1: uip_ds6_maddr_lookup
  0x203ecd: uip_ds6_addr_rm
  0x203f11: uip_ds6_select_src
  0x203fa5: uip_ds6_send_ra_sollicited
  0x203fd9: uip_ds6_send_ra_periodic
  0x204029: uip_ds6_periodic
  0x204095: uip_ds6_compute_reachable_time
  0x2040c1: uip_ds6_init
  0x2041e5: uiplib_ipaddr_snprint
  0x2042d5: uip_udp_packet_send
  0x204309: call_route_callback
  0x204359: uip_ds6_route_init
  0x2043a5: uip_ds6_route_nexthop
  0x2043c1: uip_ds6_route_head
  0x2043cd: uip_ds6_route_lookup
  0x204435: uip_ds6_route_rm
  0x2044c9: rm_routelist
  0x2044f9: uip_ds6_defrt_rm
  0x20453d: uip_ds6_defrt_lookup
  0x204571: uip_ds6_defrt_choose
  0x2045a1: uip_ds6_defrt_periodic
  0x2045d1: uip_ds6_nbr_rm
  0x2045f5: uip_ds6_neighbors_init
  0x204611: uip_ds6_nbr_add
  0x204679: uip_ds6_nbr_get_ll
  0x204685: uip_ds6_nbr_head
  0x204691: uip_ds6_nbr_next
  0x20469d: uip_ds6_nbr_ll_lookup
  0x2046a9: uip_ds6_neighbor_periodic
  0x2047a9: tcpip_output
  0x2047d5: udp_new
  0x2047ed: tcpip_ipv6_output
  0x204925: packet_input
  0x204945: process_thread_tcpip_process
  0x204a01: tcpip_uipcall
  0x204a2d: upper_layer_chksum
  0x204a81: ext_hdr_options_process
  0x204afd: uip_update_ttl
  0x204b21: uip_init
  0x204b59: uip_remove_ext_hdr
  0x204bc1: uip_udp_new
  0x204c4d: uip_process
  0x2050b9: extract_lladdr_from_llao_aligned
  0x2050d9: create_llao
  0x205101: rs_input
  0x20526d: na_input
  0x2053fd: ns_input
  0x205645: uip_nd6_ns_output
  0x205791: uip_nd6_ra_output
  0x205979: uip_nd6_init
  0x20599d: snmp_message_decode
  0x205ca5: snmp_mib_find
  0x205cc9: snmp_mib_find_next
  0x205cf1: snmp_mib_add
  0x205d2d: snmp_mib_init
  0x205d39: process_thread_snmp_process
  0x205e9d: snmp_init
  0x205eb5: snmp_engine
  0x205f8d: main
  0x20617d: stimer_expired
  0x20619d: log_6addr
  0x2061bd: log_lladdr
  0x2061f9: update_time
  0x20623d: etimer_request_poll
  0x206249: process_thread_etimer_process
  0x2062f5: add_timer
  0x206335: etimer_pending
  0x206345: etimer_stop
  0x206379: node_id_init
  0x206391: process_thread_ctimer_process
  0x206411: ctimer_init
  0x206439: ctimer_set_with_process
  0x20647d: ctimer_set
  0x206491: ctimer_reset
  0x2064c9: ctimer_stop
  0x2064f5: ctimer_expired
  0x206529: rtimer_run_next
  0x206551: call_process.part.0
  0x206589: exit_process
  0x206609: do_poll
  0x20663d: process_alloc_event
  0x20664d: process_init
  0x20667d: process_run
  0x206701: process_nevents
  0x206715: process_post
  0x206751: process_post_synch
  0x206765: process_start
  0x206795: process_poll
  0x2067ad: stack_check_init
  0x2067d5: stack_check_get_usage
  0x206815: process_thread_stack_check_process
  0x2068c1: random_rand
  0x2068e1: random_init
  0x20695d: duration_exceeded_callback
  0x206991: process_thread_button_hal_process
  0x206a01: press_release_handler
  0x206a19: debounce_handler
  0x206a7d: button_hal_init
  0x206b71: process_thread_serial_line_process
  0x206c11: serial_line_input_byte
  0x206c55: serial_line_init
  0x206c79: leds_on
  0x206cd9: leds_off
  0x206d21: leds_init
  0x206d65: gpio_hal_register_handler
  0x206d71: gpio_hal_event_handler
  0x206d95: gpio_hal_init
  0x206da1: queuebuf_init
  0x206dbd: index_from_key
  0x206ddd: index_from_lladdr
  0x206e1d: nbr_get_bit.constprop.1
  0x206e49: nbr_table_is_registered
  0x206e69: nbr_table_register
  0x206e99: nbr_table_next
  0x206ee1: nbr_table_head
  0x206f19: nbr_table_add_lladdr
  0x207041: nbr_table_remove
  0x20706d: nbr_table_get_lladdr
  0x207091: packetbuf_set_datalen
  0x20709d: packetbuf_datalen
  0x2070a9: packetbuf_hdrlen
  0x2070c1: packetbuf_dataptr
  0x2070d1: packetbuf_attr_clear
  0x207105: packetbuf_clear
  0x207125: packetbuf_copyfrom
  0x207155: packetbuf_set_attr
  0x207165: packetbuf_set_addr
  0x20717d: packetbuf_addr
  0x20718d: netstack_process_ip_callback
  0x2071cd: netstack_init
  0x2071f1: periodic
  0x20721d: link_stats_init
  0x207245: fill_space
  0x207279: format_str_v
  0x207941: printf
  0x207961: vsnprintf
  0x207989: packet_input
  0x207995: 'on'
  0x2079a1: 'off'
  0x2079ad: max_payload
  0x2079c5: send_packet
  0x2079e1: init
  0x2079ed: output
  0x207a39: input
  0x207a75: nullnet_set_input_callback
  0x207a81: nullnet_input_callback_snmp
  0x207a95: process_thread_snmp_server_process
  0x207af5: __aeabi_uldivmod
  0x207b25: __udivmoddi4
  0x207e11: __aeabi_idiv0
  0x207e15: div
  0x207e4d: memcmp
  0x207eb1: memcpy
  0x207f9d: memmove
  0x208065: memset
  0x208101: strlen
  0x20815d: strncmp
  0x2081f9: default_handler
  0x2081fb: nmi_handler
  0x208201: fade
  0x208259: platform_init_stage_one
  0x20826d: platform_idle
  0x208271: status
  0x208275: soc_init
  0x208297: clock_isr
  0x20829b: rtimer_arch_init
  0x20829d: uart0_isr
  0x2082a3: uart1_isr
  0x2082a9: gpio_port_a_isr
  0x2082af: gpio_port_b_isr
  0x2082b5: gpio_port_c_isr
  0x2082bb: gpio_port_d_isr
  0x2082c1: send
  0x2082d3: int_master_read_and_disable
  0x2082db: int_master_status_set
  0x2082e1: dbg_putchar
  0x2082f1: dbg_send_bytes
  0x208311: configure
  0x208315: status
  0x208319: value
  0x20834d: configure
  0x208351: status
  0x208355: value
  0x20837f: sysServices_handler
  0x208399: sysUpTime_handler
  0x20839d: uipbuf_set_len_field
  0x2083a5: uipbuf_get_len_field
  0x2083b1: uipbuf_get_next_header
  0x2083ff: uipbuf_get_last_header
  0x20842b: uip_ds6_list_loop
  0x20847b: uip_ds6_maddr_rm
  0x208483: uip_ds6_set_addr_iid
  0x208499: get_match_length
  0x2084d7: uip_udp_packet_sendto
  0x208527: uip_ds6_route_next
  0x20852f: rm_routelist_callback
  0x208533: uip_ds6_nbr_lookup
  0x20855f: uip_ds6_nbr_update_ll
  0x2085bd: uip_ds6_nbr_ipaddr_from_lladdr
  0x2085c1: uip_ds6_nbr_refresh_reachable_state
  0x2085e1: chksum
  0x208619: uip_icmp6chksum
  0x20861f: uip_udpchksum
  0x208625: uip_htons
  0x20862b: uip_htonl
  0x20863d: snmp_api_replace_oid
  0x208653: snmp_api_set_string
  0x20866f: snmp_api_set_time_ticks
  0x208681: snmp_api_set_oid
  0x208693: snmp_api_add_resource
  0x208697: snmp_message_encode
  0x2087ad: snmp_oid_cmp_oid
  0x2087e7: snmp_oid_encode_oid
  0x20886f: snmp_oid_decode_oid
  0x208921: snmp_oid_copy
  0x208941: snmp_ber_encode_type
  0x20894d: snmp_ber_encode_length
  0x208959: snmp_ber_encode_integer
  0x20898b: snmp_ber_encode_unsigned_integer
  0x2089bb: snmp_ber_encode_string_len
  0x2089f5: snmp_ber_encode_null
  0x208a0b: snmp_ber_decode_type
  0x208a19: snmp_ber_decode_length
  0x208a27: snmp_ber_decode_integer
  0x208a73: snmp_ber_decode_unsigned_integer
  0x208abf: snmp_ber_decode_string_len_buffer
  0x208b2d: snmp_ber_decode_null
  0x208b37: snmp_engine_get
  0x208b85: snmp_engine_get_next
  0x208bd3: snmp_engine_get_bulk
  0x208d1b: autostart_start
  0x208d2f: stimer_set
  0x208d3d: stimer_remaining
  0x208d4d: stimer_elapsed
  0x208d5b: energest_init
  0x208d5d: etimer_set
  0x208d6f: etimer_reset
  0x208d81: etimer_expired
  0x208d8b: rtimer_init
  0x208d8f: call_process
  0x208d9b: timer_set
  0x208da9: timer_expired
  0x208dc5: timer_reset
  0x208dd9: ringbuf_init
  0x208de7: ringbuf_put
  0x208e0d: ringbuf_get
  0x208e2d: list_init
  0x208e33: list_head
  0x208e37: list_tail
  0x208e47: list_remove
  0x208e6d: list_add
  0x208e87: list_push
  0x208e97: list_length
  0x208ea5: list_insert
  0x208ec3: list_item_next
  0x208ec9: memb_init
  0x208ee9: memb_alloc
  0x208f11: memb_free
  0x208f3b: button_hal_get_state
  0x208f65: item_from_index
  0x208f79: index_from_item
  0x208f8f: nbr_set_bit
  0x208fc7: nbr_table_get_from_lladdr
  0x208fed: linkaddr_copy
  0x208ff3: linkaddr_cmp
  0x209003: write_str
  0x209013: buffer_str
  0x20903b: snprintf
  0x209055: putchar
  0x209061: init
  0x209065: root_set_prefix
  0x209067: get_sr_node_ipaddr
  0x20906b: leave_network
  0x20906d: ext_header_update
  0x209071: ext_header_hbh_update
  0x209075: ext_header_srh_update
  0x209079: ext_header_srh_get_next_hop
  0x20907d: link_callback
  0x20907f: drop_route
  0x209081: is_in_leaf_mode
  0x209085: ext_header_remove
  0x209089: get_root_ipaddr
  0x20908d: node_has_joined
  0x209091: node_is_reachable
  0x209095: global_repair
  0x209097: local_repair
  0x209099: neighbor_state_changed
  0x20909b: root_start
  0x20909f: node_is_root
  0x2090a3: init
  0x2090a4: als_sensor
  0x2090b4: uart_regs
  0x20910c: cc2538_rf_driver
  0x209144: output_power
  0x2091b4: cc2538_temp_sensor
  0x2091c4: vdd3_sensor
  0x2091d4: nullmac_driver
  0x2091f0: nullnet_driver
  0x209200: nullrouting_driver
  0x209254: autostart_processes
  0x20925c: linkaddr_null
  0x209264: leds_arch_leds
  0x2097e3: buffer.5551
  0x2097f3: buffer.5560
  0x209858: _ldata
  0x27ffd4: flash_cca_lock_page
  0x20000000: _enrdata
  0x20000040: _data
  0x20000050: sensors
  0x20000060: key_up
  0x200000b0: key_left
  0x20000100: key_select
  0x20000150: key_right
  0x200001a0: key_down
  0x200001f0: button_hal_buttons
  0x20000208: cc2538_rf_process
  0x20000218: sysObjectID
  0x20000224: sysLocation
  0x20000230: sysLocation_oid
  0x20000258: sysName
  0x20000264: sysContact_oid
  0x2000028c: sysDescr_oid
  0x200002b4: sysServices_oid
  0x200002dc: sysContact
  0x200002e8: sysDescr
  0x200002f4: sysUpTime_oid
  0x2000031c: sysServices
  0x20000328: sysObjectID_oid
  0x20000350: sysObjectID_oid.7084
  0x20000370: sysUpTime
  0x2000037c: sysName_oid
  0x200003a4: echo_request_handler
  0x200003b0: echo_reply_handler
  0x200003bc: defaultroutermemb
  0x200003c8: nbr_routes_struct
  0x200003d8: nbr_routes
  0x200003dc: routememb
  0x200003e8: neighborroutememb
  0x200003f4: ds6_neighbors_struct
  0x20000404: tcpip_process
  0x20000414: rs_input_handler
  0x20000420: ns_input_handler
  0x2000042c: na_input_handler
  0x20000438: snmp_process
  0x20000448: curr_log_level_main
  0x2000044c: curr_log_level_snmp
  0x20000450: etimer_process
  0x20000460: ctimer_process
  0x20000470: stack_check_process
  0x20000480: button_hal_process
  0x20000490: serial_line_process
  0x200004a0: bufmem
  0x200004ac: buframmem
  0x200004b8: neighbor_addr_mem
  0x200004c4: link_stats_struct
  0x200004d4: ctxt
  0x200004dc: snmp_server_process
  0x200004ec: send_on_cca
  0x200004ed: rf_channel
  0x200004ee: _edata
  0x200004f0: _bss
  0x200004f8: rt_ticks_epoch
  0x20000500: i.5534
  0x20000504: events.5535
  0x20000508: next_trigger
  0x2000050c: input_handler
  0x20000514: ioc_sel
  0x20000518: ioc_over
  0x2000051c: notification_process
  0x20000520: prev_MDMTEST1
  0x20000524: prev_FRMCTRL0
  0x20000528: periph_permit_pm1_funcs
  0x2000053c: notification_process
  0x20000540: echo_reply_callback_list_list
  0x20000544: input_handler_list_list
  0x20000548: locmaddr
  0x2000054c: locprefix
  0x20000550: locaddr
  0x20000554: defaultroutermemb_memb_mem
  0x20000594: num_routes
  0x20000598: defaultrouterlist_list
  0x2000059c: _nbr_routes_mem
  0x2000061c: routelist_list
  0x20000620: routememb_memb_mem
  0x200008a0: neighborroutememb_memb_mem
  0x20000920: notificationlist_list
  0x20000924: _ds6_neighbors_mem
  0x20000ba4: periodic
  0x20000bb4: prefix
  0x20000bb8: nbr
  0x20000bbc: nd6_opt_llao
  0x20000bc0: addr
  0x20000bc4: snmp_mib_list
  0x20000bc8: snmp_udp_conn
  0x20000bcc: packet_len.7064
  0x20000bd0: varbind_length.7147
  0x20000bd4: varbinds.7146
  0x20000c6c: header.7145
  0x20000c88: timerlist
  0x20000c8c: next_expiration
  0x20000c90: ctimer_list_list
  0x20000c94: next_rtimer
  0x20000c98: process_current
  0x20000c9c: process_list
  0x20000ca0: events
  0x20000e20: et.5876
  0x20000e30: button_event_handler
  0x20000e3c: pmask
  0x20000e40: rxbuf
  0x20000e48: ptr.5519
  0x20000e4c: handlers_list
  0x20000e50: bufmem_memb_mem
  0x20000e70: nbr_table_keys_list
  0x20000e74: neighbor_addr_mem_memb_mem
  0x20000f34: all_tables
  0x20000f54: num_tables
  0x20000f58: packetbuf_aligned
  0x20001458: ip_processor_list_list
  0x2000145c: _link_stats_mem
  0x2000151c: current_callback
  0x20001520: packet_len.7097
  0x20001524: uipbuf_attrs
  0x20001530: uipbuf_default_attrs
  0x2000153c: tmp_ipaddr
  0x2000154c: default_prefix
  0x2000155c: loc_fipaddr
  0x2000156c: rand_time
  0x2000156e: uip_ext_len
  0x20001570: lastport
  0x20001572: node_id
  0x20001574: buframmem_memb_mem
  0x20003ed4: buflen
  0x20003ed6: bufptr
  0x20003ed8: num_sensors
  0x20003ed9: crc_corr
  0x20003eda: was_on
  0x20003edb: rssi
  0x20003edc: poll_mode
  0x20003edd: rf_flags
  0x20003ede: max_pm
  0x20003edf: racount
  0x20003ee0: routememb_memb_used
  0x20003ef0: neighborroutememb_memb_used
  0x20003f00: defaultroutermemb_memb_used
  0x20003f02: uip_ext_bitmap
  0x20003f03: uip_last_proto
  0x20003f04: nd6_opt_offset
  0x20003f05: packet.7062
  0x20004105: initialized
  0x20004106: fevent
  0x20004107: nevents
  0x20004108: poll_requested
  0x20004109: lastevent
  0x2000410a: rxbuf_data
  0x2000418a: overflow.5512
  0x2000418b: buf.5518
  0x2000420b: buframmem_memb_used
  0x20004213: bufmem_memb_used
  0x2000421b: locked_map
  0x2000422b: neighbor_addr_mem_memb_used
  0x2000423b: used_map
  0x2000424b: hdrlen
  0x2000424c: packet.7095
  0x2000444c: uip_ds6_timer_ra
  0x20004454: uip_ds6_if
  0x2000454c: uip_ds6_netif_addr_list_offset
  0x2000454d: uip_ds6_addr_size
  0x20004550: uip_ds6_prefix_list
  0x200045b0: uip_ds6_timer_periodic
  0x200045c0: uip_len
  0x200045c4: uip_sappdata
  0x200045c8: uip_lladdr
  0x200045d0: uip_aligned_buf
  0x20004ad0: uip_flags
  0x20004ad4: uip_udp_conn
  0x20004ad8: uip_appdata
  0x20004adc: uip_conn
  0x20004ae0: uip_slen
  0x20004ae4: uip_udp_conns
  0x20004be4: periodic_timer
  0x20004c04: nullnet_buf
  0x20004c08: nullnet_len
  0x20004c0a: packetbuf_addrs
  0x20004c1a: packetbuf_attrs
  0x20004c34: linkaddr_node_addr
  0x20004c3c: sensors_event
  0x20004c3d: sensors_flags
  0x20004c41: tcpip_event
  0x20004c42: button_hal_release_event
  0x20004c43: button_hal_periodic_event
  0x20004c44: button_hal_press_event
  0x20004c45: serial_line_event_message
  0x20004c46: _stack
  0x20004c48: stack
  0x20005448: _heap
  0x20008000: _eheap
