board:
  init_nsvtor: 0x8000000

interrupt:
  mode: round-robin
  trigger:
    on-infinite-sleep: true
    interval: 1000

memory_maps:
  - name: mmio
    address: 0x40000000
    size: 0x20000000
    type: mmio
  - name: ram
    address: 0x20000000
    size: 0x100000
    type: ram
  - name: mmio_2
    address: 0x1fff7000
    size: 0x1000
    type: mmio
  - name: text
    address: 0x8000000
    size: 0x51800
    file:
      path: app_controlX.bin
    type: rom

symbols:
  - app_controlX.elf
