interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x8000000
    file: PLCX.bin
    ivt_offset: 0x0
    permissions: r-x
    size: 0x16140
symbols:
  0x0: reent.c
  0x400: _Min_Stack_Size
  0x2000: _Min_Heap_Size
  0x8000000: g_pfnVectors
  0x80001ad: __do_global_dtors_aux
  0x80001d1: frame_dummy
  0x8000219: strlen
  0x8000231: memchr
  0x80002d1: __aeabi_uldivmod
  0x8000301: __udivmoddi4
  0x80005dd: __aeabi_idiv0
  0x80005e1: _ZN6Modbus5beginEl
  0x800064d: _ZN6Modbus4initEhhh
  0x8000663: _ZN6ModbusC1Ehhh
  0x8000671: _Z41__static_initialization_and_destruction_0ii
  0x8000695: _ZN6Modbus11getRxBufferEv
  0x8000709: _ZN6Modbus7calcCRCEh
  0x800074d: _ZN6Modbus12sendTxBufferEv
  0x80007d1: _ZN6Modbus15validateRequestEv
  0x80008d9: _ZN6Modbus14buildExceptionEh
  0x80008ef: _ZN6Modbus11process_FC1EPth
  0x80009a5: _ZN6Modbus11process_FC3EPth
  0x8000a0d: _ZN6Modbus11process_FC5EPth
  0x8000a5b: _ZN6Modbus11process_FC6EPth
  0x8000a87: _ZN6Modbus12process_FC15EPth
  0x8000b11: _ZN6Modbus12process_FC16EPth
  0x8000b61: _ZN6Modbus4pollEPth
  0x8000c59: setup
  0x8000c6d: loop
  0x8000c85: _GLOBAL__sub_I__ZN6ModbusC2Ev
  0x8000c95: SystemClock_Config
  0x8000d45: Reset_Handler
  0x8000d4c: CopyDataInit
  0x8000d54: LoopCopyDataInit
  0x8000d62: FillZerobss
  0x8000d68: LoopFillZerobss
  0x8000d94: Default_Handler
  0x8000d95: CAN2_SCE_IRQHandler
  0x8000d97: init
  0x8000d9f: HAL_MspInit
  0x8000da1: HAL_InitTick
  0x8000ded: HAL_Init
  0x8000e21: HAL_IncTick
  0x8000e39: HAL_GetTick
  0x8000e45: HAL_NVIC_SetPriorityGrouping
  0x8000e69: HAL_NVIC_SetPriority
  0x8000ecd: HAL_NVIC_EnableIRQ
  0x8000ee9: HAL_SYSTICK_Config
  0x8000f15: HAL_NVIC_ClearPendingIRQ
  0x8000f35: HAL_SYSTICK_CLKSourceConfig
  0x8000f55: HAL_SYSTICK_Callback
  0x8000f57: HAL_SYSTICK_IRQHandler
  0x8000f5f: HAL_DAC_DeInit
  0x8000f7b: HAL_DAC_Stop
  0x8000f95: HAL_DMA_Abort_IT
  0x8000fbd: HAL_GPIO_Init
  0x80011a1: HAL_GPIO_WritePin
  0x80011ad: HAL_GPIO_EXTI_IRQHandler
  0x80011c9: I2C_Master_SB
  0x8001253: I2C_Master_ADD10
  0x800125f: I2C_Master_ADDR
  0x8001429: I2C_SlaveTransmit_BTF
  0x8001449: I2C_SlaveReceive_BTF
  0x8001469: HAL_I2C_Slave_Sequential_Transmit_IT
  0x80014f5: HAL_I2C_Slave_Sequential_Receive_IT
  0x8001581: HAL_I2C_EnableListen_IT
  0x80015bf: HAL_I2C_MasterTxCpltCallback
  0x80015c1: HAL_I2C_MasterRxCpltCallback
  0x80015c3: HAL_I2C_SlaveTxCpltCallback
  0x80015c5: I2C_SlaveTransmit_TXE
  0x8001615: HAL_I2C_SlaveRxCpltCallback
  0x8001617: I2C_SlaveReceive_RXNE
  0x8001663: I2C_Slave_ADDR
  0x800168d: I2C_Slave_AF
  0x8001721: HAL_I2C_MemTxCpltCallback
  0x8001723: I2C_MasterTransmit_TXE
  0x800186d: I2C_MasterTransmit_BTF
  0x800190b: HAL_I2C_MemRxCpltCallback
  0x800190d: I2C_MasterReceive_RXNE
  0x80019a9: I2C_MasterReceive_BTF
  0x8001ab5: HAL_I2C_AbortCpltCallback
  0x8001ab9: I2C_ITError
  0x8001c05: I2C_Slave_STOPF
  0x8001d09: HAL_I2C_EV_IRQHandler
  0x8001e71: HAL_I2C_ER_IRQHandler
  0x8001f45: I2C_DMAAbort
  0x8001fa5: HAL_PWREx_EnableOverDrive
  0x8002025: HAL_RCC_OscConfig
  0x80023bd: HAL_RCC_GetSysClockFreq
  0x8002491: HAL_RCC_ClockConfig
  0x80025e9: HAL_RCC_GetHCLKFreq
  0x80025f5: HAL_RCC_GetPCLK1Freq
  0x8002615: HAL_RCC_GetPCLK2Freq
  0x8002635: HAL_RTC_AlarmIRQHandler
  0x8002695: HAL_RTCEx_AlarmBEventCallback
  0x8002697: HAL_TIM_PWM_DeInit
  0x80026d1: HAL_TIM_IC_CaptureCallback
  0x80026d3: HAL_TIM_PWM_PulseFinishedCallback
  0x80026d5: HAL_TIM_TriggerCallback
  0x80026d7: HAL_TIM_IRQHandler
  0x8002851: TIM_CCxChannelCmd
  0x800286d: HAL_TIM_PWM_Stop
  0x80028dd: TIM_CCxNChannelCmd
  0x80028f9: HAL_TIMEx_PWMN_Stop
  0x8002945: HAL_TIMEx_CommutationCallback
  0x8002947: HAL_TIMEx_BreakCallback
  0x8002949: UART_EndRxTransfer
  0x8002965: UART_Transmit_IT
  0x80029d1: UART_SetConfig
  0x8002d15: UART_WaitOnFlagUntilTimeout
  0x8002d79: HAL_UART_MspInit
  0x8002d7b: HAL_UART_Init
  0x8002dd9: HAL_UART_Transmit
  0x8002ebb: HAL_UART_Transmit_IT
  0x8002f03: HAL_UART_Receive_IT
  0x8002f55: UART_EndTransmit_IT
  0x8002f6f: UART_Receive_IT
  0x8003005: HAL_UART_IRQHandler
  0x8003125: UART_DMAAbortOnError
  0x8003135: HAL_UART_GetState
  0x8003141: is_pin_configured
  0x8003157: set_pin_configured
  0x8003175: reset_pin_configured
  0x8003195: get_GPIO_Port
  0x8003205: set_GPIO_Port_Clock
  0x8003389: get_dac_channel
  0x80033a5: get_pwm_channel
  0x80033d1: HAL_DAC_MspDeInit
  0x80033e1: dac_stop
  0x8003415: HAL_TIM_PWM_MspDeInit
  0x800341d: pwm_stop
  0x8003475: GetCurrentMilli
  0x800347d: noOsSystickHandler
  0x800347f: SysTick_Handler
  0x800348f: digital_io_init
  0x80034bf: digital_io_write
  0x80034d7: hw_config_init
  0x80034e3: pinmap_find_peripheral
  0x80034fd: pinmap_peripheral
  0x800350f: pinmap_find_pin
  0x8003527: pinmap_pin
  0x8003537: pinmap_find_function
  0x8003553: pinmap_function
  0x8003567: pin_in_pinmap
  0x800358b: pinmap_merge_peripheral
  0x800359d: HAL_RTC_AlarmAEventCallback
  0x80035b5: RTC_Alarm_IRQHandler
  0x80035c5: SystemInit
  0x8003605: timer_disable_clock
  0x8003759: get_timer_obj
  0x800375d: HAL_TIM_OC_DelayElapsedCallback
  0x8003777: HAL_TIM_PeriodElapsedCallback
  0x8003785: TIM1_UP_TIM10_IRQHandler
  0x80037a1: TIM2_IRQHandler
  0x80037b5: TIM3_IRQHandler
  0x80037c9: TIM4_IRQHandler
  0x80037dd: TIM5_IRQHandler
  0x80037f1: TIM6_DAC_IRQHandler
  0x8003805: TIM7_IRQHandler
  0x8003819: TIM8_UP_TIM13_IRQHandler
  0x8003835: TIM1_BRK_TIM9_IRQHandler
  0x8003849: TIM1_TRG_COM_TIM11_IRQHandler
  0x800385d: TIM8_BRK_TIM12_IRQHandler
  0x8003871: TIM8_TRG_COM_TIM14_IRQHandler
  0x8003885: get_i2c_obj
  0x8003889: HAL_I2C_AddrCallback
  0x80038d9: HAL_I2C_ListenCpltCallback
  0x8003909: HAL_I2C_ErrorCallback
  0x8003921: I2C1_EV_IRQHandler
  0x8003931: I2C1_ER_IRQHandler
  0x8003941: I2C2_EV_IRQHandler
  0x8003951: I2C2_ER_IRQHandler
  0x8003961: I2C3_EV_IRQHandler
  0x8003971: I2C3_ER_IRQHandler
  0x8003981: uart_init
  0x8003cd1: uart_debug_init
  0x8003d21: uart_debug_write
  0x8003dd9: serial_rx_active
  0x8003dfd: serial_tx_active
  0x8003e21: uart_getc
  0x8003e5d: uart_attach_rx_callback
  0x8003eb5: uart_attach_tx_callback
  0x8003f09: uart_index
  0x8003f2d: HAL_UART_RxCpltCallback
  0x8003f51: HAL_UART_TxCpltCallback
  0x8003f9d: HAL_UART_ErrorCallback
  0x8003fdd: USART1_IRQHandler
  0x8003ff5: USART2_IRQHandler
  0x800400d: USART3_IRQHandler
  0x8004025: UART4_IRQHandler
  0x800403d: UART5_IRQHandler
  0x8004055: USART6_IRQHandler
  0x800406d: UART7_IRQHandler
  0x8004085: UART8_IRQHandler
  0x800409d: _sbrk
  0x80040d9: _close
  0x80040df: _fstat
  0x80040e9: _isatty
  0x80040ed: _lseek
  0x80040f1: _read
  0x80040f5: _write
  0x8004101: _exit
  0x8004105: _kill
  0x8004115: _getpid
  0x8004119: pinMode
  0x80041c5: digitalWrite
  0x800420d: millis
  0x8004215: _ZN14HardwareSerial16_tx_complete_irqEP8serial_s
  0x8004249: _ZN14HardwareSerial9availableEv
  0x800425d: _ZN14HardwareSerial4peekEv
  0x8004279: _ZN14HardwareSerial4readEv
  0x80042a1: _ZN14HardwareSerial5flushEv
  0x80042b5: _ZN14HardwareSerial16_rx_complete_irqEP8serial_s
  0x80042f1: _ZN14HardwareSerial5writeEh
  0x8004341: _Z14serialEventRunv
  0x800436d: _ZN14HardwareSerial4initEv
  0x8004391: _ZN14HardwareSerial5beginEmh
  0x800444d: _ZN14HardwareSerial5setRxEm
  0x8004469: _ZN14HardwareSerial5setTxEm
  0x8004485: _ZN14HardwareSerialC1EPv
  0x80044e1: _Z41__static_initialization_and_destruction_0ii
  0x8004505: _GLOBAL__sub_I_Serial3
  0x8004513: _ZNK9IPAddress7printToER5Print
  0x800454d: _ZN9IPAddressC1Ehhhh
  0x8004569: _Z41__static_initialization_and_destruction_0ii
  0x8004595: _GLOBAL__sub_I__ZN9IPAddressC2Ev
  0x80045a3: _ZN5Print5writeEPKhj
  0x80045c7: _ZN5Print5printEc
  0x80045d1: _ZN5Print11printNumberEmh
  0x800462b: _ZN5Print5printEmi
  0x8004641: _ZN5Print5printEhi
  0x8004649: _Z8makeWordhh
  0x800464f: _Z11initVariantv
  0x8004651: _Z7premainv
  0x8004661: main
  0x8004681: _ZL10get_pin_idt
  0x8004695: __tcf_0
  0x80046bd: _Z41__static_initialization_and_destruction_0ii
  0x8004769: EXTI0_IRQHandler
  0x8004773: EXTI1_IRQHandler
  0x800477d: EXTI2_IRQHandler
  0x8004787: EXTI3_IRQHandler
  0x8004791: EXTI4_IRQHandler
  0x800479b: EXTI9_5_IRQHandler
  0x80047b1: EXTI15_10_IRQHandler
  0x80047c9: _ZNKSt8functionIFvvEEclEv
  0x80047d9: HAL_GPIO_EXTI_Callback
  0x80047f9: _GLOBAL__sub_I__Z22stm32_interrupt_enableP12GPIO_TypeDeftSt8functionIFvvEEm
  0x8004807: __aeabi_atexit
  0x8004811: __assert_func
  0x800484d: __cxa_atexit
  0x8004869: fiprintf
  0x800488d: __libc_init_array
  0x80048d5: memset
  0x80048e5: _free_r
  0x8004981: _malloc_r
  0x8004a3d: __sfputc_r
  0x8004a69: __sfputs_r
  0x8004a8d: _vfiprintf_r
  0x8004cb9: _printf_common
  0x8004da5: _printf_i
  0x8004fe5: iprintf
  0x8005015: _sbrk_r
  0x8005035: __swbuf_r
  0x80050d9: __swsetup_r
  0x80051b5: abort
  0x80051c5: __sflush_r
  0x80052d5: _fflush_r
  0x8005329: _cleanup_r
  0x8005335: std.isra.0
  0x800537d: __sfmoreglue
  0x80053a9: __sinit
  0x8005409: __sfp
  0x8005481: _fwalk_reent
  0x80054bd: __swhatbuf_r
  0x8005505: __smakebuf_r
  0x8005585: __malloc_lock
  0x8005587: __malloc_unlock
  0x8005589: _raise_r
  0x80055d9: raise
  0x80055e9: _kill_r
  0x800560d: _getpid_r
  0x8005611: __sread
  0x8005633: __swrite
  0x800566b: __sseek
  0x800568f: __sclose
  0x8005699: _write_r
  0x80056bd: _close_r
  0x80056dd: _fstat_r
  0x8005701: _isatty_r
  0x8005721: _lseek_r
  0x8005745: _read_r
  0x8005769: _ZSt25__throw_bad_function_callv
  0x8005771: _GLOBAL__sub_I__ZNSt12ctype_bynameIcEC2ERKSsj
  0x8005835: _GLOBAL__sub_I__ZNSt12ctype_bynameIwEC2ERKSsj
  0x80058f9: _GLOBAL__sub_I__ZNSt12ctype_bynameIwEC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEj
  0x800597d: _GLOBAL__sub_I__ZNSt12ctype_bynameIcEC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEj
  0x8005a00: __EH_FRAME_BEGIN__
  0x8005a01: _init
  0x8005a0d: _fini
  0x8005a18: _etext
  0x8005a20: PinMap_DAC
  0x8005a44: PinMap_PWM
  0x8005c18: PinMap_UART_RX
  0x8005ca8: PinMap_UART_TX
  0x8005d44: digitalPin
  0x8005e04: AHBPrescTable
  0x8005e14: APBPrescTable
  0x8005ed4: _ZTV14HardwareSerial
  0x8005ef4: _ZZN14HardwareSerial5beginEmhE19__PRETTY_FUNCTION__
  0x8005f28: _ZTV9IPAddress
  0x8005f70: _global_impure_ptr
  0x8005fa8: __sf_fake_stderr
  0x8005fc8: __sf_fake_stdin
  0x8005fe8: __sf_fake_stdout
  0x8006008: __exidx_start
  0x8006010: __exidx_end
  0x8006014: __frame_dummy_init_array_entry
  0x8006038: __init_array_end
  0x800603c: _sidata
  0x8006140: _siccmram
  0x10000000: _sccmram
  0x20000000: __dso_handle
  0x20000004: au16data
  0x20000024: uwTickFreq
  0x20000028: uwTickPrio
  0x2000002c: SystemCoreClock
  0x20000030: serial_debug
  0x200000a0: _impure_ptr
  0x200000a4: impure_data
  0x20000104: _edata
  0x20000108: object.8672
  0x20000120: slave
  0x20000184: RTCUserCallback
  0x20000188: RtcHandle
  0x200001a8: callbackUserData
  0x200001ac: timer_handles
  0x20000204: i2c_handles
  0x20000210: rx_callback
  0x20000238: rx_callback_obj
  0x20000260: tx_callback
  0x20000288: tx_callback_obj
  0x200002b0: uart_handlers
  0x200002d8: heap_end.4572
  0x200002dc: g_anOutputPinConfigured
  0x20000308: g_digPinConfigured
  0x20000334: Serial3
  0x2000043c: _ZL11INADDR_NONE
  0x20000444: _ZL13gpio_irq_conf
  0x20000584: __malloc_free_list
  0x20000588: __malloc_sbrk_start
  0x2000058c: _ZGVNSt7collateIcE2idE
  0x20000590: _ZGVNSt8messagesIcE2idE
  0x20000594: _ZGVNSt8time_getIcSt19istreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x20000598: _ZGVNSt8time_putIcSt19ostreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x2000059c: _ZGVNSt11__timepunctIcE2idE
  0x200005a0: _ZGVNSt7num_putIcSt19ostreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x200005a4: _ZGVNSt7num_getIcSt19istreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x200005a8: _ZGVNSt8numpunctIcE2idE
  0x200005ac: _ZGVNSt9money_putIcSt19ostreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x200005b0: _ZGVNSt9money_getIcSt19istreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x200005b4: _ZGVNSt10moneypunctIcLb1EE2idE
  0x200005b8: _ZGVNSt10moneypunctIcLb0EE2idE
  0x200005bc: _ZGVNSt7collateIwE2idE
  0x200005c0: _ZGVNSt8messagesIwE2idE
  0x200005c4: _ZGVNSt8time_getIwSt19istreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x200005c8: _ZGVNSt8time_putIwSt19ostreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x200005cc: _ZGVNSt11__timepunctIwE2idE
  0x200005d0: _ZGVNSt7num_putIwSt19ostreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x200005d4: _ZGVNSt7num_getIwSt19istreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x200005d8: _ZGVNSt8numpunctIwE2idE
  0x200005dc: _ZGVNSt9money_putIwSt19ostreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x200005e0: _ZGVNSt9money_getIwSt19istreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x200005e4: _ZGVNSt10moneypunctIwLb1EE2idE
  0x200005e8: _ZGVNSt10moneypunctIwLb0EE2idE
  0x200005ec: _ZGVNSt7__cxx117collateIwE2idE
  0x200005f0: _ZGVNSt7__cxx118messagesIwE2idE
  0x200005f4: _ZGVNSt7__cxx118time_getIwSt19istreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x200005f8: _ZGVNSt7__cxx118numpunctIwE2idE
  0x200005fc: _ZGVNSt7__cxx119money_putIwSt19ostreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x20000600: _ZGVNSt7__cxx119money_getIwSt19istreambuf_iteratorIwSt11char_traitsIwEEE2idE
  0x20000604: _ZGVNSt7__cxx1110moneypunctIwLb1EE2idE
  0x20000608: _ZGVNSt7__cxx1110moneypunctIwLb0EE2idE
  0x2000060c: _ZGVNSt7__cxx117collateIcE2idE
  0x20000610: _ZGVNSt7__cxx118messagesIcE2idE
  0x20000614: _ZGVNSt7__cxx118time_getIcSt19istreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x20000618: _ZGVNSt7__cxx118numpunctIcE2idE
  0x2000061c: _ZGVNSt7__cxx119money_putIcSt19ostreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x20000620: _ZGVNSt7__cxx119money_getIcSt19istreambuf_iteratorIcSt11char_traitsIcEEE2idE
  0x20000624: _ZGVNSt7__cxx1110moneypunctIcLb1EE2idE
  0x20000628: _ZGVNSt7__cxx1110moneypunctIcLb0EE2idE
  0x2000062c: uwTick
  0x20000630: errno
  0x20000634: __bss_end__
  0x20000638: _end
  0x20030000: _estack
