begin_point: 0x800463e
entry_point: 0x8000d19
fork_points:
  - 0x800463e
include:
  - ./cortexm_memory.yml
initial_sp: 0x20030000
isr_vector: 0x8000d19
memory_map:
  flash:
    base_addr: 0x8000000
    file: ./PLC.bin
    permissions: r-x
    size: 0x2000000
rules: rules.txt
