interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x202000
    file: contiki-hello-4-8.bin
    ivt_offset: 0x0
    permissions: r-x
    size: 0x8e000
symbols:
  0x0: smartrf-sensors.c
  0x202000: vectors
  0x20228d: reset_handler
  0x2022cd: platform_init_stage_two
  0x202319: platform_init_stage_three
  0x2023a5: process_thread_sensors_process
  0x202481: value
  0x2024a5: configure
  0x2024f9: soc_get_rev
  0x202511: soc_print_info
  0x202521: update_ticks
  0x20256d: clock_init
  0x2025b9: clock_time
  0x2025cd: clock_seconds
  0x2025e1: clock_delay_usec
  0x2025fd: clock_adjust
  0x20261d: rtimer_arch_next_trigger
  0x202629: rtimer_arch_now
  0x202655: rtimer_arch_schedule
  0x2026ad: rtimer_isr
  0x2026e1: permit_pm1
  0x202705: uart_isr
  0x202769: uart_init
  0x202911: uart_set_input
  0x202921: uart_write_byte
  0x20293d: watchdog_init
  0x202949: watchdog_start
  0x202955: watchdog_periodic
  0x202965: nvic_init
  0x202975: sys_ctrl_init
  0x2029e9: gpio_port_isr
  0x202a35: ioc_init
  0x202a51: ioc_set_over
  0x202a65: ioc_set_sel
  0x202a79: adc_init
  0x202a89: adc_get
  0x202b01: permit_pm1
  0x202b11: crypto_isr
  0x202b41: crypto_enable
  0x202b61: crypto_init
  0x202b9d: crypto_disable
  0x202bbd: gpio_hal_arch_no_port_pin_cfg_set
  0x202c9d: 'on'
  0x202cc5: 'off'
  0x202d05: set_channel
  0x202d3d: channel_clear
  0x202d79: read
  0x202da1: receiving_packet
  0x202db9: pending_packet
  0x202dc9: get_value
  0x202f2d: set_object
  0x202f5d: get_object
  0x2030a1: transmit
  0x203145: prepare
  0x2031ad: set_poll_mode
  0x203251: init
  0x203339: process_thread_cc2538_rf_process
  0x2033c9: set_value
  0x203559: cc2538_rf_rx_tx_isr
  0x20357d: cc2538_rf_err_isr
  0x2035a5: udma_init
  0x2035d9: udma_set_channel_src
  0x2035e9: udma_set_channel_dst
  0x2035fd: udma_set_channel_control_word
  0x203611: udma_channel_enable
  0x203629: udma_channel_mask_set
  0x203641: udma_channel_sw_request
  0x203659: udma_isr
  0x203669: udma_err_isr
  0x203675: select_32_mhz_xosc
  0x2036a5: lpm_exit
  0x2036d9: lpm_enter
  0x203791: lpm_register_peripheral
  0x2037b5: lpm_init
  0x2037d9: pka_isr
  0x203809: ieee_addr_cpy_to
  0x203869: main
  0x203a55: stimer_expired
  0x203a75: log_6addr
  0x203a95: log_lladdr
  0x203ad1: update_time
  0x203b15: etimer_request_poll
  0x203b21: process_thread_etimer_process
  0x203bcd: add_timer
  0x203c0d: etimer_pending
  0x203c1d: etimer_stop
  0x203c51: node_id_init
  0x203c69: process_thread_ctimer_process
  0x203ce9: ctimer_init
  0x203d11: ctimer_set_with_process
  0x203d55: ctimer_set
  0x203d69: ctimer_reset
  0x203da1: ctimer_stop
  0x203dcd: ctimer_expired
  0x203e01: rtimer_run_next
  0x203e29: call_process.part.0
  0x203e61: exit_process
  0x203ee1: do_poll
  0x203f15: process_alloc_event
  0x203f25: process_exit
  0x203f31: process_init
  0x203f61: process_run
  0x203fe5: process_nevents
  0x203ff9: process_post
  0x204035: process_post_synch
  0x204049: process_start
  0x204079: process_poll
  0x204091: stack_check_init
  0x2040b9: stack_check_get_usage
  0x2040f9: process_thread_stack_check_process
  0x2041a5: random_rand
  0x2041c5: random_init
  0x204241: duration_exceeded_callback
  0x204275: process_thread_button_hal_process
  0x2042e9: press_release_handler
  0x204301: debounce_handler
  0x204365: button_hal_init
  0x204459: process_thread_serial_line_process
  0x2044f9: serial_line_input_byte
  0x20453d: serial_line_init
  0x204561: leds_on
  0x2045c1: leds_off
  0x204609: leds_init
  0x20464d: gpio_hal_register_handler
  0x204659: gpio_hal_event_handler
  0x20467d: gpio_hal_init
  0x204689: queuebuf_init
  0x2046a5: queuebuf_numfree
  0x2046b1: queuebuf_new_from_packetbuf
  0x2046f5: queuebuf_free
  0x204721: queuebuf_to_packetbuf
  0x204751: index_from_key
  0x204771: index_from_lladdr
  0x2047b1: nbr_get_bit.constprop.3
  0x2047dd: remove_key
  0x204865: nbr_table_is_registered
  0x204885: nbr_table_register
  0x2048b5: nbr_table_next
  0x2048fd: nbr_table_head
  0x204935: entry_is_allowed.isra.2
  0x2049a5: nbr_table_add_lladdr
  0x204a55: nbr_table_remove
  0x204a81: nbr_table_lock
  0x204a91: nbr_table_unlock
  0x204aa1: nbr_table_get_lladdr
  0x204ac5: packetbuf_set_datalen
  0x204ad1: packetbuf_hdrptr
  0x204ad9: packetbuf_datalen
  0x204ae5: packetbuf_hdrlen
  0x204afd: packetbuf_dataptr
  0x204b0d: packetbuf_copyto
  0x204b51: packetbuf_totlen
  0x204b65: packetbuf_hdralloc
  0x204ba5: packetbuf_attr_clear
  0x204bd9: packetbuf_clear
  0x204bf9: packetbuf_copyfrom
  0x204c25: packetbuf_attr_copyto
  0x204c49: packetbuf_attr_copyfrom
  0x204c6d: packetbuf_set_attr
  0x204c7d: packetbuf_attr
  0x204c89: packetbuf_set_addr
  0x204ca1: packetbuf_addr
  0x204cb1: netstack_process_ip_callback
  0x204cf1: netstack_init
  0x204d15: periodic
  0x204d41: link_stats_from_lladdr
  0x204d4d: link_stats_packet_sent
  0x204dd1: link_stats_input_callback
  0x204e35: link_stats_reset
  0x204e59: link_stats_init
  0x204e81: fill_space
  0x204eb5: format_str_v
  0x205589: printf
  0x2055a9: vsnprintf
  0x2055d1: process_thread_ble_l2cap_tx_process
  0x205731: get_channel_for_addr
  0x205779: 'off'
  0x205789: 'on'
  0x20579d: send
  0x205869: init
  0x2059c9: input_l2cap_conn_req
  0x205b05: input
  0x205d0d: uipbuf_add_ext_hdr
  0x205d3d: uipbuf_set_len
  0x205d51: uipbuf_get_attr
  0x205d65: uipbuf_set_attr
  0x205d79: uipbuf_clear_attr
  0x205d8d: uipbuf_clear
  0x205dad: uipbuf_init
  0x205dcd: echo_reply_input
  0x205e39: echo_request_input
  0x205ed1: uip_icmp6_input
  0x205f09: uip_icmp6_register_input_handler
  0x205f15: uip_icmp6_error_output
  0x206059: uip_icmp6_send
  0x2060dd: uip_icmp6_init
  0x2060f9: node_matches_address.part.0
  0x206121: uip_sr_get_node
  0x206155: uip_sr_is_addr_reachable
  0x206199: uip_sr_update_node
  0x20623d: uip_sr_init
  0x206261: uip_sr_periodic
  0x2062c9: uip_sr_free_all
  0x206309: uip_ds6_default_prefix
  0x206311: uip_ds6_prefix_add
  0x206375: uip_ds6_is_addr_onlink
  0x2063b5: uip_ds6_addr_lookup
  0x2063e1: uip_ds6_get_link_local
  0x206421: uip_ds6_maddr_add
  0x20646d: uip_ds6_addr_add
  0x206501: uip_ds6_maddr_lookup
  0x20652d: uip_ds6_addr_rm
  0x206571: uip_ds6_periodic
  0x2065bd: uip_ds6_select_src
  0x206651: uip_ds6_compute_reachable_time
  0x20667d: uip_ds6_init
  0x206799: uiplib_ipaddr_snprint
  0x206889: uip_ds6_route_init
  0x2068a5: uip_ds6_defrt_rm
  0x2068dd: uip_ds6_defrt_lookup
  0x206911: uip_ds6_defrt_add
  0x206971: uip_ds6_defrt_choose
  0x2069a1: uip_ds6_defrt_periodic
  0x2069d1: uip_ds6_nbr_rm
  0x2069f5: uip_ds6_neighbors_init
  0x206a11: uip_ds6_nbr_add
  0x206a51: uip_ds6_nbr_get_ll
  0x206a5d: uip_ds6_nbr_head
  0x206a69: uip_ds6_nbr_next
  0x206a75: uip_ds6_nbr_ll_lookup
  0x206a81: tcpip_output
  0x206aad: tcpip_input
  0x206ad1: tcpip_ipv6_output
  0x206bb5: packet_input
  0x206bd5: process_thread_tcpip_process
  0x206c91: tcpip_uipcall
  0x206cbd: upper_layer_chksum
  0x206d11: ext_hdr_options_process
  0x206d8d: uip_update_ttl
  0x206db1: uip_init
  0x206de9: uip_remove_ext_hdr
  0x206e51: uip_process
  0x2072ad: ns_input
  0x207525: uip_nd6_init
  0x207531: clear_fragments
  0x20756d: sicslowpan_init
  0x207585: set_packet_attrs
  0x2075dd: compress_addr_64
  0x20766d: addr_context_lookup_by_prefix
  0x207691: send_packet
  0x2076b5: fragment_copy_payload_and_send
  0x207721: output
  0x207ea1: packet_sent
  0x207efd: store_fragment
  0x207f59: uncompress_addr
  0x207fe9: add_fragment
  0x208109: input
  0x20899d: get_rank
  0x2089bd: remove_neighbor
  0x2089f9: rpl_neighbor_get_from_lladdr
  0x208a09: rpl_neighbor_rank_via_nbr
  0x208a21: rpl_neighbor_get_lladdr
  0x208a31: best_parent
  0x208ac5: rpl_neighbor_set_preferred_parent
  0x208b0d: rpl_neighbor_remove_all
  0x208b3d: rpl_neighbor_get_from_ipaddr
  0x208b59: rpl_neighbor_select_best
  0x208bad: rpl_neighbor_init
  0x208bc1: new_dio_interval
  0x208c19: schedule_dao_retransmission
  0x208c49: handle_unicast_dio_timer
  0x208c65: send_new_dao
  0x208c99: resend_dao
  0x208cd1: handle_dao_ack_timer
  0x208ce5: handle_leaving_timer
  0x208cf5: handle_dio_timer
  0x208d65: rpl_timers_schedule_periodic_dis
  0x208d9d: handle_dis_timer
  0x208dd1: handle_periodic_timer
  0x208e19: rpl_timers_dio_reset
  0x208e4d: rpl_timers_schedule_unicast_dio
  0x208e75: rpl_timers_schedule_dao
  0x208ea9: rpl_timers_schedule_dao_ack
  0x208ef1: rpl_timers_notify_dao_ack
  0x208f3d: get_probing_target
  0x208ffd: rpl_schedule_probing
  0x209025: rpl_schedule_probing_now
  0x209051: rpl_timers_unschedule_leaving
  0x209075: rpl_timers_schedule_leaving
  0x2090a5: rpl_timers_init
  0x2090c5: rpl_timers_stop_dag_timers
  0x209109: rpl_timers_unschedule_state_update
  0x20911d: rpl_timers_schedule_state_update
  0x209139: update_hbh_header
  0x209185: rpl_ext_header_srh_get_next_hop
  0x209209: rpl_ext_header_srh_update
  0x2092c1: rpl_ext_header_hbh_update
  0x209351: rpl_ext_header_remove
  0x209401: rpl_ext_header_update
  0x209659: rpl_has_joined
  0x209671: rpl_is_reachable
  0x209689: rpl_get_leaf_only
  0x209695: get_sr_node_ipaddr
  0x2096c1: set_ip_from_prefix
  0x2096ed: init
  0x20972d: rpl_link_callback
  0x209759: rpl_get_global_address
  0x2097bd: rpl_reset_prefix
  0x2097e5: rpl_set_prefix_from_addr
  0x209855: update_metric_container
  0x209861: within_hysteresis
  0x209899: rank_via_nbr
  0x2098c9: best_parent
  0x209939: dao_ack_input
  0x209971: dao_input
  0x209a71: dio_input
  0x209c85: dis_input
  0x209cb1: rpl_icmp6_dis_output
  0x209ce9: rpl_icmp6_dio_output
  0x209ea9: rpl_icmp6_dao_output
  0x209f6d: rpl_icmp6_dao_ack_output
  0x209fb1: rpl_icmp6_init
  0x209fe1: init_dag
  0x20a059: process_dio_init_dag
  0x20a0fd: rpl_dag_get_root_ipaddr
  0x20a12d: rpl_dag_leave
  0x20a181: rpl_dag_poison_and_leave
  0x20a191: rpl_dag_periodic
  0x20a1d9: rpl_is_addr_in_our_dag
  0x20a201: rpl_local_repair
  0x20a235: rpl_global_repair
  0x20a26d: rpl_dag_ready_to_advertise
  0x20a291: rpl_dag_update_state
  0x20a3c1: rpl_process_dio
  0x20a539: rpl_process_dis
  0x20a565: rpl_process_dao
  0x20a5b1: rpl_process_dao_ack
  0x20a605: rpl_dag_init_root
  0x20a6ad: rpl_dag_init
  0x20a6bd: rpl_dag_root_set_prefix
  0x20a725: rpl_dag_root_start
  0x20a78d: rpl_dag_root_is_root
  0x20a7a5: process_thread_hello_world_process
  0x20a7ed: __aeabi_uldivmod
  0x20a81d: __udivmoddi4
  0x20ab09: __aeabi_idiv0
  0x20ab0d: memcmp
  0x20ab71: memcpy
  0x20ac5d: memmove
  0x20ad25: memset
  0x20adc1: strlen
  0x20ae1d: default_handler
  0x20ae1f: nmi_handler
  0x20ae25: fade
  0x20ae7d: platform_init_stage_one
  0x20ae91: platform_idle
  0x20ae95: status
  0x20ae99: soc_init
  0x20aebb: clock_isr
  0x20aebf: rtimer_arch_init
  0x20aec1: uart0_isr
  0x20aec7: uart1_isr
  0x20aecd: gpio_port_a_isr
  0x20aed3: gpio_port_b_isr
  0x20aed9: gpio_port_c_isr
  0x20aedf: gpio_port_d_isr
  0x20aee5: send
  0x20aef7: int_master_read_and_disable
  0x20aeff: int_master_status_set
  0x20af05: dbg_putchar
  0x20af15: dbg_send_bytes
  0x20af35: configure
  0x20af39: status
  0x20af3d: value
  0x20af71: configure
  0x20af75: status
  0x20af79: value
  0x20afa3: autostart_start
  0x20afb7: stimer_set
  0x20afc5: energest_init
  0x20afc7: etimer_set
  0x20afd9: etimer_reset
  0x20afeb: etimer_expired
  0x20aff5: rtimer_init
  0x20aff9: call_process
  0x20b005: timer_set
  0x20b013: timer_expired
  0x20b02f: timer_reset
  0x20b043: ringbuf_init
  0x20b051: ringbuf_put
  0x20b077: ringbuf_get
  0x20b097: list_init
  0x20b09d: list_head
  0x20b0a1: list_tail
  0x20b0b1: list_remove
  0x20b0d7: list_add
  0x20b0f1: list_push
  0x20b101: list_item_next
  0x20b107: memb_init
  0x20b127: memb_alloc
  0x20b14f: memb_free
  0x20b179: memb_inmemb
  0x20b195: memb_numfree
  0x20b1b1: button_hal_get_state
  0x20b1db: item_from_index
  0x20b1ef: index_from_item
  0x20b205: nbr_set_bit
  0x20b23d: nbr_table_get_from_lladdr
  0x20b263: linkaddr_copy
  0x20b269: linkaddr_cmp
  0x20b279: link_stats_is_fresh
  0x20b29d: guess_etx_from_rssi
  0x20b2e3: mac_call_sent_callback
  0x20b2fb: write_str
  0x20b30b: buffer_str
  0x20b333: snprintf
  0x20b34d: putchar
  0x20b359: max_payload
  0x20b35f: input_l2cap_connection_udate_resp
  0x20b383: input_l2cap_credit
  0x20b3cb: uipbuf_set_len_field
  0x20b3d3: uipbuf_get_len_field
  0x20b3df: uipbuf_get_next_header
  0x20b433: uipbuf_get_last_header
  0x20b45f: uipbuf_search_header
  0x20b49f: uip_sr_expire_parent
  0x20b4cd: uip_ds6_list_loop
  0x20b51d: uip_ds6_maddr_rm
  0x20b525: uip_ds6_set_addr_iid
  0x20b53b: uip_ds6_set_lladdr_from_iid
  0x20b551: get_match_length
  0x20b58f: uip_ds6_route_nexthop
  0x20b593: uip_ds6_route_lookup
  0x20b597: uip_ds6_route_rm
  0x20b599: uip_ds6_nbr_lookup
  0x20b5c5: uip_ds6_nbr_update_ll
  0x20b623: uip_ds6_nbr_ipaddr_from_lladdr
  0x20b627: uip_ds6_nbr_lladdr_from_ipaddr
  0x20b639: uip_ds6_link_callback
  0x20b63b: chksum
  0x20b673: uip_icmp6chksum
  0x20b679: uip_udpchksum
  0x20b67f: uip_htonl
  0x20b691: rpl_nbr_gc_get_worst
  0x20b6af: rpl_neighbor_get_ipaddr
  0x20b6bd: rpl_neighbor_get_link_stats
  0x20b6cb: rpl_neighbor_is_fresh
  0x20b6d9: handle_state_update
  0x20b6dd: get_probing_delay
  0x20b6f7: handle_probing_timer
  0x20b71b: drop_route
  0x20b71d: neighbor_state_changed
  0x20b71f: rpl_lollipop_greater_than
  0x20b753: reset
  0x20b755: nbr_link_metric
  0x20b767: nbr_has_usable_link
  0x20b779: nbr_path_cost
  0x20b7a1: nbr_is_acceptable_parent
  0x20b7bf: get32
  0x20b7d7: set32
  0x20b7e9: get16
  0x20b7f5: set16
  0x20b7ff: rpl_icmp6_update_nbr_table
  0x20b82d: rpl_process_hbh
  0x20b848: als_sensor
  0x20b858: uart_regs
  0x20b8b0: cc2538_rf_driver
  0x20b8e8: output_power
  0x20b958: cc2538_temp_sensor
  0x20b968: vdd3_sensor
  0x20b978: ble_l2cap_driver
  0x20b994: sicslowpan_driver
  0x20b9a4: rpl_lite_driver
  0x20b9f8: autostart_processes
  0x20ba00: linkaddr_null
  0x20ba08: leds_arch_leds
  0x20bcc0: buffer.5647
  0x20bcd0: buffer.5656
  0x20bd7b: llprefix
  0x20bd7d: unc_llconf
  0x20bd81: unc_mxconf
  0x20bd90: ttl_values
  0x20bd94: unc_ctxconf
  0x20bea6: _etext
  0x20bea8: _ldata
  0x27ffd4: flash_cca_lock_page
  0x20000000: _enrdata
  0x20000040: _data
  0x20000050: sensors
  0x20000060: key_up
  0x200000b0: key_left
  0x20000100: key_select
  0x20000150: key_right
  0x200001a0: key_down
  0x200001f0: button_hal_buttons
  0x20000208: cc2538_rf_process
  0x20000218: curr_log_level_main
  0x2000021c: etimer_process
  0x2000022c: ctimer_process
  0x2000023c: stack_check_process
  0x2000024c: button_hal_process
  0x2000025c: serial_line_process
  0x2000026c: bufmem
  0x20000278: buframmem
  0x20000284: neighbor_addr_mem
  0x20000290: link_stats_struct
  0x200002a0: ctxt
  0x200002a8: ble_l2cap_tx_process
  0x200002b8: echo_request_handler
  0x200002c4: echo_reply_handler
  0x200002d0: nodememb
  0x200002dc: defaultroutermemb
  0x200002e8: ds6_neighbors_struct
  0x200002f8: tcpip_process
  0x20000308: ns_input_handler
  0x20000314: rpl_neighbors
  0x20000318: rpl_neighbors_struct
  0x20000328: rpl_mrhof
  0x2000034c: dao_ack_handler
  0x20000358: dis_handler
  0x20000364: dao_handler
  0x20000370: dio_handler
  0x2000037c: hello_world_process
  0x2000038c: send_on_cca
  0x2000038d: rf_channel
  0x2000038e: _edata
  0x20000390: _bss
  0x20000398: rt_ticks_epoch
  0x200003a0: events.5631
  0x200003a4: i.5630
  0x200003a8: next_trigger
  0x200003ac: input_handler
  0x200003b4: ioc_sel
  0x200003b8: ioc_over
  0x200003bc: notification_process
  0x200003c0: prev_MDMTEST1
  0x200003c4: prev_FRMCTRL0
  0x200003c8: periph_permit_pm1_funcs
  0x200003dc: notification_process
  0x200003e0: timerlist
  0x200003e4: next_expiration
  0x200003e8: ctimer_list_list
  0x200003ec: next_rtimer
  0x200003f0: process_current
  0x200003f4: process_list
  0x200003f8: events
  0x20000578: et.5974
  0x20000588: pmask
  0x2000058c: button_event_handlers
  0x20000598: rxbuf
  0x200005a0: ptr.5615
  0x200005a4: handlers_list
  0x200005a8: bufmem_memb_mem
  0x200005c8: nbr_table_keys_list
  0x200005cc: neighbor_addr_mem_memb_mem
  0x2000068c: all_tables
  0x200006ac: num_tables
  0x200006b0: packetbuf_aligned
  0x20000730: ip_processor_list_list
  0x20000734: _link_stats_mem
  0x200007f4: echo_reply_callback_list_list
  0x200007f8: input_handler_list_list
  0x200007fc: num_nodes
  0x20000800: nodememb_memb_mem
  0x20000980: nodelist_list
  0x20000984: locmaddr
  0x20000988: locprefix
  0x2000098c: locaddr
  0x20000990: defaultroutermemb_memb_mem
  0x200009d0: defaultrouterlist_list
  0x200009d4: periodic
  0x200009e4: nbr
  0x200009e8: nd6_opt_llao
  0x200009ec: addr
  0x200009f0: callback
  0x200009f4: context
  0x200009f8: last_rssi
  0x200009fc: packetbuf_ptr
  0x20000a00: iphc_ptr
  0x20000a04: last_tx_status
  0x20000a08: packetbuf_payload_len
  0x20000a0c: mac_max_payload
  0x20000a10: frag_info
  0x20000b80: _rpl_neighbors_mem
  0x20000c00: periodic_timer
  0x20000c20: dis_timer
  0x20000c40: timer.5584
  0x20000c50: node_id
  0x20000c52: buframmem_memb_mem
  0x200011b2: buflen
  0x200011b4: bufptr
  0x200011b6: l2cap_channels
  0x20001bd6: uipbuf_attrs
  0x20001be6: uipbuf_default_attrs
  0x20001bf6: tmp_ipaddr
  0x20001c06: default_prefix
  0x20001c16: loc_fipaddr
  0x20001c26: _ds6_neighbors_mem
  0x20001d46: uip_ext_len
  0x20001d48: lastport
  0x20001d4a: nd6_opt_offset
  0x20001d4c: my_tag
  0x20001d4e: root_ipaddr.7245
  0x20001d5e: num_sensors
  0x20001d5f: was_on
  0x20001d60: poll_mode
  0x20001d61: rf_flags
  0x20001d62: max_pm
  0x20001d63: initialized
  0x20001d64: fevent
  0x20001d65: nevents
  0x20001d66: poll_requested
  0x20001d67: lastevent
  0x20001d68: rxbuf_data
  0x20001de8: overflow.5608
  0x20001de9: buf.5614
  0x20001e69: buframmem_memb_used
  0x20001e71: bufmem_memb_used
  0x20001e79: locked_map
  0x20001e89: neighbor_addr_mem_memb_used
  0x20001e99: used_map
  0x20001ea9: hdrlen
  0x20001eaa: l2cap_channel_count
  0x20001eab: l2cap_tx_event
  0x20001eac: ble_addr
  0x20001eb2: nodememb_memb_used
  0x20001ec2: defaultroutermemb_memb_used
  0x20001ec4: uip_ext_bitmap
  0x20001ec5: uip_last_proto
  0x20001ec6: curr_page
  0x20001ec7: uncomp_hdr_len
  0x20001ec8: addr_contexts
  0x20001ed2: frag_buf
  0x2000241e: packetbuf_hdr_len
  0x2000241f: rpl_leaf_only
  0x20002420: initialized.7256
  0x20002424: periodic_timer
  0x20002444: uip_ds6_timer_ra
  0x2000244c: uip_ds6_if
  0x20002568: uip_ds6_netif_addr_list_offset
  0x20002569: uip_ds6_addr_size
  0x2000256c: uip_ds6_prefix_list
  0x200025cc: uip_ds6_timer_periodic
  0x200025dc: uip_len
  0x200025e0: uip_sappdata
  0x200025e4: uip_lladdr
  0x200025ec: uip_aligned_buf
  0x20002aec: uip_flags
  0x20002af0: uip_udp_conn
  0x20002af4: uip_appdata
  0x20002af8: uip_conn
  0x20002afc: uip_slen
  0x20002b00: uip_udp_conns
  0x20002c00: curr_instance
  0x20002d60: packetbuf_addrs
  0x20002d70: packetbuf_attrs
  0x20002d8a: linkaddr_node_addr
  0x20002d92: rpl_multicast_addr
  0x20002da2: sensors_event
  0x20002da3: sensors_flags
  0x20002da7: button_hal_release_event
  0x20002da8: button_hal_periodic_event
  0x20002da9: button_hal_press_event
  0x20002daa: serial_line_event_message
  0x20002dab: tcpip_event
  0x20002dac: _stack
  0x20002db0: stack
  0x200035b0: _heap
  0x20008000: _eheap
