interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  mmio_UDD:
    base_addr: 0x20180000
    permissions: rw-
    size: 0x20000
  flash:
    base_addr: 0xa0000
    permissions: rw-
    size: 0x20000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x80000
    file: GPSTrackerX.bin
    ivt_offset: 0x0
    permissions: r-x
    size: 0x1bc88
  internal_ROM:
    base_addr: 0x100000
    permissions: r-x
    size: 0x100000
symbols:
  0x0: __register_frame_info
  0x80000: exception_table
  0x800f5: __do_global_dtors_aux
  0x80119: frame_dummy
  0x80149: SysTick_Config
  0x80175: _Z11device_initv
  0x801b5: _Z16data_append_charc
  0x801d9: _Z18data_append_stringPKc
  0x8020d: _Z10data_resetv
  0x8022d: _Z20data_field_separatorc
  0x80245: _Z11is_url_safec
  0x80285: _Z18url_encoded_strlenPKc
  0x802b1: _Z19url_encoded_strlcpyPciPKc
  0x80311: _Z6gps_onv
  0x8032d: _Z7gps_offv
  0x80349: _Z16gsm_power_statusv
  0x8035d: _Z19gsm_is_final_resultPKci
  0x8055d: _Z10status_ledv
  0x8059d: _Z12status_delayl
  0x805cd: _Z11blink_startv
  0x805f9: _Z13blink_got_gpsv
  0x80625: _Z19usb_console_disablev
  0x80691: _Z19usb_console_restorev
  0x806b1: yield
  0x806b9: _Z13cpu_slow_downv
  0x806ed: _Z14cpu_full_speedv
  0x8070d: _Z13settings_savev
  0x80735: _Z13settings_loadv
  0x808d9: _Z20storage_save_currentv
  0x80921: _Z17storage_get_indexv
  0x8097d: _GLOBAL__sub_I__Z11addon_delayl
  0x80989: _Z8gps_openv
  0x80999: _Z8gps_initv
  0x809c5: _Z8gsm_openv
  0x809d5: _Z8gsm_initv
  0x80a21: _Z9gps_closev
  0x80a2d: _Z9gsm_closev
  0x80a39: _Z9gps_setupv
  0x80a79: _Z13gsm_read_linei
  0x80ac9: _Z13gsm_get_replyi
  0x80ae5: _Z12gsm_get_imeiv
  0x80b41: _Z11gsm_send_atv
  0x80b95: _Z18gsm_wait_for_replyiii
  0x80c15: _Z18gsm_wait_for_replyii
  0x80c1d: _Z7gsm_offi
  0x80c89: _Z6rebootv
  0x80cc1: _Z10kill_powerv
  0x80d1d: _Z10gsm_wakeupv
  0x80d61: _Z6gsm_onv
  0x80dcd: _Z12gsm_set_timev
  0x80e0d: _Z9parse_cmdPc
  0x80e6d: _Z11gsm_set_pinv
  0x80f09: _Z12gsm_get_timev
  0x80f71: _Z15gsm_startup_cmdv
  0x80fe1: _Z20gsm_get_modem_statusv
  0x8103d: _Z20gsm_wait_modem_readyi
  0x81069: _Z14gsm_disconnectv
  0x81089: _Z14gsm_deactivatev
  0x810bd: _Z11gsm_set_apnv
  0x811ad: _Z10gsm_configv
  0x811cb: _Z9gsm_setupv
  0x811e5: _Z25gsm_get_connection_statusv
  0x812bd: _Z11gsm_connectv
  0x813fd: _Z16gsm_validate_tcpv
  0x8145d: _Z14gsm_send_begini
  0x814ad: _Z13gsm_send_donev
  0x814d5: _Z21gsm_send_data_currentv
  0x81539: _Z21gsm_send_http_currentv
  0x81625: _Z19parse_receive_replyv
  0x81789: _Z13gsm_send_datav
  0x817d9: _Z17storage_send_logsi
  0x818ad: _Z9send_datav
  0x818f5: _Z12sms_send_msgPKcS0_
  0x8195d: _Z11sms_cmd_runPcS_
  0x81c69: _Z7sms_cmdPcS_
  0x81ca9: _Z9sms_checkv
  0x81df9: _Z19gsm_get_queclocatorv
  0x81e6d: _Z16collect_gps_datav
  0x8218d: _Z16collect_all_datai
  0x82295: loop
  0x82411: _Z14gsm_ntp_updatev
  0x824a1: setup
  0x82519: _ZN7TinyGPSC1Ev
  0x8256d: _ZN7TinyGPS5statsEPmPtS1_
  0x82587: _ZN7TinyGPS8from_hexEc
  0x825a7: _ZN7TinyGPS7gpsatolEPKc
  0x825c3: _ZN7TinyGPS13parse_decimalEv
  0x8261d: _ZN7TinyGPS13parse_degreesEv
  0x82685: _ZN7TinyGPS9gpsstrcmpEPKcS1_
  0x8269d: _ZN7TinyGPS13term_completeEv
  0x8284d: _ZN7TinyGPS6encodeEc
  0x828f9: _ZN7TinyGPS12get_positionEPlS0_Pm
  0x8291f: _ZN7TinyGPS12get_datetimeEPmS0_S0_
  0x82949: _ZN7TinyGPS14f_get_positionEPfS0_Pm
  0x829b1: _ZN7TinyGPS10f_altitudeEv
  0x829dd: _ZN7TinyGPS8f_courseEv
  0x82a09: _ZN7TinyGPS13f_speed_knotsEv
  0x82a39: _ZN7TinyGPS12f_speed_kmphEv
  0x82a79: _ZN15DueFlashStorageC2Ev
  0x82a9d: _ZN15DueFlashStorage4readEm
  0x82aa5: _ZN15DueFlashStorage11readAddressEm
  0x82aad: _ZN15DueFlashStorage5writeEmh
  0x82ae1: _ZN15DueFlashStorage5writeEmPhm
  0x82b29: translate_address
  0x82b65: flash_init
  0x82b8d: flash_write
  0x82c6d: _sbrk
  0x82c89: _Z11serialEventv
  0x82c8d: UART_Handler
  0x82c99: _Z12serialEvent1v
  0x82c9b: _Z12serialEvent2v
  0x82c9d: _Z12serialEvent3v
  0x82ca1: USART0_Handler
  0x82cad: USART1_Handler
  0x82cb9: USART2_Handler
  0x82cc5: init
  0x82ddd: _GLOBAL__sub_I_g_APinDescription
  0x82eb1: _Z14serialEventRunv
  0x82ef5: adc_init
  0x82f8d: adc_configure_trigger
  0x82fb7: adc_configure_timing
  0x82fd1: adc_disable_channel
  0x82fdb: adc_disable_all_channel
  0x82fe3: adc_disable_interrupt
  0x82fe7: WDT_Disable
  0x82ff1: WDT_Restart
  0x82ffd: rstc_start_software_reset
  0x83009: pmc_mck_set_prescaler
  0x83021: pmc_switch_mainck_to_fastrc
  0x8308d: pmc_enable_upll_clock
  0x830a1: pmc_disable_upll_clock
  0x830b1: pmc_enable_periph_clk
  0x830f5: pmc_disable_periph_clk
  0x83135: pmc_disable_all_periph_clk
  0x8315d: pmc_switch_udpck_to_upllck
  0x83171: pmc_enable_udpck
  0x8317d: pmc_disable_udpck
  0x83189: pmc_enable_sleepmode
  0x831b1: pmc_enable_waitmode
  0x831e5: pmc_set_writeprotect
  0x83201: efc_init
  0x8320f: efc_set_wait_state
  0x83221: efc_get_wait_state
  0x83229: efc_perform_command
  0x83275: PIO_PullUp
  0x8327f: PIO_Get
  0x83293: PIO_SetPeripheral
  0x832b9: PIO_SetInput
  0x832df: PIO_SetOutput
  0x83305: PIO_Configure
  0x83369: PIO_GetOutputDataStatus
  0x8337d: UDD_SetStack
  0x83389: UDD_Init
  0x83459: UDD_Attach
  0x834a9: UDD_Detach
  0x834b9: UDD_InitEP
  0x834e5: UDD_InitEndpoints
  0x83521: UDD_WaitIN
  0x83531: UDD_WaitOUT
  0x83541: UDD_ClearIN
  0x83559: UDD_ClearOUT
  0x83571: UDD_ReceivedSetupInt
  0x83581: UDD_ClearSetupInt
  0x83591: UDD_Send
  0x83619: UDD_Send8
  0x8363d: UDD_Recv8
  0x83665: UDD_Recv
  0x83699: UDD_Stall
  0x836ad: UDD_FifoByteCount
  0x836c1: UDD_ReleaseRX
  0x836e9: UDD_ReleaseTX
  0x83711: UDD_SetAddress
  0x83731: SystemInit
  0x837b9: SystemCoreClockUpdate
  0x83889: Reset_Handler
  0x83901: UOTGHS_Handler
  0x83911: PIOA_Handler
  0x83949: PIOB_Handler
  0x83981: SPI0_Handler
  0x83983: SVC_Handler
  0x83987: PendSV_Handler
  0x8398b: SysTick_Handler
  0x839a1: sysTickHook
  0x839a5: svcHook
  0x839a7: ltoa
  0x83a15: itoa
  0x83a19: millis
  0x83a1d: delay
  0x83a39: analogOutputInit
  0x83a3d: pinMode
  0x83b45: digitalWrite
  0x83bb5: digitalRead
  0x83bf9: _ZN5Print5writeEPKhj
  0x83c1b: _ZN5Print5writeEPKc
  0x83c39: _ZN5Print5printEPKc
  0x83c41: _ZN5Print5printEc
  0x83c4b: _ZN5Print11printNumberEmh
  0x83c89: _ZN5Print5printEli
  0x83cc5: _ZN5Print5printEii
  0x83cc9: initiateReset
  0x83cd5: cancelReset
  0x83ce5: tickReset
  0x83d05: _ZN10RingBufferC2Ev
  0x83d21: _ZN10RingBuffer10store_charEh
  0x83d3d: _ZN9UARTClasscvbEv
  0x83d41: _ZN9UARTClass9availableEv
  0x83d51: _ZN9UARTClass4peekEv
  0x83d6d: _ZN9UARTClass4readEv
  0x83d95: _ZN9UARTClass5flushEv
  0x83dad: _ZN9UARTClass5writeEh
  0x83e01: _ZN9UARTClass3endEv
  0x83e3d: _ZN9UARTClassC2EP4Uart4IRQnmP10RingBufferS4_
  0x83e61: _ZN9UARTClass4initEmm
  0x83ed1: _ZN9UARTClass5beginEm
  0x83ed9: _ZN9UARTClass10IrqHandlerEv
  0x83f31: _ZN10USARTClass5beginEm
  0x83f39: _ZN10USARTClassC2EP5Usart4IRQnmP10RingBufferS4_
  0x83f5d: _ZN7Serial_17availableForWriteEv
  0x83f65: _ZN7Serial_4peekEv
  0x83f95: _ZN7Serial_5writeEh
  0x83fad: _ZN7Serial_4readEv
  0x84001: _ZN7Serial_5flushEv
  0x84019: _ZN7Serial_9availableEv
  0x84041: _ZN7Serial_6acceptEv
  0x840c1: _ZN7Serial_5writeEPKhj
  0x840fd: _Z16CDC_GetInterfacePh
  0x84111: _Z21CDC_GetOtherInterfacePh
  0x84125: _Z9CDC_SetupR8USBSetup
  0x8419d: _ZN7Serial_5beginEm
  0x841a1: _GLOBAL__sub_I_cdc_rx_buffer
  0x841bd: _ZL11USB_SendZlpv
  0x841dd: _Z14USBD_Availablem
  0x84209: _Z9USBD_RecvmPvm
  0x84285: _Z9USBD_Recvm
  0x842a9: _Z9USBD_SendmPKvm
  0x842f5: _Z16USBD_SendControlhPKvm
  0x84335: _ZL24USB_SendStringDescriptorPKhi
  0x84399: _Z16USBD_RecvControlPvm
  0x843b5: _Z26USBD_ClassInterfaceRequestR8USBSetup
  0x843d3: _Z19USBD_SendInterfacesv
  0x843f5: _Z24USBD_SendOtherInterfacesv
  0x84417: _Z10USBD_Flushm
  0x8442d: _ZN10USBDevice_C1Ev
  0x84451: _ZN10USBDevice_6attachEv
  0x84471: _GLOBAL__sub_I_EndPoints
  0x8447d: _ZL7USB_ISRv
  0x848d1: initVariant
  0x848d5: main
  0x8490d: _watchdogDefaultSetup
  0x84919: _ZN13PluggableUSB_12getInterfaceEPh
  0x84941: _ZN13PluggableUSB_13getDescriptorER8USBSetup
  0x8495d: _ZN13PluggableUSB_12getShortNameEPc
  0x84979: _ZN13PluggableUSB_5setupER8USBSetup
  0x84999: _Z12PluggableUSBv
  0x849c1: TimeTick_Increment
  0x849d1: GetTickCount
  0x849dd: __fpclassifyd
  0x84a2d: __aeabi_drsub
  0x84a35: __subdf3
  0x84a39: __aeabi_dadd
  0x84cb1: __floatunsidf
  0x84cd1: __aeabi_i2d
  0x84cf5: __aeabi_f2d
  0x84d31: __floatundidf
  0x84d41: __aeabi_l2d
  0x84d9d: __muldf3
  0x84ff1: __divdf3
  0x851c1: __gedf2
  0x851c9: __ledf2
  0x851d1: __nedf2
  0x8524d: __aeabi_cdrcmple
  0x8525d: __aeabi_cdcmpeq
  0x8526d: __aeabi_dcmpeq
  0x85281: __aeabi_dcmplt
  0x85295: __aeabi_dcmple
  0x852a9: __aeabi_dcmpge
  0x852bd: __aeabi_dcmpgt
  0x852d1: __aeabi_d2iz
  0x85321: __truncdfsf2
  0x853c1: __gesf2
  0x853c9: __ltsf2
  0x853d1: __cmpsf2
  0x85431: __aeabi_cfrcmple
  0x85439: __aeabi_cfcmpeq
  0x85449: __aeabi_fcmpeq
  0x8545d: __aeabi_fcmplt
  0x85471: __aeabi_fcmple
  0x85485: __aeabi_fcmpge
  0x85499: __aeabi_fcmpgt
  0x854ad: atoi
  0x854b5: atol
  0x854bd: __libc_init_array
  0x8550d: memcpy
  0x855f9: memset
  0x8568d: snprintf
  0x856f5: sprintf
  0x85741: strchr
  0x85835: strcmp
  0x85a71: strlcat
  0x85acd: strlcpy
  0x85b09: strlen
  0x85b69: strncmp
  0x85c1d: critical_factorization
  0x85cd9: two_way_long_needle
  0x85ec5: strstr
  0x860c5: strtok
  0x860d5: __strtok_r
  0x86139: strtok_r
  0x86141: _strtol_r
  0x86255: strtol
  0x8626d: _svfprintf_r
  0x8774d: register_fini
  0x87761: atexit
  0x8776d: quorem
  0x878a1: _dtoa_r
  0x886d9: __libc_fini_array
  0x88709: _malloc_trim_r
  0x887a5: _free_r
  0x8893d: _localeconv_r
  0x88945: _malloc_r
  0x88e7d: memchr
  0x88f11: memcmp
  0x88f79: memmove
  0x89045: __malloc_lock
  0x89049: __malloc_unlock
  0x8904d: _Balloc
  0x89099: _Bfree
  0x890ad: __multadd
  0x89141: __hi0bits
  0x89181: __lo0bits
  0x891dd: __i2b
  0x891f1: __multiply
  0x8932d: __pow5mult
  0x893c9: __lshift
  0x89485: __mcmp
  0x894cd: __mdiff
  0x895a5: __d2b
  0x89661: _realloc_r
  0x89a21: _sbrk_r
  0x89a45: __ssprint_r
  0x89b45: __register_exitproc
  0x89bed: _calloc_r
  0x89c4d: __aeabi_uldivmod
  0x89c79: __gnu_ldivmod_helper
  0x89ca9: __gnu_uldivmod_helper
  0x89cd9: __aeabi_idiv0
  0x89cdd: __divdi3
  0x89f7d: __udivdi3
  0x8a7ec: _ZZ6to_hexiE3hex
  0x8a7fd: _ZL12HTTP_HEADER1
  0x8a873: _ZL12HTTP_HEADER2
  0x8a8a8: _ZN7TinyGPS19GPS_INVALID_F_SPEEDE
  0x8a8ac: _ZN7TinyGPS22GPS_INVALID_F_ALTITUDEE
  0x8a8dc: _ZN7TinyGPS19GPS_INVALID_F_ANGLEE
  0x8a944: g_APinDescription
  0x8af38: _ZTV9UARTClass
  0x8af68: _ZTV10USARTClass
  0x8af98: _ZTV7Serial_
  0x8afc0: _ZL18_cdcOtherInterface
  0x8b002: _ZL13_cdcInterface
  0x8b044: STRING_PRODUCT
  0x8b058: USB_DeviceDescriptor
  0x8b06a: STRING_LANGUAGE
  0x8b06e: _ZL18test_packet_buffer
  0x8b0a3: STRING_MANUFACTURER
  0x8b0ab: USB_DeviceDescriptorA
  0x8b0bd: _ZL19USB_DeviceQualifier
  0x8b0cc: _global_impure_ptr
  0x8b0d0: zeroes.6760
  0x8b124: blanks.6759
  0x8b134: _ctype_
  0x8b258: __mprec_tens
  0x8b320: __mprec_bigtens
  0x8b348: p05.5266
  0x8b355: _init
  0x8b360: __preinit_array_start
  0x8b364: __frame_dummy_init_array_entry
  0x8b378: __init_array_end
  0x8b379: _fini
  0x8b384: __fini_array_start
  0x8b388: _efixed
  0x8b390: _etext
  0x20078000: _srelocate
  0x20078001: banzai
  0x2007802c: SEND_DATA
  0x20078030: last_time_gps
  0x20078034: engineRunning
  0x20078038: logindex
  0x2007803c: led_interval
  0x20078040: g_interrupt_enabled
  0x20078044: SystemCoreClock
  0x20078048: _ZL5ticks
  0x2007804c: _ZL10breakValue
  0x20078050: _ZL12_usbLineInfo
  0x20078058: EndPoints
  0x20078080: impure_data
  0x200784a8: _impure_ptr
  0x200784ac: __ctype_ptr__
  0x200784b0: lconv
  0x200784e8: __malloc_av_
  0x200788f0: __malloc_trim_threshold
  0x200788f4: __malloc_sbrk_base
  0x200788f8: _erelocate
  0x200788fc: object.7862
  0x20078914: ledState
  0x20078918: data_sep_flag
  0x2007891c: last_date_gps
  0x20078920: previousMillis
  0x20078924: data_current
  0x200792e9: lon_current
  0x200792f8: last_fix_gps
  0x200792fc: engine_start
  0x20079300: gsm_reply_failures
  0x20079304: lat_current
  0x20079313: save_config
  0x20079314: time_char
  0x2007932c: config
  0x200793e8: interval_count
  0x200793ec: time_stop
  0x200793f0: power_reboot
  0x200793f1: modem_reply
  0x200794b9: _ZZ21gsm_send_data_currentvE3buf
  0x20079a34: sms_check_count
  0x20079a38: gsm_clock_was_set
  0x20079a3c: time_start
  0x20079a40: data_index
  0x20079a44: power_cutoff
  0x20079a45: dueFlashStorage
  0x20079a48: gsm_send_failures
  0x20079a4c: engineRunningTime
  0x20079a50: time_diff
  0x20079a54: _ZL17gs_ul_page_buffer
  0x20079b54: heap.6305
  0x20079b58: tx_buffer2
  0x20079c60: tx_buffer1
  0x20079d68: Serial
  0x20079d8c: rx_buffer1
  0x20079e94: Serial1
  0x20079ebc: Serial2
  0x20079ee4: Serial3
  0x20079f0c: tx_buffer3
  0x2007a014: tx_buffer4
  0x2007a11c: g_pinStatus
  0x2007a144: rx_buffer2
  0x2007a24c: rx_buffer3
  0x2007a354: rx_buffer4
  0x2007a45c: iap_perform_command.6591
  0x2007a460: ul_recv_fifo_ptr
  0x2007a488: ul_send_fifo_ptr
  0x2007a4b0: gpf_isr
  0x2007a4b4: callbacksPioA
  0x2007a534: callbacksPioB
  0x2007a5b4: cdc_rx_buffer
  0x2007a7bc: _ZZN7Serial_6acceptEvE5guard
  0x2007a7c0: SerialUSB
  0x2007a7d4: _cmark
  0x2007a7d6: _ZL14isEndpointHalt
  0x2007a7d8: _cdcComposite
  0x2007a7dc: _ZL21isRemoteWakeUpEnabled
  0x2007a7e0: _usbInitialized
  0x2007a7e4: USBDevice
  0x2007a7e8: _usbSetInterface
  0x2007a7ec: _cend
  0x2007a7f0: _usbConfiguration
  0x2007a7f4: _ZZ12PluggableUSBvE3obj
  0x2007a7fc: _ZGVZ12PluggableUSBvE3obj
  0x2007a800: _dwTickCount
  0x2007a804: __malloc_max_total_mem
  0x2007a808: __malloc_max_sbrked_mem
  0x2007a80c: __malloc_top_pad
  0x2007a810: __malloc_current_mallinfo
  0x2007a838: errno
  0x2007a83c: _end
  0x20088000: _estack
