interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  dynamically_added_crash_region_080407fe:
    base_addr: 0x803b000
    permissions: rw-
    size: 0xa000
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x8000000
    file: hoverX.bin
    ivt_offset: 0x0
    permissions: r-x
    size: 0x1e7d4
symbols:
  0x0: reent.c
  0x200: _Min_Heap_Size
  0x400: _Min_Stack_Size
  0x800: _Reserved_Space
  0x8000000: g_pfnVectors
  0x80001e9: deregister_tm_clones
  0x8000205: register_tm_clones
  0x8000229: __do_global_dtors_aux
  0x8000251: frame_dummy
  0x8000271: atoi
  0x8000279: _atoi_r
  0x8000281: calloc
  0x8000291: __libc_init_array
  0x80002d9: malloc
  0x80002e9: free
  0x80002f9: memcpy
  0x80003e5: memset
  0x8000485: _calloc_r
  0x80004a1: _free_r
  0x8000549: _malloc_r
  0x8000611: _sbrk_r
  0x8000635: _snprintf_r
  0x80006b5: sniprintf
  0x800073d: _sprintf_r
  0x8000779: siprintf
  0x80007bd: siscanf
  0x8000815: _sscanf_r
  0x800086d: __sread
  0x8000891: __seofread
  0x8000895: __swrite
  0x80008d5: __sseek
  0x80008f5: __sclose
  0x80008fd: strcat
  0x800093d: strcpy
  0x80009f9: strlen
  0x8000a55: strncmp
  0x8000af5: strncpy
  0x8000b69: _strtol_l.isra.0
  0x8000ca1: _strtol_r
  0x8000ca5: strtol_l
  0x8000cb9: strtol
  0x8000ccd: _write_r
  0x8000cf9: _close_r
  0x8000d1d: __errno
  0x8000d29: _lseek_r
  0x8000d55: __malloc_lock
  0x8000d59: __malloc_unlock
  0x8000d5d: __ssputs_r
  0x8000e21: __ssprint_r
  0x8000f19: _svfiprintf_r
  0x8001191: _sungetc_r
  0x800120d: __ssrefill_r
  0x8001249: __ssvfiscanf_r
  0x80015ad: _printf_common
  0x80016d5: _printf_i
  0x8001969: _scanf_chars
  0x8001a29: _scanf_i
  0x8001c2d: _read_r
  0x8001c59: __sccl
  0x8001cc9: _strtoul_l.isra.0
  0x8001e09: _strtoul_r
  0x8001e0d: strtoul_l
  0x8001e21: strtoul
  0x8001e35: __submore
  0x8001ead: _ungetc_r
  0x8001f99: ungetc
  0x8001fa9: __sflush_r
  0x80020d5: _fflush_r
  0x8002135: fflush
  0x8002159: __fp_lock
  0x800215d: _cleanup_r
  0x8002169: __fp_unlock
  0x800216d: __sfmoreglue
  0x800219d: __sfp
  0x8002221: __sinit.part.0
  0x8002315: _cleanup
  0x8002329: __sinit
  0x8002331: __sfp_lock_acquire
  0x8002335: __sfp_lock_release
  0x8002339: __sinit_lock_acquire
  0x800233d: __sinit_lock_release
  0x8002341: __fp_lock_all
  0x8002355: __fp_unlock_all
  0x8002369: _fwalk
  0x80023b1: _fwalk_reent
  0x8002401: memchr
  0x800248d: memmove
  0x8002559: _realloc_r
  0x80025a5: _malloc_usable_size_r
  0x80025b5: cos
  0x8002645: sin
  0x80026d9: __ieee754_rem_pio2
  0x8002b11: __kernel_cos
  0x8002d59: __kernel_rem_pio2
  0x8003599: __kernel_sin
  0x8003705: fabs
  0x8003711: floor
  0x8003819: scalbn
  0x800390d: _close
  0x800391d: _lseek
  0x800392d: _read
  0x800393d: _sbrk
  0x8003959: _write
  0x8003969: __aeabi_drsub
  0x8003971: __subdf3
  0x8003975: __aeabi_dadd
  0x8003bed: __floatunsidf
  0x8003c0d: __aeabi_i2d
  0x8003c31: __aeabi_f2d
  0x8003c75: __floatundidf
  0x8003c85: __aeabi_l2d
  0x8003ce1: __muldf3
  0x8003f35: __divdf3
  0x8004105: __gedf2
  0x800410d: __ledf2
  0x8004115: __nedf2
  0x8004191: __aeabi_cdrcmple
  0x80041a1: __aeabi_cdcmpeq
  0x80041b1: __aeabi_dcmpeq
  0x80041c5: __aeabi_dcmplt
  0x80041d9: __aeabi_dcmple
  0x80041ed: __aeabi_dcmpge
  0x8004201: __aeabi_dcmpgt
  0x8004215: __aeabi_d2iz
  0x8004265: __truncdfsf2
  0x8004305: __aeabi_frsub
  0x800430d: __aeabi_fsub
  0x8004311: __addsf3
  0x8004471: __floatunsisf
  0x8004479: __floatsisf
  0x8004495: __aeabi_ul2f
  0x80044a5: __aeabi_l2f
  0x8004521: __aeabi_fmul
  0x8004689: __aeabi_fdiv
  0x80047c1: __gesf2
  0x80047c9: __ltsf2
  0x80047d1: __cmpsf2
  0x8004831: __aeabi_cfrcmple
  0x8004839: __aeabi_cfcmpeq
  0x8004849: __aeabi_fcmpeq
  0x800485d: __aeabi_fcmplt
  0x8004871: __aeabi_fcmple
  0x8004885: __aeabi_fcmpge
  0x8004899: __aeabi_fcmpgt
  0x80048ad: __aeabi_f2iz
  0x80048f9: __aeabi_uldivmod
  0x8004929: __udivmoddi4
  0x8004bed: __aeabi_idiv0
  0x8004bf1: FLASH_Program_HalfWord
  0x8004c0d: FLASH_SetErrorCode
  0x8004c7d: HAL_FLASH_Unlock
  0x8004ca5: HAL_FLASH_Lock
  0x8004cb9: FLASH_WaitForLastOperation
  0x8004d21: HAL_FLASH_Program
  0x8004dbd: RCC_Delay
  0x8004de9: HAL_RCC_OscConfig
  0x80051c9: HAL_RCC_GetSysClockFreq
  0x8005235: HAL_RCC_ClockConfig
  0x80053b1: HAL_RCC_GetHCLKFreq
  0x80053bd: HAL_RCC_GetPCLK1Freq
  0x80053dd: HAL_RCC_GetPCLK2Freq
  0x80053fd: TIM_OC1_SetConfig
  0x8005465: TIM_OC3_SetConfig
  0x80054d5: TIM_OC4_SetConfig
  0x8005525: TIM_TI1_ConfigInputStage
  0x8005549: TIM_TI2_ConfigInputStage
  0x800556f: TIM_ETR_SetConfig
  0x8005585: TIM_SlaveTimer_SetConfig
  0x80055f9: HAL_TIM_Base_MspInit
  0x80055fb: HAL_TIM_Base_Start
  0x8005615: HAL_TIM_PWM_MspInit
  0x8005617: HAL_TIM_SlaveConfigSynchronization
  0x8005659: TIM_Base_SetConfig
  0x80056f1: HAL_TIM_Base_Init
  0x8005725: HAL_TIM_PWM_Init
  0x8005759: TIM_OC2_SetConfig
  0x80057c9: HAL_TIM_PWM_ConfigChannel
  0x80058a5: TIM_CCxChannelCmd
  0x80058c5: HAL_TIM_PWM_Start
  0x80058fd: TIM_CCxNChannelCmd
  0x800591b: HAL_TIMEx_PWMN_Start
  0x800593f: HAL_TIMEx_ConfigBreakDeadTime
  0x8005997: HAL_TIMEx_MasterConfigSynchronization
  0x80059e9: HAL_ADCEx_MultiModeConfigChannel
  0x8005a41: HAL_NVIC_SetPriorityGrouping
  0x8005a65: HAL_NVIC_SetPriority
  0x8005acd: HAL_NVIC_EnableIRQ
  0x8005ae5: HAL_NVIC_DisableIRQ
  0x8005afd: HAL_NVIC_SystemReset
  0x8005b21: HAL_SYSTICK_Config
  0x8005b4d: HAL_SYSTICK_CLKSourceConfig
  0x8005b6d: HAL_SYSTICK_Callback
  0x8005b6f: HAL_SYSTICK_IRQHandler
  0x8005b79: FLASH_MassErase
  0x8005b9d: FLASH_PageErase
  0x8005bc1: HAL_FLASHEx_Erase
  0x8005c65: HAL_GPIO_Init
  0x8005e9d: HAL_GPIO_ReadPin
  0x8005eab: HAL_GPIO_WritePin
  0x8005eb7: HAL_GPIO_TogglePin
  0x8005ec1: HAL_RCCEx_PeriphCLKConfig
  0x8005fd5: HAL_MspInit
  0x8005fd9: HAL_InitTick
  0x8006005: HAL_Init
  0x8006029: HAL_IncTick
  0x8006039: HAL_GetTick
  0x8006045: HAL_Delay
  0x8006069: HAL_ADC_MspInit
  0x800606d: HAL_ADC_ConfigChannel
  0x80061a5: ADC_Enable
  0x8006221: HAL_ADC_Start
  0x8006309: ADC_ConversionStop_Disable
  0x8006355: HAL_ADC_Init
  0x8006479: UART_SetConfig
  0x8006625: HAL_UART_MspInit
  0x8006627: HAL_UART_Init
  0x8006685: SystemInit
  0x80066d1: USART2_IT_init
  0x80067c9: MX_GPIO_Init
  0x8006a0d: MX_TIM_Init
  0x8006bfd: MX_ADC1_Init
  0x8006d2d: MX_ADC2_Init
  0x8006de1: poweroff
  0x8006e49: init_PID_control
  0x8006f9d: change_PID_constants
  0x800707d: init_flash_content
  0x80070cd: check_power_button
  0x80071c9: SystemClock_Config
  0x8007259: main
  0x8007dc1: BldcController_Init
  0x8007ec9: DMA1_Channel1_IRQHandler
  0x80084e1: readADCs
  0x80087fd: setScopeChannel
  0x8008809: consoleScope
  0x800880d: USART2_IT_starttx
  0x8008821: serial_usart_buffer_count
  0x8008835: serial_usart_buffer_push
  0x8008875: USART2_IT_send
  0x80088b9: serial_usart_buffer_pop
  0x80088ed: USART2_IT_IRQ
  0x8008935: HallInterruptinit
  0x8008a3d: HallGetuS
  0x8008a95: HallInterruptsInterrupt
  0x8008d15: TIM4_IRQHandler
  0x8008d99: writeFlash
  0x8008f0d: readFlash
  0x8008fa1: NMI_Handler
  0x8008fa3: HardFault_Handler
  0x8008fa5: MemManage_Handler
  0x8008fa7: BusFault_Handler
  0x8008fa9: UsageFault_Handler
  0x8008fab: SVC_Handler
  0x8008fad: DebugMon_Handler
  0x8008faf: PendSV_Handler
  0x8008fb1: SysTick_Handler
  0x8008fbd: EXTI0_IRQHandler
  0x8008fc9: EXTI1_IRQHandler
  0x8008fd5: EXTI2_IRQHandler
  0x8008fe1: EXTI3_IRQHandler
  0x8008fed: EXTI4_IRQHandler
  0x8008ff9: EXTI9_5_IRQHandler
  0x800906d: EXTI15_10_IRQHandler
  0x80090f9: USART2_IRQHandler
  0x8009109: pid_need_compute
  0x8009121: pid_compute
  0x80091cd: pid_tune
  0x8009251: pid_limits
  0x80092b7: pid_auto
  0x80092f7: pid_direction
  0x8009331: pid_create
  0x8009375: getChange
  0x8009383: computeAngularVelocities
  0x8009439: DeadReckoner
  0x80094a9: getXYT
  0x80094fd: computePosition
  0x800968d: reset
  0x80096b1: noTick
  0x80096b5: noDelay
  0x80096b7: noReset
  0x80096b9: nosend
  0x80096bd: fn_ping
  0x80096d5: protocol_process_ReadValue
  0x800970d: protocol_process_ReadAndSendValue
  0x800974d: protocol_process_WriteValue
  0x8009791: protocol_process_cmdWritevalAndRespond
  0x80097c9: fn_defaultProcessing
  0x80097f7: fn_defaultProcessingPreWriteClear
  0x8009823: fn_SubscribeData
  0x80098bd: fn_ProtocolcountDataSum
  0x8009975: fn_ProtocolcountDataAck
  0x80099c9: fn_ProtocolcountDataNoack
  0x8009a1d: fn_defaultProcessingReadOnly
  0x8009a31: fn_paramstat_descriptions
  0x8009b39: setParam
  0x8009b59: setParamsCopy
  0x8009bb5: setParamVariable
  0x8009be9: setParamHandler
  0x8009c01: protocol_init
  0x8009c9d: protocol_process_message
  0x8009e31: mpGetTxByte
  0x8009e65: mpPutTx
  0x8009e85: protocol_cobsr_decode
  0x8009ec3: protocol_cobsr_encode
  0x8009eed: protocol_SOM_decode
  0x8009f09: protocol_SOM_encode
  0x8009f37: protocol_send_raw
  0x8009fa1: protocol_send_ack
  0x8009fd3: protocol_send_nack
  0x800a011: mpTxQueued
  0x800a033: mpGetTxMsg
  0x800a081: protocol_send
  0x800a219: protocol_tick
  0x800a35d: protocol_byte
  0x800a619: protocol_post
  0x800a68b: protocol_send_text
  0x800a6f9: line_lock_ascii
  0x800a725: line_unlock_ascii
  0x800a7b9: line_help
  0x800a859: ascii_add_immediate
  0x800a889: ascii_add_line_fn
  0x800a8b9: ascii_byte
  0x800aa4d: ascii_init
  0x800aa9d: cobsr_encode
  0x800ab53: cobsr_decode
  0x800ac3b: line_toggle_sensor_control
  0x800ac41: immediate_dir
  0x800b149: immediate_stop
  0x800b1c1: immediate_quit
  0x800b245: immediate_hall
  0x800b2bd: immediate_sensors
  0x800b2e1: line_sensors
  0x800b2ed: immediate_electrical
  0x800b3cd: line_electrical
  0x800b3d9: immediate_stm32
  0x800b429: line_stm32
  0x800b435: line_main_timing_stats
  0x800b465: immediate_toggle_control
  0x800b4a9: line_debug_control
  0x800b509: line_immediate
  0x800b649: line_set_alarm
  0x800b6c9: line_generic_var
  0x800b915: line_poweroff_control
  0x800b9d9: line_reset_firmware
  0x800ba25: line_test_message
  0x800ba99: line_read_memory
  0x800bb55: get_F_description
  0x800bbf1: main_ascii_init
  0x800bd9d: fn_enable
  0x800be19: fn_SpeedData
  0x800be41: fn_Position
  0x800be99: fn_PositionIncr
  0x800bf05: fn_RawPosition
  0x800bf5d: fn_PWMData
  0x800bff5: fn_BuzzerData
  0x800c051: fn_FlashContentMaxCurrLim
  0x800c08d: fn_xytPosn
  0x800c0b5: fn_FlashContentPID
  0x800c0cd: setup_protocol
  0x800c445: consoleLog
  0x800c465: fn_FlashContentMagic
  0x800c4bd: BLDC_controller_step
  0x800cb55: BLDC_controller_initialize
  0x800cb6d: Reset_Handler
  0x800cb70: CopyDataInit
  0x800cb78: LoopCopyDataInit
  0x800cb86: FillZerobss
  0x800cb8c: LoopFillZerobss
  0x800cbb4: Default_Handler
  0x800cbb5: DMA2_Channel3_IRQHandler
  0x800cbb8: __EH_FRAME_BEGIN__
  0x800cbb9: _init
  0x800cbc5: _fini
  0x800cbd0: _etext
  0x800cbd8: _global_impure_ptr
  0x800cbdc: _ctype_
  0x800ccec: __sf_fake_stderr
  0x800cd0c: __sf_fake_stdout
  0x800cd2c: __sf_fake_stdin
  0x800cd4c: npio2_hw
  0x800cdcc: two_over_pi
  0x800ced8: init_jk
  0x800cee8: PIo2
  0x800cf3c: AHBPrescTable
  0x800cf4c: APBPrescTable
  0x800d088: FlashDefaults
  0x800d104: hall_to_pos
  0x800d10c: increments
  0x800d4f0: initialparams
  0x800e204: control_types
  0x800e2b4: __exidx_start
  0x800e2bc: __exidx_end
  0x800e2c0: __init_array_end
  0x800e2c4: _sidata
  0x800e7d4: _sdata_ramfuncs
  0x20000000: _impure_ptr
  0x20000004: impure_data
  0x20000064: SystemCoreClock
  0x20000068: adc_buffers
  0x20000178: input_timeout_counter
  0x2000017c: BldcControllerParams
  0x20000198: batteryVoltage
  0x2000019c: electrical_measurements
  0x20000214: debug_out
  0x20000215: enablescope
  0x20000218: WheelSize_mm
  0x2000021c: flash_data
  0x20000220: flashlen
  0x20000224: protocol_Delay
  0x20000228: protocol_GetTick
  0x2000022c: protocol_SystemReset
  0x20000230: version
  0x20000234: password
  0x20000240: PWMData
  0x20000254: PosnData
  0x20000274: SpeedData
  0x20000298: rtConstP
  0x200004ac: rtP
  0x20000510: _edata
  0x20000514: object.6742
  0x2000052c: __malloc_free_list
  0x20000530: __malloc_sbrk_start
  0x20000534: heap_end.4192
  0x20000538: USART2WordLength
  0x2000053c: ADCcontrolActive
  0x20000540: PositionPidFloats
  0x20000560: SpeedPidFloats
  0x20000580: autoSensorBaud2
  0x20000584: buzzerLen
  0x20000588: control_type
  0x2000058c: debug_counter
  0x20000590: disablepoweroff
  0x20000594: dspeeds
  0x2000059c: powerofftimer
  0x200005a0: pwms
  0x200005a8: sensor_control
  0x200005ac: bldc_count
  0x200005b0: bldc_count_per_hall_counter
  0x200005b8: bldc_counter
  0x200005c0: buzzerFreq
  0x200005c4: buzzerPattern
  0x200005c8: buzzerTimer
  0x200005cc: enable
  0x200005d0: offsetcount
  0x200005d4: pwml
  0x200005d8: pwmr
  0x200005dc: bldc_count_per_hall
  0x200005e8: now_us
  0x200005f0: timerwraps
  0x200005f8: ProtocolcountData
  0x2000061c: immediate_functions
  0x20000e1c: line_functions
  0x2000161c: speedB
  0x20001620: steerB
  0x20001624: BuzzerData
  0x20001628: protocol_enable
  0x20001630: pFlash
  0x20001650: uwTick
  0x20001654: hdma_usart2_rx
  0x20001698: huart3
  0x200016d8: hadc2
  0x20001708: hi2c2
  0x2000175c: htim_right
  0x2000179c: hdma_i2c2_rx
  0x200017e0: hdma_i2c2_tx
  0x20001824: hadc1
  0x20001854: hdma_usart2_tx
  0x20001898: adc_buffer
  0x200018b0: huart2
  0x200018f0: htim_left
  0x20001930: adctFiltered
  0x20001938: SpeedPid
  0x200019a0: xytPosn
  0x200019ac: button2_ADC
  0x200019b0: inactivity_timeout_counter
  0x200019b4: power_button_info
  0x200019c0: button1_ADC
  0x200019c4: PositionPid
  0x20001a2c: deadreconer
  0x20001a30: FlashContent
  0x20001a78: adcrFiltered
  0x20001a80: button2
  0x20001a84: cmd2
  0x20001a88: steer
  0x20001a8c: speed
  0x20001a90: button1
  0x20001a98: cmd2_ADC
  0x20001aa0: cmd1
  0x20001aa8: cmd1_ADC
  0x20001ab0: rtY_Right
  0x20001ac4: rtDW_Left
  0x20001ae8: rtY_Left
  0x20001afc: rtU_Right
  0x20001b04: rtDW_Right
  0x20001b28: rtU_Left
  0x20001b30: rtM_Right_
  0x20001b40: rtM_Left_
  0x20001b50: usart2_it_TXbuffer
  0x20001f5c: uart_buf
  0x20001fc0: usart2_it_RXbuffer
  0x200023cc: ch_buf
  0x200023e0: hall_wl
  0x200023e1: hall_vl
  0x200023e8: timeStats
  0x20002470: hall_wr
  0x20002474: local_hall_params
  0x200024d6: hall_vr
  0x200024d7: hall_ul
  0x200024d8: hall_ur
  0x200024dc: HallData
  0x20002524: h_timer_hall
  0x20002564: contentbuf
  0x20002664: paramstat_descriptions
  0x20002764: Position
  0x20002774: sUSART2
  0x200039c8: RawPosition
  0x200039d8: PositionIncr
  0x200039e0: errno
  0x200039e4: __bss_end__
  0x200039e8: end
  0x2000c000: _estack
  0xf1e0f85f: BootRAM
