interrupt:
  mode: round-robin
  trigger:
    on-infinite-sleep: true
    interval: 1000

memory_maps:
  - name: dynamically_added_crash_region_0080a00c
    address: 0x805000
    size: 0xa000
    type: ram
  - name: mmio
    address: 0x40000000
    size: 0x20000000
    type: mmio
  - name: ram
    address: 0x20000000
    size: 0x100000
    type: ram
  - name: text
    address: 0x0
    size: 0x21800
    file:
      path: HAL.atmel_6lowpan_udp_rx.bin
    type: rom

symbols:
  - HAL.atmel_6lowpan_udp_rx.elf
