entry_point: 0x8015ecd
fork_points:
  - 0x800c088
include:
  - ./cortexm_memory.yml
initial_sp: 0x2002fffc
isr_vector: 0x8015ecd
memory_map:
  flash:
    base_addr: 0x800c080
    file: ./uEmu.uTasker_MODBUS.bin
    permissions: r-x
    size: 0x2000000
rules: rules.txt
