interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x8000000
    file: CNCX.bin
    ivt_offset: 0x0
    permissions: r-x
    size: 0x1c3f8
symbols:
  0x0: s_lib_ver.c
  0x200: _Min_Heap_Size
  0x400: _Min_Stack_Size
  0x8000000: g_pfnVectors
  0x8000189: deregister_tm_clones
  0x80001a5: register_tm_clones
  0x80001c9: __do_global_dtors_aux
  0x80001f1: frame_dummy
  0x8000211: coolant_flood_on
  0x800021d: coolant_flood_off
  0x8000229: coolant_mist_on
  0x8000235: coolant_mist_off
  0x8000241: coolant_init
  0x8000259: coolant_stop
  0x8000269: coolant_run
  0x80002b1: get_current_usecs
  0x80002ed: _delay_ms
  0x8000303: _delay_us
  0x8000349: eeprom_init
  0x8000369: eeprom_get_char
  0x8000399: eeprom_put_char
  0x80003cd: memcpy_to_eeprom_with_checksum
  0x8000445: memcpy_from_eeprom_with_checksum
  0x80004d1: select_plane
  0x8000505: gc_init
  0x8000555: gc_set_current_position
  0x80005c5: to_millimeters
  0x800060d: gc_execute_line
  0x8001875: next_statement
  0x80018f5: step_wr
  0x8001925: dirn_wr
  0x8001955: limits_init
  0x8001985: limits_isr
  0x80019bd: homing_cycle
  0x8001d75: limits_go_home
  0x8001e05: grbl_main
  0x8001ec1: mc_line
  0x8001f29: mc_arc
  0x8002429: mc_dwell
  0x80024e5: mc_go_home
  0x8002609: mc_reset
  0x8002659: read_float
  0x8002835: delay_ms
  0x800285b: delay_us
  0x80028c1: sys_sync_current_position
  0x80028f1: next_block_index
  0x8002917: prev_block_index
  0x800293d: estimate_acceleration_distance
  0x8002989: intersection_distance
  0x80029f9: max_allowable_speed
  0x8002a59: planner_reverse_pass_kernel
  0x8002b15: planner_reverse_pass
  0x8002b7d: planner_forward_pass_kernel
  0x8002c29: planner_forward_pass
  0x8002c99: calculate_trapezoid_for_block
  0x8002e89: planner_recalculate_trapezoids
  0x8002f5d: planner_recalculate
  0x8002f71: plan_reset_buffer
  0x8002fa5: plan_init
  0x8002fc1: plan_discard_current_block
  0x8002ff5: plan_get_current_block
  0x800302d: plan_check_full_buffer
  0x8003055: plan_synchronize
  0x8003085: plan_buffer_line
  0x800366d: plan_set_current_position
  0x8003699: plan_cycle_reinitialize
  0x800371d: printString
  0x8003747: printPgmString
  0x8003771: print_base2
  0x80037c1: print_uint8_base2
  0x80037dd: print_uint16_base2
  0x80037f9: print_uint32_base10
  0x8003879: printInteger
  0x80038a3: printFloat
  0x80039f1: protocol_reset_line_buffer
  0x8003a11: protocol_init
  0x8003a2d: protocol_execute_startup
  0x8003a89: buttons_isr
  0x8003ae5: protocol_execute_runtime
  0x8003c09: protocol_execute_line
  0x8003fa5: protocol_process
  0x80040a1: report_status_message
  0x80041b9: report_alarm_message
  0x8004211: report_feedback_message
  0x8004299: report_init_message
  0x80042ad: report_grbl_help
  0x80042c1: report_grbl_settings
  0x8004559: report_gcode_parameters
  0x8004741: report_gcode_modes
  0x8004971: report_startup_line
  0x80049b1: report_realtime_status
  0x8004c19: settings_store_startup_line
  0x8004c4d: settings_write_coord_data
  0x8004c83: write_global_settings
  0x8004ca1: settings_reset
  0x8004d85: settings_read_startup_line
  0x8004dd5: settings_read_coord_data
  0x8004e2b: read_global_settings
  0x8004e89: settings_store_global_setting
  0x800520b: settings_init
  0x8005261: spindle_on
  0x800526d: spindle_off
  0x8005279: spindle_fwd
  0x8005285: spindle_rev
  0x8005291: spindle_init
  0x80052a9: spindle_stop
  0x80052b5: spindle_run
  0x8005305: step_wr
  0x8005335: dirn_wr
  0x8005365: stepper_motor_disable
  0x8005371: stepper_motor_enable
  0x800537d: set_step_events_per_minute
  0x80053b9: iterate_trapezoid_cycle_counter
  0x80053f9: step_period_isr
  0x80057b9: step_pulse_isr
  0x80057d1: step_delay_isr
  0x80057e9: st_wake_up
  0x800583d: st_go_idle
  0x800586d: st_reset
  0x8005895: st_init
  0x80058b5: st_cycle_start
  0x80058d5: st_feed_hold
  0x80058f9: st_cycle_reinitialize
  0x8005959: serial_rx_hook
  0x80059d5: HAL_Init
  0x8005a19: HAL_DeInit
  0x8005a71: HAL_MspInit
  0x8005a7d: HAL_MspDeInit
  0x8005a89: HAL_IncTick
  0x8005aa5: HAL_GetTick
  0x8005ab9: HAL_Delay
  0x8005ae5: HAL_GetHalVersion
  0x8005af5: HAL_GetREVID
  0x8005b0d: HAL_GetDEVID
  0x8005b25: HAL_EnableDBGSleepMode
  0x8005b41: HAL_DisableDBGSleepMode
  0x8005b5d: HAL_EnableDBGStopMode
  0x8005b79: HAL_DisableDBGStopMode
  0x8005b95: HAL_EnableDBGStandbyMode
  0x8005bb1: HAL_DisableDBGStandbyMode
  0x8005bcd: HAL_EnableCompensationCell
  0x8005be5: HAL_DisableCompensationCell
  0x8005bfd: NVIC_SetPriority
  0x8005c51: SysTick_Config
  0x8005c95: HAL_RCC_DeInit
  0x8005d0d: HAL_RCC_OscConfig
  0x80061ad: HAL_RCC_ClockConfig
  0x8006439: HAL_RCC_MCOConfig
  0x80064e9: HAL_RCC_EnableCSS
  0x8006501: HAL_RCC_DisableCSS
  0x8006519: HAL_RCC_GetSysClockFreq
  0x8006655: HAL_RCC_GetHCLKFreq
  0x80066ad: HAL_RCC_GetPCLK1Freq
  0x80066f9: HAL_RCC_GetPCLK2Freq
  0x8006745: HAL_RCC_GetOscConfig
  0x80068e9: HAL_RCC_GetClockConfig
  0x8006949: HAL_RCC_NMI_IRQHandler
  0x8006971: HAL_RCC_CCSCallback
  0x800697d: NVIC_SetPriorityGrouping
  0x80069c5: NVIC_GetPriorityGrouping
  0x80069e1: NVIC_EnableIRQ
  0x8006a11: NVIC_DisableIRQ
  0x8006a45: NVIC_GetPendingIRQ
  0x8006a85: NVIC_SetPendingIRQ
  0x8006ab9: NVIC_ClearPendingIRQ
  0x8006aed: NVIC_GetActive
  0x8006b2d: NVIC_SetPriority
  0x8006b81: NVIC_GetPriority
  0x8006bcd: NVIC_EncodePriority
  0x8006c31: NVIC_DecodePriority
  0x8006c9d: NVIC_SystemReset
  0x8006cc9: SysTick_Config
  0x8006d0d: HAL_NVIC_SetPriorityGrouping
  0x8006d23: HAL_NVIC_SetPriority
  0x8006d5b: HAL_NVIC_EnableIRQ
  0x8006d77: HAL_NVIC_DisableIRQ
  0x8006d93: HAL_NVIC_SystemReset
  0x8006d9f: HAL_SYSTICK_Config
  0x8006db7: HAL_NVIC_GetPriorityGrouping
  0x8006dc5: HAL_NVIC_GetPriority
  0x8006df1: HAL_NVIC_SetPendingIRQ
  0x8006e0d: HAL_NVIC_GetPendingIRQ
  0x8006e2b: HAL_NVIC_ClearPendingIRQ
  0x8006e47: HAL_NVIC_GetActive
  0x8006e65: HAL_SYSTICK_CLKSourceConfig
  0x8006e9d: HAL_SYSTICK_IRQHandler
  0x8006ea9: HAL_SYSTICK_Callback
  0x8006eb5: HAL_GPIO_Init
  0x80071fd: HAL_GPIO_DeInit
  0x800733d: HAL_GPIO_ReadPin
  0x800736b: HAL_GPIO_WritePin
  0x8007399: HAL_GPIO_TogglePin
  0x80073bb: HAL_GPIO_EXTI_IRQHandler
  0x80073ed: HAL_GPIO_EXTI_Callback
  0x8007401: gpio_clr
  0x800742f: gpio_set
  0x800745d: Error_Handler
  0x8007463: SystemClock_Config
  0x80074f5: debounce_on_handler
  0x800754d: debounce_off_handler
  0x800756d: main
  0x8007595: SystemInit
  0x80075f1: SystemCoreClockUpdate
  0x80076f1: gpio_toggle
  0x8007737: NMI_Handler
  0x8007743: HardFault_Handler
  0x8007749: MemManage_Handler
  0x800774f: BusFault_Handler
  0x8007755: UsageFault_Handler
  0x800775b: SVC_Handler
  0x8007767: DebugMon_Handler
  0x8007773: PendSV_Handler
  0x800777f: SysTick_Handler
  0x80077b5: gpio_init
  0x800787d: gpio_rd
  0x80078ad: debounce_input
  0x800791d: debounce_rd
  0x8007959: debounce_isr
  0x80079e9: debounce_init
  0x8007a09: NVIC_EnableIRQ
  0x8007a39: enable_tim_clock
  0x8007a99: enable_tim_interrupt
  0x8007af9: step_timer_init
  0x8007b99: step_isr_enable
  0x8007beb: step_isr_disable
  0x8007c19: set_step_period
  0x8007c69: set_step_pulse_delay
  0x8007c87: set_step_pulse_time
  0x8007ca5: TIM2_IRQHandler
  0x8007d31: g540_timer_init
  0x8007dd1: g540_timer_start
  0x8007e01: g540_timer_stop
  0x8007e31: timers_init
  0x8007e45: usart_putc
  0x8007e75: usart_flush
  0x8007e81: usart_tstc
  0x8007ead: usart_getc
  0x8007ecd: enable_usart_clock
  0x8007f7d: set_baud_rate
  0x80081b9: usart_init
  0x800826d: serial_init
  0x8008279: serial_write
  0x8008293: __io_putchar
  0x80082af: serial_read
  0x80082e3: serial_reset_read_buffer
  0x8008301: ceil
  0x80083f9: cos
  0x8008499: floor
  0x8008591: lround
  0x8008635: round
  0x80086c9: sin
  0x8008779: trunc
  0x80087ed: atan2
  0x80087f1: hypot
  0x800884d: sqrt
  0x80088a9: __ieee754_atan2
  0x8008a39: __ieee754_hypot
  0x8008c71: __ieee754_rem_pio2
  0x80090c5: __ieee754_sqrt
  0x8009251: __kernel_cos
  0x80094b1: __kernel_rem_pio2
  0x8009d01: __kernel_sin
  0x8009e89: atan
  0x800a1a9: fabs
  0x800a1b1: finite
  0x800a1c1: scalbn
  0x800a2b5: __aeabi_drsub
  0x800a2bd: __subdf3
  0x800a2c1: __aeabi_dadd
  0x800a539: __floatunsidf
  0x800a559: __aeabi_i2d
  0x800a57d: __aeabi_f2d
  0x800a5c1: __floatundidf
  0x800a5d1: __aeabi_l2d
  0x800a62d: __muldf3
  0x800a881: __divdf3
  0x800aa51: __gedf2
  0x800aa59: __ledf2
  0x800aa61: __nedf2
  0x800aadd: __aeabi_cdrcmple
  0x800aaed: __aeabi_cdcmpeq
  0x800aafd: __aeabi_dcmpeq
  0x800ab11: __aeabi_dcmplt
  0x800ab25: __aeabi_dcmple
  0x800ab39: __aeabi_dcmpge
  0x800ab4d: __aeabi_dcmpgt
  0x800ab61: __unorddf2
  0x800ab8d: __aeabi_d2iz
  0x800abdd: __aeabi_d2uiz
  0x800ac1d: __truncdfsf2
  0x800acbd: __aeabi_frsub
  0x800acc5: __aeabi_fsub
  0x800acc9: __addsf3
  0x800ae29: __floatunsisf
  0x800ae31: __floatsisf
  0x800ae4d: __aeabi_ul2f
  0x800ae5d: __aeabi_l2f
  0x800aed9: __aeabi_fmul
  0x800b041: __aeabi_fdiv
  0x800b179: __gesf2
  0x800b181: __ltsf2
  0x800b189: __cmpsf2
  0x800b1e9: __aeabi_cfrcmple
  0x800b1f1: __aeabi_cfcmpeq
  0x800b201: __aeabi_fcmpeq
  0x800b215: __aeabi_fcmplt
  0x800b229: __aeabi_fcmple
  0x800b23d: __aeabi_fcmpge
  0x800b251: __aeabi_fcmpgt
  0x800b265: __aeabi_f2iz
  0x800b2b1: atexit
  0x800b2bd: __errno
  0x800b2c9: __libc_fini_array
  0x800b2f5: __libc_init_array
  0x800b33d: memset
  0x800b3e1: __register_exitproc
  0x800b449: Reset_Handler
  0x800b450: CopyDataInit
  0x800b458: LoopCopyDataInit
  0x800b466: FillZerobss
  0x800b46c: LoopFillZerobss
  0x800b498: Default_Handler
  0x800b499: DMA1_Stream3_IRQHandler
  0x800b49d: register_fini
  0x800b4b0: __EH_FRAME_BEGIN__
  0x800b4b1: _init
  0x800b4bd: _fini
  0x800b4c8: _etext
  0x800bbac: APBAHBPrescTable
  0x800bbbc: gpio_info
  0x800bd58: CSWTCH.8
  0x800bd70: CSWTCH.9
  0x800bd88: npio2_hw
  0x800be08: two_over_pi
  0x800bf10: init_jk
  0x800bf20: PIo2
  0x800bf60: atanhi
  0x800bf80: atanlo
  0x800bfa0: _global_impure_ptr
  0x800bfa4: __exidx_start
  0x800bfa8: __frame_dummy_init_array_entry
  0x800bfac: __init_array_end
  0x800bfb0: _sidata
  0x800c3f8: _siccmram
  0x10000000: _sccmram
  0x20000000: _sdata
  0x20000004: AHBPrescTable
  0x20000014: __fdlib_version
  0x20000018: _impure_ptr
  0x20000020: impure_data
  0x20000448: _edata
  0x2000044c: object.0
  0x20000464: current_coolant_mode
  0x20000468: eeprom_ready
  0x2000046c: eeprom_data
  0x2000086c: gc
  0x200008a4: sys
  0x200008b8: block_buffer
  0x20000d38: block_buffer_head
  0x20000d39: block_buffer_tail
  0x20000d3a: next_buffer_head
  0x20000d3c: pl
  0x20000d58: line
  0x20000e58: char_counter
  0x20000e59: iscomment
  0x20000e5c: settings
  0x20000e9c: current_direction
  0x20000ea0: st
  0x20000ec4: current_block
  0x20000ec8: step_bits
  0x20000eca: dirn_bits
  0x20000ecc: saved_step_bits
  0x20000ed0: uwTick
  0x20000ed4: limits_enabled
  0x20000ed8: buttons_enabled
  0x20000edc: debounce
  0x20000ef4: debounce_ready
  0x20000ef8: __bss_end__
  0x2001ffff: _estack
