interrupt:
  mode: round-robin
  trigger:
    on-infinite-sleep: true
    interval: 1000

memory_maps:
  - name: dynamically_added_crash_region_10000130
    address: 0xfffb000
    size: 0xa000
    type: ram
  - name: mmio
    address: 0x40000000
    size: 0x20000000
    type: mmio
  - name: ram
    address: 0x20000000
    size: 0x100000
    type: ram
  - name: text
    address: 0x0
    size: 0x1cc00
    file:
      path: zephyr-CVE-2021-3329.bin
    type: rom

symbols:
  - zephyr-CVE-2021-3329.elf
