board:
  init_nsvtor: 0x8000000

interrupt:
  mode: round-robin
  trigger:
    on-infinite-sleep: true
    interval: 1000

memory_maps:
  - name: dynamically_added_crash_region_080407fe
    address: 0x803b000
    size: 0xa000
    type: ram
  - name: mmio
    address: 0x40000000
    size: 0x20000000
    type: mmio
  - name: ram
    address: 0x20000000
    size: 0x100000
    type: ram
  - name: text
    address: 0x8000000
    size: 0x1e800
    file:
      path: hoverX.bin
    type: rom

symbols:
  - hoverX.elf
