interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  .stack:
    base_addr: 0x1ffec000
    permissions: rw-
    size: 0xa000
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x0
    file: Console.bin
    ivt_offset: 0x0
    permissions: r-x
    size: 0x177fc
symbols:
  0x0: cortex_vector_base
  0x10: _flashsec_length
  0x40: vector_cpu
  0x1d8: vector_padding
  0x400: _vectors_length
  0x410: _sfixed
  0x411: _init
  0x41d: _fini
  0x429: _sbrk_r
  0x491: _read_r
  0x4b3: _write_r
  0x4d5: _close_r
  0x4f3: _lseek_r
  0x515: _fstat_r
  0x535: _isatty_r
  0x567: bitarithm_lsb
  0x58f: clist_rpush
  0x5cb: clist_lpop
  0x611: sched_run
  0x699: sched_set_status
  0x739: sched_switch
  0x795: sched_task_exit
  0x7dd: thread_stack_init
  0x8b9: thread_isr_stack_usage
  0x901: thread_isr_stack_pointer
  0x91d: thread_isr_stack_start
  0x931: cpu_switch_context_exit
  0x936: unreachable381
  0x93d: thread_yield_higher
  0x959: isr_pendsv
  0x975: isr_svc
  0x979: context_restore
  0x991: post_startup
  0x99d: reset_handler_default
  0xa31: nmi_default
  0xa41: _stack_size_left
  0xa65: hard_fault_default
  0xa78: fix_msp
  0xa7e: test_sp
  0xa8c: use_psp
  0xa90: out
  0xaa9: hard_fault_handler
  0xc81: mem_manage_default
  0xc91: bus_fault_default
  0xca1: usage_fault_default
  0xcb1: debug_mon_default
  0xcc1: isr_systick
  0xcd1: irq_disable
  0xcef: irq_enable
  0xd09: irq_restore
  0xd25: irq_is_in
  0xd3f: bitband_addr
  0xd71: bit_clear32
  0xd95: cpu_errata_fixes
  0xda9: pre_startup
  0xdb9: isr_wdog_ewm
  0xdc5: wdog_disable
  0xded: uart_stdio_init
  0xe0d: uart_stdio_read
  0xe31: uart_stdio_write
  0xe51: pm_off
  0xe5d: board_init
  0xed1: cpu_print_last_instruction
  0xef1: panic_arch
  0xefd: core_panic
  0xf55: main_trampoline
  0xf79: idle_thread
  0xf85: kernel_init
  0xfe5: cib_init
  0x102d: thread_add_to_list
  0x1099: thread_measure_stack_free
  0x10cd: thread_create
  0x126d: cpu_init
  0x1295: mutex_lock
  0x12ad: isrpipe_write_one
  0x12db: isrpipe_read
  0x1311: NVIC_EnableIRQ
  0x1341: cortexm_isr_end
  0x1359: bitband_addr
  0x138b: bit_set32
  0x13b1: uart_init
  0x143d: uart_init_pins
  0x14b5: uart_init_uart
  0x15c1: uart_write
  0x1615: irq_handler_uart
  0x1675: isr_uart0_rx_tx
  0x1683: bitband_addr
  0x16b5: bit_set32
  0x16d9: bit_set8
  0x16fd: bit_clear8
  0x1721: kinetis_mcg_disable_pll
  0x1735: kinetis_mcg_set_fll_factor
  0x1765: kinetis_mcg_enable_osc
  0x17c9: kinetis_mcg_init_erclk32k
  0x1819: kinetis_mcg_init_mcgirclk
  0x18a9: kinetis_mcg_set_fei
  0x1909: kinetis_mcg_set_fee
  0x194d: kinetis_mcg_set_fbi
  0x19ad: kinetis_mcg_set_fbe
  0x1a05: kinetis_mcg_set_blpi
  0x1a29: kinetis_mcg_set_blpe
  0x1a4d: kinetis_mcg_set_pbe
  0x1ac1: kinetis_mcg_set_pee
  0x1afd: kinetis_mcg_set_mode
  0x1ba5: kinetis_mcg_set_safe_mode
  0x1c71: kinetis_mcg_init
  0x1cdd: cortexm_isr_end
  0x1cf5: bitband_addr
  0x1d27: bit_set32
  0x1d4b: port
  0x1d6d: gpio
  0x1d8f: port_num
  0x1dad: pin_num
  0x1dc9: clk_en
  0x1df9: get_ctx
  0x1e31: write_map
  0x1ead: ctx_clear
  0x1ed3: gpio_init
  0x1f67: gpio_init_port
  0x1fdd: gpio_set
  0x2009: irq_handler
  0x2099: isr_porta
  0x20ad: isr_portb
  0x20c1: isr_portc
  0x20d5: isr_portd
  0x20e9: isr_porte
  0x20fd: ps
  0x2255: tsrb_empty
  0x2279: tsrb_full
  0x22a3: _push
  0x22d5: _pop
  0x2301: tsrb_get
  0x2349: tsrb_add_one
  0x237b: periph_init
  0x2389: main
  0x23a5: auto_init
  0x23b1: list_remove_head
  0x23d9: _mutex_lock
  0x2461: mutex_unlock
  0x24dd: NVIC_SetPriority
  0x2531: cortexm_init
  0x2599: rtc_init
  0x25a5: rtc_set_time
  0x25c7: rtc_get_time
  0x25ed: rtc_set_alarm
  0x2625: rtc_get_alarm
  0x264d: rtc_clear_alarm
  0x2665: rtc_poweron
  0x2671: rtc_poweroff
  0x267d: rtc_cb
  0x26a1: NVIC_EnableIRQ
  0x26d1: NVIC_SetPriority
  0x2725: cortexm_isr_end
  0x273d: rtt_init
  0x27a9: rtt_get_counter
  0x27e9: rtt_set_counter
  0x2821: rtt_set_alarm
  0x287d: rtt_get_alarm
  0x289d: rtt_clear_alarm
  0x28d9: rtt_poweron
  0x28fd: rtt_poweroff
  0x2921: isr_rtc
  0x298d: __sputc_r
  0x29e9: _putchar
  0x2a11: find_handler
  0x2a81: print_help
  0x2b05: handle_input_line
  0x2d7d: readline
  0x2e69: print_prompt
  0x2e8d: shell_run
  0x2ebd: _reboot_handler
  0x2ed5: _ps_handler
  0x2eed: probe
  0x2f51: probe_all
  0x2f95: list
  0x3001: read
  0x307d: write
  0x318d: _saul
  0x3201: _alarm_handler
  0x321d: dow
  0x32ad: _parse_time
  0x3399: _print_time
  0x33e1: _rtc_getalarm
  0x3415: _rtc_setalarm
  0x3465: _rtc_gettime
  0x3499: _rtc_settime
  0x34e1: _rtc_usage
  0x3545: _rtc_handler
  0x3679: NVIC_SystemReset
  0x36a1: pm_reboot
  0x36ad: phydat_dump
  0x385d: phydat_unit_to_str
  0x3965: phydat_prefix_from_scale
  0x3a35: saul_class_to_str
  0x3b9d: saul_reg_find_nth
  0x3bdd: saul_reg_read
  0x3c0d: saul_reg_write
  0x3c3d: fmt_u32_dec
  0x3cd1: fmt_s32_dec
  0x3d17: fmt_s16_dfp
  0x3d3d: fmt_s32_dfp
  0x3e6d: fmt_lpad
  0x3ebb: atoi
  0x3ec5: __sflush_r
  0x3fd5: _fflush_r
  0x4029: fflush
  0x404d: _cleanup_r
  0x4059: std.isra.0
  0x40a1: __sfmoreglue
  0x40cd: __sinit
  0x412d: __sfp
  0x41a5: _fwalk
  0x41dd: _fwalk_reent
  0x4219: gmtime_r
  0x434d: __libc_init_array
  0x4395: memmove
  0x43c9: memset
  0x43d9: validate_structure
  0x4599: mktime
  0x4891: _free_r
  0x492d: _malloc_r
  0x49e9: iprintf
  0x4a19: _puts_r
  0x4ad1: puts
  0x4ae1: __srget_r
  0x4b39: __sread
  0x4b5b: __seofread
  0x4b5f: __swrite
  0x4b97: __sseek
  0x4bbb: __sclose
  0x4bc3: strcmp
  0x4bd7: strncmp
  0x4bfb: _strtol_l.isra.0
  0x4cfd: _strtol_r
  0x4d21: strtol
  0x4d4d: __tzcalc_limits
  0x4e9d: __tz_lock
  0x4e9f: __tz_unlock
  0x4ea1: _tzset_unlocked
  0x4ead: _tzset_unlocked_r
  0x51b1: __swbuf_r
  0x5255: __swsetup_r
  0x5331: div
  0x5359: _findenv_r
  0x53d9: _getenv_r
  0x53e9: __gettzinfo
  0x53f1: __locale_ctype_ptr_l
  0x53f9: __locale_ctype_ptr
  0x5415: __swhatbuf_r
  0x545d: __smakebuf_r
  0x54dd: free
  0x54ed: __ascii_mbtowc
  0x5511: __malloc_lock
  0x5513: __malloc_unlock
  0x5515: __sfputc_r
  0x5541: __sfputs_r
  0x5565: _vfprintf_r
  0x5791: _printf_common
  0x587d: _printf_i
  0x5abd: lflush
  0x5ad1: __srefill_r
  0x5be5: siscanf
  0x5c39: strcpy
  0x5c49: strlen
  0x5c59: _strtoul_l.isra.0
  0x5d55: _strtoul_r
  0x5d79: strtoul
  0x5da5: __ascii_wctomb
  0x5dbf: __env_lock
  0x5dc1: __env_unlock
  0x5dd1: memchr
  0x5e71: memcpy
  0x5e87: _realloc_r
  0x5ed3: _sungetc_r
  0x5f4d: __ssrefill_r
  0x5f89: __ssvfiscanf_r
  0x6231: _scanf_chars
  0x62f9: _scanf_i
  0x64e1: __sccl
  0x6541: __submore
  0x65b7: _malloc_usable_size_r
  0x6840: BFARVALID_MASK.6858
  0x6844: MMARVALID_MASK.6859
  0x687c: assert_crash_message
  0x68dc: uart_config
  0x68fc: mcg_mode_routing
  0x6bfc: _shell_command_list
  0x7274: _tenmap
  0x7294: __sf_fake_stderr
  0x72b4: __sf_fake_stdin
  0x72d4: __sf_fake_stdout
  0x72f4: _global_impure_ptr
  0x72f8: DAYS_IN_MONTH
  0x7328: _DAYS_BEFORE_MONTH
  0x73a0: __month_lengths
  0x7433: _ctype_
  0x755c: __preinit_array_start
  0x40000: _ram_length
  0x100000: _rom_length
  0x1fff0000: isr_stack
  0x1fff0200: _estack
  0x1fff0204: uart_stdio_isrpipe
  0x1fff0218: main_name
  0x1fff021c: idle_name
  0x1fff0220: state_names
  0x1fff024c: INCORRECT_QUOTING.4813
  0x1fff0250: t.7177
  0x1fff0280: _impure_ptr
  0x1fff0284: impure_data
  0x1fff02e4: _tzname
  0x1fff02ec: tzinfo
  0x1fff032c: __global_locale
  0x1fff0498: environ
  0x1fff049c: max_threads
  0x1fff049d: _tcb_name_offset
  0x1fff04a0: _erelocate
  0x1fff04a4: sched_context_switch_request
  0x1fff04a8: sched_threads
  0x1fff052c: sched_active_thread
  0x1fff0530: sched_active_pid
  0x1fff0534: sched_runqueues
  0x1fff0574: runqueue_bitcache
  0x1fff0578: _rx_buf_mem
  0x1fff05b8: crashed
  0x1fff05bc: main_stack
  0x1fff0bbc: idle_stack
  0x1fff0cbc: config
  0x1fff0cc4: current_mode
  0x1fff0cc8: isr_ctx
  0x1fff0d28: isr_map
  0x1fff0ee8: rtc_callback
  0x1fff0eec: rtt_callback
  0x1fff0efc: saul_reg
  0x1fff0f00: __malloc_free_list
  0x1fff0f04: __malloc_sbrk_start
  0x1fff0f08: __tzname_dst
  0x1fff0f13: __tzname_std
  0x1fff0f20: prev_tzenv
  0x1fff0f24: _daylight
  0x1fff0f28: _timezone
  0x1fff0f2c: initial_env
  0x1fff0f30: _ezero
  0x20000000: _ram_base_addr
  0x20030000: _eheap
