interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  dynamically_added_crash_region_080407fe:
    base_addr: 0x803b000
    permissions: rw-
    size: 0xa000
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x8000000
    file: hover0508.bin
    ivt_offset: 0x0
    permissions: r-x
    size: 0x1d968
symbols:
  0x0: close.c
  0x200: _Min_Heap_Size
  0x400: _Min_Stack_Size
  0x800: _Reserved_Space
  0x8000000: g_pfnVectors
  0x80001e9: __do_global_dtors_aux
  0x800020d: frame_dummy
  0x8000229: strlen
  0x8000239: __aeabi_drsub
  0x8000241: __subdf3
  0x8000245: __aeabi_dadd
  0x80004bd: __floatunsidf
  0x80004dd: __aeabi_i2d
  0x8000501: __aeabi_f2d
  0x8000545: __floatundidf
  0x8000555: __aeabi_l2d
  0x80005b1: __muldf3
  0x8000805: __divdf3
  0x80009d5: __gedf2
  0x80009dd: __ledf2
  0x80009e5: __nedf2
  0x8000a61: __aeabi_cdrcmple
  0x8000a71: __aeabi_cdcmpeq
  0x8000a81: __aeabi_dcmpeq
  0x8000a95: __aeabi_dcmplt
  0x8000aa9: __aeabi_dcmple
  0x8000abd: __aeabi_dcmpge
  0x8000ad1: __aeabi_dcmpgt
  0x8000ae5: __aeabi_d2iz
  0x8000b35: __truncdfsf2
  0x8000bd5: __aeabi_frsub
  0x8000bdd: __aeabi_fsub
  0x8000be1: __addsf3
  0x8000d41: __floatunsisf
  0x8000d49: __floatsisf
  0x8000d65: __aeabi_ul2f
  0x8000d75: __aeabi_l2f
  0x8000df1: __aeabi_fmul
  0x8000f59: __aeabi_fdiv
  0x8001091: __gesf2
  0x8001099: __ltsf2
  0x80010a1: __cmpsf2
  0x8001101: __aeabi_cfrcmple
  0x8001109: __aeabi_cfcmpeq
  0x8001119: __aeabi_fcmpeq
  0x800112d: __aeabi_fcmplt
  0x8001141: __aeabi_fcmple
  0x8001155: __aeabi_fcmpge
  0x8001169: __aeabi_fcmpgt
  0x800117d: __aeabi_f2iz
  0x80011c9: __aeabi_uldivmod
  0x80011f9: __udivmoddi4
  0x80014cd: __aeabi_idiv0
  0x80014d1: FLASH_Program_HalfWord
  0x80014ed: FLASH_SetErrorCode
  0x800155d: HAL_FLASH_Unlock
  0x8001585: HAL_FLASH_Lock
  0x8001599: FLASH_WaitForLastOperation
  0x8001601: HAL_FLASH_Program
  0x80016a1: RCC_Delay
  0x80016cd: HAL_RCC_OscConfig
  0x8001aad: HAL_RCC_GetSysClockFreq
  0x8001b1d: HAL_RCC_ClockConfig
  0x8001c99: HAL_RCC_GetHCLKFreq
  0x8001ca5: HAL_RCC_GetPCLK1Freq
  0x8001cc5: HAL_RCC_GetPCLK2Freq
  0x8001ce5: TIM_OC1_SetConfig
  0x8001d4d: TIM_OC3_SetConfig
  0x8001dbd: TIM_OC4_SetConfig
  0x8001e0d: TIM_TI1_ConfigInputStage
  0x8001e31: TIM_TI2_ConfigInputStage
  0x8001e57: TIM_ETR_SetConfig
  0x8001e6f: TIM_SlaveTimer_SetConfig
  0x8001ee3: HAL_TIM_Base_MspInit
  0x8001ee5: HAL_TIM_Base_Start
  0x8001eff: HAL_TIM_PWM_MspInit
  0x8001f01: HAL_TIM_SlaveConfigSynchronization
  0x8001f41: TIM_Base_SetConfig
  0x8001fd9: HAL_TIM_Base_Init
  0x800200d: HAL_TIM_PWM_Init
  0x8002041: TIM_OC2_SetConfig
  0x80020b1: HAL_TIM_PWM_ConfigChannel
  0x800218d: TIM_CCxChannelCmd
  0x80021a9: HAL_TIM_PWM_Start
  0x80021e1: TIM_CCxNChannelCmd
  0x80021fb: HAL_TIMEx_PWMN_Start
  0x800221f: HAL_TIMEx_ConfigBreakDeadTime
  0x8002277: HAL_TIMEx_MasterConfigSynchronization
  0x80022c9: HAL_ADCEx_MultiModeConfigChannel
  0x8002329: HAL_NVIC_SetPriorityGrouping
  0x800234d: HAL_NVIC_SetPriority
  0x80023bd: HAL_NVIC_EnableIRQ
  0x80023d5: HAL_NVIC_DisableIRQ
  0x80023ed: HAL_NVIC_SystemReset
  0x8002411: HAL_SYSTICK_Config
  0x8002439: HAL_SYSTICK_CLKSourceConfig
  0x8002459: HAL_SYSTICK_Callback
  0x800245b: HAL_SYSTICK_IRQHandler
  0x8002465: FLASH_MassErase
  0x8002489: FLASH_PageErase
  0x80024ad: HAL_FLASHEx_Erase
  0x8002551: HAL_GPIO_Init
  0x8002791: HAL_GPIO_ReadPin
  0x800279f: HAL_GPIO_WritePin
  0x80027ab: HAL_GPIO_TogglePin
  0x80027b5: HAL_RCCEx_PeriphCLKConfig
  0x80028cd: HAL_MspInit
  0x80028d1: HAL_InitTick
  0x80028fd: HAL_Init
  0x8002921: HAL_IncTick
  0x8002931: HAL_GetTick
  0x800293d: HAL_Delay
  0x8002961: HAL_ADC_MspInit
  0x8002965: HAL_ADC_ConfigChannel
  0x8002aa9: ADC_Enable
  0x8002b29: HAL_ADC_Start
  0x8002c11: ADC_ConversionStop_Disable
  0x8002c5d: HAL_ADC_Init
  0x8002d81: UART_SetConfig
  0x8002f25: HAL_UART_MspInit
  0x8002f27: HAL_UART_Init
  0x8002f85: SystemInit
  0x8002fd1: USART2_IT_init
  0x80030d1: MX_GPIO_Init
  0x8003359: MX_TIM_Init
  0x8003555: MX_ADC1_Init
  0x8003685: MX_ADC2_Init
  0x8003739: poweroff
  0x80037a1: init_PID_control
  0x80038f5: change_PID_constants
  0x80039d5: init_flash_content
  0x8003a25: check_power_button
  0x8003b21: SystemClock_Config
  0x8003bb9: main
  0x8004721: BldcController_Init
  0x8004829: DMA1_Channel1_IRQHandler
  0x8004e41: readADCs
  0x800515d: setScopeChannel
  0x8005169: consoleScope
  0x800516d: USART2_IT_starttx
  0x8005181: serial_usart_buffer_count
  0x8005195: serial_usart_buffer_push
  0x80051d5: USART2_IT_send
  0x8005219: serial_usart_buffer_pop
  0x800524d: USART2_IT_IRQ
  0x8005295: HallInterruptinit
  0x800538d: HallGetuS
  0x80053d9: HallInterruptsInterrupt
  0x8005659: TIM4_IRQHandler
  0x80056dd: writeFlash
  0x8005855: readFlash
  0x80058ed: NMI_Handler
  0x80058ef: HardFault_Handler
  0x80058f1: MemManage_Handler
  0x80058f3: BusFault_Handler
  0x80058f5: UsageFault_Handler
  0x80058f7: SVC_Handler
  0x80058f9: DebugMon_Handler
  0x80058fb: PendSV_Handler
  0x80058fd: SysTick_Handler
  0x8005909: EXTI0_IRQHandler
  0x8005915: EXTI1_IRQHandler
  0x8005921: EXTI2_IRQHandler
  0x800592d: EXTI3_IRQHandler
  0x8005939: EXTI4_IRQHandler
  0x8005945: EXTI9_5_IRQHandler
  0x80059b9: EXTI15_10_IRQHandler
  0x8005a45: USART2_IRQHandler
  0x8005a55: pid_need_compute
  0x8005a6d: pid_compute
  0x8005b19: pid_tune
  0x8005b9d: pid_limits
  0x8005c03: pid_auto
  0x8005c43: pid_direction
  0x8005c7d: pid_create
  0x8005cc1: getChange
  0x8005ccf: computeAngularVelocities
  0x8005d81: DeadReckoner
  0x8005df1: getXYT
  0x8005e4d: computePosition
  0x8005fdd: reset
  0x8006001: noTick
  0x8006005: noDelay
  0x8006007: noReset
  0x8006009: nosend
  0x800600d: fn_ping
  0x8006025: protocol_process_ReadValue
  0x800605f: protocol_process_ReadAndSendValue
  0x800609f: protocol_process_WriteValue
  0x80060e3: protocol_process_cmdWritevalAndRespond
  0x800611b: fn_defaultProcessing
  0x8006149: fn_defaultProcessingPreWriteClear
  0x8006175: fn_SubscribeData
  0x8006215: fn_ProtocolcountDataSum
  0x80062d9: fn_ProtocolcountDataAck
  0x8006339: fn_ProtocolcountDataNoack
  0x8006399: fn_defaultProcessingReadOnly
  0x80063ad: fn_paramstat_descriptions
  0x80064b5: setParam
  0x80064d5: setParamsCopy
  0x8006531: setParamVariable
  0x8006563: setParamHandler
  0x8006579: protocol_init
  0x8006615: protocol_process_message
  0x80067a9: mpGetTxByte
  0x80067dd: mpPutTx
  0x80067fd: protocol_cobsr_decode
  0x800683b: protocol_cobsr_encode
  0x8006865: protocol_SOM_decode
  0x8006881: protocol_SOM_encode
  0x80068af: protocol_send_raw
  0x8006919: protocol_send_ack
  0x800694b: protocol_send_nack
  0x8006989: mpTxQueued
  0x80069ab: mpGetTxMsg
  0x80069f9: protocol_send
  0x8006b91: protocol_tick
  0x8006cd5: protocol_byte
  0x8006f91: protocol_post
  0x8007003: protocol_send_text
  0x8007071: line_lock_ascii
  0x80070ad: line_unlock_ascii
  0x8007155: line_help
  0x80071f5: ascii_add_immediate
  0x8007225: ascii_add_line_fn
  0x8007255: ascii_byte
  0x80073f9: ascii_init
  0x8007449: cobsr_encode
  0x8007517: cobsr_decode
  0x8007601: line_toggle_sensor_control
  0x8007609: immediate_dir
  0x8007b11: immediate_stop
  0x8007b89: immediate_quit
  0x8007c1d: immediate_hall
  0x8007c95: immediate_sensors
  0x8007cc5: line_sensors
  0x8007cd1: immediate_electrical
  0x8007db1: line_electrical
  0x8007dbd: immediate_stm32
  0x8007e0d: line_stm32
  0x8007e19: line_main_timing_stats
  0x8007e49: immediate_toggle_control
  0x8007e8d: line_debug_control
  0x8007eed: line_immediate
  0x8008071: line_set_alarm
  0x80080f1: line_generic_var
  0x8008345: line_poweroff_control
  0x8008409: line_reset_firmware
  0x8008451: line_test_message
  0x80084d5: line_read_memory
  0x8008591: get_F_description
  0x800862d: main_ascii_init
  0x80087d9: fn_enable
  0x8008855: fn_SpeedData
  0x800887d: fn_Position
  0x80088d5: fn_PositionIncr
  0x8008941: fn_RawPosition
  0x8008999: fn_PWMData
  0x8008a31: fn_BuzzerData
  0x8008a8d: fn_FlashContentMaxCurrLim
  0x8008ac9: fn_xytPosn
  0x8008af1: fn_FlashContentPID
  0x8008b09: setup_protocol
  0x8008e81: consoleLog
  0x8008ea1: fn_FlashContentMagic
  0x8008ef9: BLDC_controller_step
  0x8009505: BLDC_controller_initialize
  0x800951d: Reset_Handler
  0x8009520: CopyDataInit
  0x8009528: LoopCopyDataInit
  0x8009536: FillZerobss
  0x800953c: LoopFillZerobss
  0x8009564: Default_Handler
  0x8009565: DMA2_Channel3_IRQHandler
  0x8009567: atoi
  0x8009571: calloc
  0x8009581: __libc_init_array
  0x80095c9: malloc
  0x80095d9: memcpy
  0x80095f5: memset
  0x8009605: _calloc_r
  0x800962d: _free_r
  0x80096bd: sbrk_aligned
  0x80096fd: _malloc_r
  0x80097e5: _sbrk_r
  0x8009805: sniprintf
  0x800986d: siprintf
  0x80098ad: siscanf
  0x8009901: __seofread
  0x8009905: strcat
  0x8009923: strcpy
  0x8009933: strncmp
  0x800995b: strncpy
  0x8009981: _strtol_l.constprop.0
  0x8009a79: _strtol_r
  0x8009a7d: strtol
  0x8009a91: __errno
  0x8009a9d: __malloc_lock
  0x8009aa9: __malloc_unlock
  0x8009ab5: __ssputs_r
  0x8009b6d: _svfiprintf_r
  0x8009d6d: _sungetc_r
  0x8009de7: __ssrefill_r
  0x8009e21: __ssvfiscanf_r
  0x800a115: _printf_common
  0x800a1f5: _printf_i
  0x800a441: _scanf_chars
  0x800a4f5: _scanf_i
  0x800a6e5: __sccl
  0x800a755: _strtoul_l.constprop.0
  0x800a839: _strtoul_r
  0x800a83d: __submore
  0x800a8ad: __retarget_lock_acquire_recursive
  0x800a8af: __retarget_lock_release_recursive
  0x800a8b1: memchr
  0x800a8cd: memmove
  0x800a901: _realloc_r
  0x800a95f: _malloc_usable_size_r
  0x800a971: cos
  0x800aa15: sin
  0x800aac9: __ieee754_rem_pio2
  0x800af21: __kernel_cos
  0x800b171: __kernel_rem_pio2
  0x800b9c1: __kernel_sin
  0x800bb45: fabs
  0x800bb51: floor
  0x800bc49: scalbn
  0x800bd45: _sbrk
  0x800bd60: __EH_FRAME_BEGIN__
  0x800bd61: _init
  0x800bd6d: _fini
  0x800bd78: _etext
  0x800bda0: AHBPrescTable
  0x800bdb0: APBPrescTable
  0x800beec: FlashDefaults
  0x800bf68: hall_to_pos
  0x800bf70: increments
  0x800c354: initialparams
  0x800d068: control_types
  0x800d0be: _ctype_
  0x800d210: __sf_fake_stderr
  0x800d230: __sf_fake_stdin
  0x800d250: __sf_fake_stdout
  0x800d270: npio2_hw
  0x800d2f0: two_over_pi
  0x800d3f8: PIo2
  0x800d438: init_jk
  0x800d448: __exidx_start
  0x800d450: __exidx_end
  0x800d454: __init_array_end
  0x800d458: _sidata
  0x800d968: _sdata_ramfuncs
  0x20000000: _sdata
  0x20000004: adc_buffers
  0x20000114: input_timeout_counter
  0x20000118: BldcControllerParams
  0x20000134: batteryVoltage
  0x20000138: electrical_measurements
  0x200001b0: debug_out
  0x200001b1: enablescope
  0x200001b4: WheelSize_mm
  0x200001b8: flash_data
  0x200001bc: flashlen
  0x200001c0: protocol_Delay
  0x200001c4: protocol_GetTick
  0x200001c8: protocol_SystemReset
  0x200001cc: version
  0x200001d0: password
  0x200001dc: PWMData
  0x200001f0: PosnData
  0x20000210: SpeedData
  0x20000234: rtConstP
  0x20000448: rtP
  0x200004ac: _impure_ptr
  0x200004b0: impure_data
  0x20000510: _edata
  0x20000514: object.0
  0x20000530: pFlash
  0x20000550: uwTick
  0x20000554: USART2WordLength
  0x20000558: adc_buffer
  0x20000570: hadc1
  0x200005a0: hadc2
  0x200005d0: htim_left
  0x20000610: htim_right
  0x20000650: huart2
  0x20000690: ADCcontrolActive
  0x20000694: FlashContent
  0x200006dc: PositionPid
  0x20000744: PositionPidFloats
  0x20000764: SpeedPid
  0x200007cc: SpeedPidFloats
  0x200007ec: autoSensorBaud2
  0x200007f0: buzzerLen
  0x200007f4: cmd1
  0x200007f8: cmd2
  0x200007fc: control_type
  0x20000800: deadreconer
  0x20000804: debug_counter
  0x20000808: disablepoweroff
  0x2000080c: dspeeds
  0x20000814: inactivity_timeout_counter
  0x20000818: power_button_info
  0x20000824: powerofftimer
  0x20000828: pwms
  0x20000830: sensor_control
  0x20000834: speed
  0x20000838: steer
  0x2000083c: xytPosn
  0x20000848: bldc_count
  0x2000084c: bldc_count_per_hall_counter
  0x20000858: bldc_counter
  0x20000860: buzzerFreq
  0x20000864: buzzerPattern
  0x20000868: buzzerTimer
  0x2000086c: enable
  0x20000870: offsetcount
  0x20000874: pwml
  0x20000878: pwmr
  0x2000087c: rtDW_Left
  0x200008a0: rtDW_Right
  0x200008c4: rtM_Left_
  0x200008d4: rtM_Right_
  0x200008e4: rtU_Left
  0x200008ec: rtU_Right
  0x200008f4: rtY_Left
  0x20000908: rtY_Right
  0x2000091c: ch_buf
  0x2000092c: usart2_it_RXbuffer
  0x20000d38: usart2_it_TXbuffer
  0x20001144: HallData
  0x2000118c: bldc_count_per_hall
  0x20001194: h_timer_hall
  0x200011d4: hall_ul
  0x200011d5: hall_ur
  0x200011d6: hall_vl
  0x200011d7: hall_vr
  0x200011d8: hall_wl
  0x200011d9: hall_wr
  0x200011dc: local_hall_params
  0x20001240: now_us
  0x20001248: timeStats
  0x200012d0: timerwraps
  0x200012d8: ProtocolcountData
  0x200012fc: contentbuf
  0x200013fc: paramstat_descriptions
  0x200014fc: immediate_functions
  0x20001cfc: line_functions
  0x200024fc: speedB
  0x20002500: steerB
  0x20002504: BuzzerData
  0x20002508: Position
  0x20002518: PositionIncr
  0x20002520: RawPosition
  0x20002530: protocol_enable
  0x20002534: sUSART2
  0x20003788: __malloc_free_list
  0x2000378c: __malloc_sbrk_start
  0x20003790: errno
  0x20003794: __lock___malloc_recursive_mutex
  0x20003798: heap_end.0
  0x2000379c: __bss_end__
  0x200037a0: end
  0x2000c000: _estack
  0xf1e0f85f: BootRAM
