board:
  init_nsvtor: 0x8000000

interrupt:
  mode: round-robin
  trigger:
    on-infinite-sleep: true
    interval: 1000

memory_maps:
  - name: mmio
    address: 0x40000000
    size: 0x20000000
    type: mmio
  - name: ram
    address: 0x20000000
    size: 0x100000
    type: ram
  - name: text
    address: 0x8000000
    size: 0x16400
    file:
      path: PLC.bin
    type: rom

symbols:
  - PLC.elf
