interrupt_triggers:
  trigger:
    every_nth_tick: 0x3e8
    fuzz_mode: round_robin
memory_map:
  .stack:
    base_addr: 0x1ffec000
    permissions: rw-
    size: 0xa000
  irq_ret:
    base_addr: 0xfffff000
    permissions: --x
    size: 0x1000
  mmio:
    base_addr: 0x40000000
    permissions: rw-
    size: 0x20000000
  nvic:
    base_addr: 0xe0000000
    permissions: rw-
    size: 0x10000000
  ram:
    base_addr: 0x20000000
    permissions: rw-
    size: 0x100000
  text:
    base_addr: 0x0
    file: ConsoleX.bin
    ivt_offset: 0x0
    permissions: r-x
    size: 0x19168
symbols:
  0x0: cortex_vector_base
  0x10: _flashsec_length
  0x40: vector_cpu
  0x1d8: vector_padding
  0x400: _vectors_length
  0x440: _sfixed
  0x441: _init
  0x44d: _fini
  0x459: _sbrk_r
  0x4c1: _read_r
  0x4e3: _write_r
  0x505: _close_r
  0x523: _lseek_r
  0x545: _fstat_r
  0x565: _isatty_r
  0x597: bitarithm_lsb
  0x5bf: clist_rpush
  0x5fb: clist_lpop
  0x641: sched_run
  0x6c9: sched_set_status
  0x769: sched_switch
  0x7c5: sched_task_exit
  0x80d: thread_stack_init
  0x8e9: thread_isr_stack_usage
  0x931: thread_isr_stack_pointer
  0x94d: thread_isr_stack_start
  0x961: cpu_switch_context_exit
  0x966: unreachable381
  0x96d: thread_yield_higher
  0x989: isr_pendsv
  0x9a5: isr_svc
  0x9a9: context_restore
  0x9c1: post_startup
  0x9cd: reset_handler_default
  0xa61: nmi_default
  0xa71: _stack_size_left
  0xa95: hard_fault_default
  0xaa8: fix_msp
  0xaae: test_sp
  0xabc: use_psp
  0xac0: out
  0xad9: hard_fault_handler
  0xcb1: mem_manage_default
  0xcc1: bus_fault_default
  0xcd1: usage_fault_default
  0xce1: debug_mon_default
  0xcf1: isr_systick
  0xd01: irq_disable
  0xd21: irq_enable
  0xd3d: irq_restore
  0xd5b: irq_is_in
  0xd75: bitband_addr
  0xda7: bit_clear32
  0xdcd: cpu_errata_fixes
  0xde1: pre_startup
  0xdf1: isr_wdog_ewm
  0xdfd: wdog_disable
  0xe25: uart_stdio_init
  0xe45: uart_stdio_read
  0xe69: uart_stdio_write
  0xe89: pm_off
  0xe95: board_init
  0xf09: cpu_print_last_instruction
  0xf29: panic_arch
  0xf35: core_panic
  0xf8d: main_trampoline
  0xfb1: idle_thread
  0xfc1: kernel_init
  0x1021: cib_init
  0x1069: thread_add_to_list
  0x10d5: thread_measure_stack_free
  0x1109: thread_create
  0x12a9: NVIC_SystemReset
  0x12d9: cortexm_sleep
  0x1325: pm_set_lowest
  0x1333: pm_reboot
  0x1341: cpu_init
  0x1369: mutex_lock
  0x1381: isrpipe_write_one
  0x13af: isrpipe_read
  0x13e5: NVIC_EnableIRQ
  0x1415: cortexm_isr_end
  0x142d: bitband_addr
  0x145f: bit_set32
  0x1485: uart_init
  0x1515: uart_init_pins
  0x1591: uart_init_uart
  0x169d: uart_write
  0x16f5: irq_handler_uart
  0x1755: isr_uart0_rx_tx
  0x1763: bitband_addr
  0x1795: bit_set32
  0x17b9: bit_set8
  0x17dd: bit_clear8
  0x1801: kinetis_mcg_disable_pll
  0x1815: kinetis_mcg_set_fll_factor
  0x1845: kinetis_mcg_enable_osc
  0x18a9: kinetis_mcg_init_erclk32k
  0x18f9: kinetis_mcg_init_mcgirclk
  0x1989: kinetis_mcg_set_fei
  0x19e9: kinetis_mcg_set_fee
  0x1a2d: kinetis_mcg_set_fbi
  0x1a8d: kinetis_mcg_set_fbe
  0x1ae5: kinetis_mcg_set_blpi
  0x1b09: kinetis_mcg_set_blpe
  0x1b2d: kinetis_mcg_set_pbe
  0x1ba1: kinetis_mcg_set_pee
  0x1bdd: kinetis_mcg_set_mode
  0x1c85: kinetis_mcg_set_safe_mode
  0x1d51: kinetis_mcg_init
  0x1dbd: cortexm_isr_end
  0x1dd5: bitband_addr
  0x1e07: bit_set32
  0x1e2b: port
  0x1e4d: gpio
  0x1e6f: port_num
  0x1e8d: pin_num
  0x1ea9: clk_en
  0x1ed9: get_ctx
  0x1f11: write_map
  0x1f91: ctx_clear
  0x1fb7: gpio_init
  0x204d: gpio_init_port
  0x20c3: gpio_set
  0x20f5: irq_handler
  0x2185: isr_porta
  0x2199: isr_portb
  0x21ad: isr_portc
  0x21c1: isr_portd
  0x21d5: isr_porte
  0x21e9: ps
  0x233d: tsrb_empty
  0x2361: tsrb_full
  0x238b: _push
  0x23bd: _pop
  0x23e9: tsrb_get
  0x2431: tsrb_add_one
  0x2463: periph_init
  0x2471: main
  0x248d: auto_init
  0x2499: list_remove_head
  0x24c1: _mutex_lock
  0x2549: mutex_unlock
  0x25c5: NVIC_SetPriority
  0x2619: cortexm_init
  0x2681: rtc_init
  0x268d: rtc_set_time
  0x26b1: rtc_get_time
  0x26e1: rtc_set_alarm
  0x271d: rtc_get_alarm
  0x274d: rtc_clear_alarm
  0x2765: rtc_poweron
  0x2771: rtc_poweroff
  0x277d: rtc_cb
  0x27a1: NVIC_EnableIRQ
  0x27d1: NVIC_SetPriority
  0x2825: cortexm_isr_end
  0x283d: rtt_init
  0x28a9: rtt_get_counter
  0x28e9: rtt_set_counter
  0x2921: rtt_set_alarm
  0x297d: rtt_get_alarm
  0x299d: rtt_clear_alarm
  0x29d9: rtt_poweron
  0x29fd: rtt_poweroff
  0x2a21: isr_rtc
  0x2a8d: _putchar
  0x2aa5: find_handler
  0x2b15: print_help
  0x2b9d: handle_input_line
  0x2e21: readline
  0x2ed5: print_prompt
  0x2ef9: shell_run
  0x2f29: _reboot_handler
  0x2f41: _ps_handler
  0x2f59: probe
  0x2fbd: probe_all
  0x3001: list
  0x306d: read
  0x30e9: write
  0x31f9: _saul
  0x326d: _alarm_handler
  0x3289: dow
  0x3319: _parse_time
  0x3405: _print_time
  0x344d: _rtc_getalarm
  0x3481: _rtc_setalarm
  0x34d1: _rtc_gettime
  0x3505: _rtc_settime
  0x354d: _rtc_usage
  0x35b1: _rtc_handler
  0x36e5: phydat_dump
  0x3861: phydat_unit_to_str
  0x3969: phydat_prefix_from_scale
  0x3a39: saul_class_to_str
  0x3d75: saul_reg_find_nth
  0x3db5: saul_reg_read
  0x3de5: saul_reg_write
  0x3e15: fmt_u32_dec
  0x3ea9: fmt_s32_dec
  0x3eef: fmt_s16_dfp
  0x3f15: fmt_s32_dfp
  0x4045: fmt_lpad
  0x4095: atoi
  0x409d: _atoi_r
  0x40a5: __errno
  0x40b1: __sflush_r
  0x41dd: _fflush_r
  0x423d: fflush
  0x4261: __fp_lock
  0x4265: _cleanup_r
  0x4271: __fp_unlock
  0x4275: __sfmoreglue
  0x42a5: __sfp
  0x4329: __sinit.part.0
  0x441d: _cleanup
  0x4431: __sinit
  0x4439: __sfp_lock_acquire
  0x443d: __sfp_lock_release
  0x4441: __sinit_lock_acquire
  0x4445: __sinit_lock_release
  0x4449: __fp_lock_all
  0x445d: __fp_unlock_all
  0x4471: _fwalk
  0x44bd: _fwalk_reent
  0x4511: _getchar_r
  0x4539: getchar
  0x4569: gmtime_r
  0x4735: __libc_init_array
  0x477d: memmove
  0x484d: memset
  0x48ed: validate_structure
  0x4b01: mktime
  0x4f0d: _free_r
  0x4fb9: _malloc_r
  0x5081: _iprintf_r
  0x50b1: iprintf
  0x50e9: _putchar_r
  0x510d: putchar
  0x5141: _puts_r
  0x5219: puts
  0x5229: __sread
  0x524d: __seofread
  0x5251: __swrite
  0x5291: __sseek
  0x52b1: __sclose
  0x52c9: strcmp
  0x559d: strncmp
  0x5641: _strtol_l.isra.0
  0x5775: _strtol_r
  0x5779: strtol_l
  0x578d: strtol
  0x57a1: __tzcalc_limits
  0x5921: __tz_lock
  0x5925: __tz_unlock
  0x5929: _tzset_unlocked
  0x5935: tzset
  0x5951: _tzset_unlocked_r
  0x5c85: _tzset_r
  0x5c9d: __swbuf_r
  0x5d4d: __swbuf
  0x5d5d: __swsetup_r
  0x5e5d: div
  0x5e95: _getc_r
  0x5f01: getc
  0x5f71: _findenv_r
  0x5fed: _getenv_r
  0x5ffd: __gettzinfo
  0x6005: __swhatbuf_r
  0x6061: __smakebuf_r
  0x60f5: malloc
  0x6105: free
  0x6115: __malloc_lock
  0x6119: __malloc_unlock
  0x611d: __sfputc_r
  0x6155: __sfputs_r
  0x6185: __sprint_r
  0x61a1: _vfprintf_r
  0x6465: vfprintf
  0x647d: _printf_common
  0x65a9: _printf_i
  0x6841: _putc_r
  0x68c1: putc
  0x694d: __srget_r
  0x69ad: __srget
  0x69bd: siscanf
  0x6a15: _sscanf_r
  0x6a69: strcpy
  0x6b41: strlen
  0x6c1d: _strtoul_l.isra.0
  0x6d5d: _strtoul_r
  0x6d61: strtoul_l
  0x6d75: strtoul
  0x6d89: __env_lock
  0x6d8d: __env_unlock
  0x6d91: __sfvwrite_r
  0x70a1: memchr
  0x7141: memcpy
  0x7275: _realloc_r
  0x72c1: _sungetc_r
  0x733d: __ssrefill_r
  0x7379: __ssvfiscanf_r
  0x76f1: _scanf_chars
  0x77b1: _scanf_i
  0x79c9: lflush
  0x79dd: __srefill_r
  0x7b0d: __sccl
  0x7b7d: __submore
  0x7bf5: _ungetc_r
  0x7ce1: ungetc
  0x7cf1: _malloc_usable_size_r
  0x7d01: __aeabi_ldivmod
  0x7da1: __udivmoddi4
  0x8061: __aeabi_idiv0
  0x82dc: BFARVALID_MASK.6900
  0x82e0: MMARVALID_MASK.6901
  0x8318: assert_crash_message
  0x8378: uart_config
  0x8398: mcg_mode_routing
  0x8694: _shell_command_list
  0x8d0c: _tenmap
  0x8d2c: __sf_fake_stderr
  0x8d4c: __sf_fake_stdout
  0x8d6c: __sf_fake_stdin
  0x8d8c: _global_impure_ptr
  0x8d90: DAYS_IN_MONTH
  0x8dc0: _DAYS_BEFORE_MONTH
  0x8e44: _ctype_
  0x8f48: __month_lengths
  0x9010: __preinit_array_start
  0x9018: _etext
  0x40000: _ram_length
  0x100000: _rom_length
  0x1fff0000: isr_stack
  0x1fff0200: _estack
  0x1fff0204: uart_stdio_isrpipe
  0x1fff0218: main_name
  0x1fff021c: idle_name
  0x1fff0220: state_names
  0x1fff024c: INCORRECT_QUOTING.4835
  0x1fff0250: t.7219
  0x1fff0280: _impure_ptr
  0x1fff0284: impure_data
  0x1fff02e4: _tzname
  0x1fff02f0: tzinfo
  0x1fff0348: environ
  0x1fff034c: max_threads
  0x1fff034d: _tcb_name_offset
  0x1fff0350: _erelocate
  0x1fff0354: sched_context_switch_request
  0x1fff0358: sched_threads
  0x1fff03dc: sched_active_thread
  0x1fff03e0: sched_active_pid
  0x1fff03e4: sched_runqueues
  0x1fff0424: runqueue_bitcache
  0x1fff0428: _rx_buf_mem
  0x1fff0468: crashed
  0x1fff046c: main_stack
  0x1fff0a6c: idle_stack
  0x1fff0b6c: config
  0x1fff0b74: current_mode
  0x1fff0b78: isr_ctx
  0x1fff0bd8: isr_map
  0x1fff0d98: rtc_callback
  0x1fff0d9c: rtt_callback
  0x1fff0dac: saul_reg
  0x1fff0db0: __malloc_free_list
  0x1fff0db4: __malloc_sbrk_start
  0x1fff0db8: prev_tzenv
  0x1fff0dbc: __tzname_std
  0x1fff0dc8: __tzname_dst
  0x1fff0dd4: _timezone
  0x1fff0dd8: _daylight
  0x1fff0ddc: initial_env
  0x1fff0de0: _ezero
  0x20000000: _ram_base_addr
  0x20030000: _eheap
